### ISSUE TITLE
Broken link in @casl/vue README

### ISSUE THREAD

**Issue by li0t** [stalniy/casl#102]
The @casl/ability link is broken it leads to https://www.npmjs.com/packages/casl-ability when it should lead to https://www.npmjs.com/package/@casl/vue.

**Comment by stalniy** [comment]
Hmm...,

I checked all links in `@casl/vue` README and can't find that broken link. Maybe you can create a screenshot?

**Comment by li0t** [comment]
![broken-link](https://user-images.githubusercontent.com/7966280/44109816-60df8a04-9fd4-11e8-8810-92dfec43ab6c.png) That one in the npm package page.

**Comment by stalniy** [comment]
Ah I see. Thanks for the issue! I’ll fix soon

**Comment by stalniy** [comment]
Fixed, will be available in the next version. Currently can be checked in github repo. Thanks again for pointing out!
