### ISSUE TITLE
Incorrect output with cannot clause

### ISSUE THREAD

**Issue by Sieabah** [stalniy/casl#11]
Just been trying to fit this into my application and found getting cannot rules pretty hard to actually be taken as false. I must be missing something.

    var casl = require('casl');

    const ability = casl.AbilityBuilder.define((can, cannot) => {
        cannot('join', 'Room');
    });

    console.log(ability.can('join', 'Room'));

[Or linked here on repl.it](https://repl.it/repls/AzureWhisperedAcaciarat)

Results in true, when I never said it could and explicitly said it couldn't.

**Comment by stalniy** [comment]
Good catch! This is a bug. 

I will try to fix it in few hours. the latest fix time is Monday :)

Thanks!

**Comment by stalniy** [comment]
Fixed will be published as 1.0.4

**Comment by Sieabah** [comment]
Nice, the repl also works now! Thanks for the quick turnaround.
