### ISSUE TITLE
Uncaught TypeError: Cannot read property 'originalRules' of undefined

### ISSUE THREAD

**Issue by rjaguilar** [stalniy/casl#111]
Getting this error when running production build, does not happen on non production builds.

<img width="734" alt="screen shot 2018-09-17 at 1 43 59 pm" src="https://user-images.githubusercontent.com/9665031/45649316-d14e9080-ba7f-11e8-81ae-0e8f668ad6f9.png">

using react - 16.4.1

**Comment by stalniy** [comment]
can you reproduce the same in demo app (https://github.com/stalniy/casl-react-example)?

**Comment by rjaguilar** [comment]
no longer getting this issue - believe our backend was not returning a list of actions to assign to our admin causing the issue. or updating dependencies and ts definitions did the trick.
