### ISSUE TITLE
[casl-vue] how to update ability without component instance

### ISSUE THREAD

**Issue by jiawen-Bees360** [stalniy/casl#112]
I mean, sometimes we want to update the ability in a place that without a component instance , vue-router 's beforeEach hook for example

```
router.beforeEach(async (to, from, next)=>{
   if(to.meta.requiredAuth){
       let projectId = to.params.projectId;
       let roles =  await fetchRoles(projectId);  // fetch user's role of current project.
       let rules = combileRulesOf(roles);  // this will return a rules array.
   
      // then how can I update the ability here ?
      // if this is inside a component, we can simply do  this.$ability.update(rules)
 }
})

```

**Comment by jiawen-Bees360** [comment]
Ah, I know it after reading your code.
Basically we have to provide a `Ability` object when install the abilityPlugin( as the second param), then we can call the `update` method of that object, anywhere I want. 
```js
// in ability.js 
export new Ability();

// in main.js
import {ability} from './ability.js'
Vue.use(abilitiesPlugin, ability);
```

// in vue-router
import {ability} from './ability.js'
router.beforeEach(async (to, from, next)=>{
  ...
  let rules = combileRulesOf(roles);
  ability.update(rules);
  // it works.
}))

**Comment by HadiNiazi** [comment]
@jiawen-Bees360 saved my day, Thank you man
