### ISSUE TITLE
Avoid duplication of rules

### ISSUE THREAD

**Issue by bertho-zero** [stalniy/casl#115]
Hi, I use roles (e.g: user) for which I have default rules, I add rules that depend on the rules of the user.

How to unify the rules to prevent a rule pack from becoming ever bigger?

In my case I have:
```
    [ [ 'remove', 'Activity' ],
      [ 'receive', 'Activity' ],
      [ 'remove', 'Activity' ] ]
```

**Comment by stalniy** [comment]
You can combine multiple actions of the same subject into single array
