### ISSUE TITLE
AbilityModule is not AOT compatible

### ISSUE THREAD

**Issue by dgouissem** [stalniy/casl#126]
Hello,

Trying to use the CASL Angular port, i find that it's not AOT compatible when bundling it in AOT mode.

below the result after running **ng serve --aot --port 2800 --locale fr --live-reload false** command:

`ERROR in Error: Unexpected value 'AbilityModule in ~/node_modules/@casl/angular/index.d.ts' 
imported by the module 'AppModule in ~/src/app/app.module.ts'. Please add a @NgModule annotation.`

**Comment by stalniy** [comment]
Hello,

Thanks for the issue! I'll check it this weekend

**Comment by dgouissem** [comment]
Thank you,
Please do you expect a new release in the next days to fix the issue?

**Comment by stalniy** [comment]
I’m currently out of time) finalizing projects on upwork. 

But yes, I’ll take a look at this today. And there a quick solution than I’ll publish right after the fix

**Comment by stalniy** [comment]
Could you please send me tour version of Angular?

**Comment by dgouissem** [comment]
Actually, we are working on Angular 5 version and we plan to upgrade to Angular 7.
Is there any blog post or online example for a concret use of CASL with Angular?

**Comment by stalniy** [comment]
This is my another leftover :) planned in issue https://github.com/stalniy/casl/issues/5  

I have already started an article but need some free time to finish it. I expect it to be published till the end of November. 

You can read Readme of the project for examples of usage https://github.com/stalniy/casl/blob/master/packages/casl-angular/README.md

**Comment by stalniy** [comment]
I’m the good news: I was able to fix the issue. Need some time to adapt tests
