### ISSUE TITLE
Use subject in Vue list rendering

### ISSUE THREAD

**Issue by matteopolati** [stalniy/casl#130]
Hi, I can not understand how it works in case of a list of objects (Vue).
In my app i've a list of articles (from API) but it seems that '$can' not recognize 'article' object in my rendered list.

Rendered List :

```
<v-card v-for="article in articles" :key="article.id" class="article"> <v-card-title>...</v-card-title> <v-card-actions> <v-btn icon :to="{ name: 'editArticle', params: article }" v-if="$can('manage', article)"> <v-icon>edit</v-icon> </v-btn> </v-card-actions> </v-card>
```

Rules (from API) : 

`[{
            "actions": ["manage"],
            "subject": ["Article"]
}]`

But in rendered page 'edit button' is not showing.

Where i'm doing wrong?

Thanks.

**Comment by stalniy** [comment]
Hi,

Is article a plain object? If so, then CASL can’t detect its type. 

You can read more about this in docs https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html#instance-checks

**Comment by gongon2dotcom** [comment]
Hi Sergii, thanks for you reply.
'articles' is an array of objects returned from an API GET call. I'm trying to replicate the example you posted [here](https://github.com/stalniy/casl-vue-api-example).
For backend i'm using php (Laravel).

I'm going crazy..

Thanks ;-)

**Comment by gongon2dotcom** [comment]
Hi Sergii, I found a solution but I do not know if it's the best way..

`export const ability = new Ability([], {
  subjectName(subject) {
    if (!subject || typeof subject === 'string') {
      return subject;
    }
    return subject.modelName;
  }
})`

..and in my article object i've added 'modulName': 'Article' property..

It works but if you have a better idea ..

**Comment by stalniy** [comment]
Hi Matteo,

Yes, currently this is the only way to go. By the way, you can define property using ES6 `Symbol`, so then it's invisible for the rest of your application.

Few other solutions which you can use:
1. Extend `Ability` class and allow to pass type as an argument to `can` 
2. ` v-if="$can('manage', { modelName: 'Article', ...article })"
