### ISSUE TITLE
@casl/mongoose errors in Typescript

### ISSUE THREAD

**Issue by mckernanin** [stalniy/casl#136]
Typescript 3.2.2,
@casl/mongoose 2.2.2

When running TSC I get the following errors:

<img width="1268" alt="screenshot 2018-12-20 14 14 10" src="https://user-images.githubusercontent.com/6300047/50311274-d4339580-0461-11e9-8968-0c3652c7ace3.png">

**Comment by stalniy** [comment]
Refactored [casl-mongoose-example](https://github.com/stalniy/casl-mongoose-example) to use Typescript and can't reproduce the error. Could you please double check?

**Comment by stalniy** [comment]
Some checklist stuff:
1. Did you install `@types/mongoose`?
2. Did you configure `tsconfig.json`?
3. Do you use ES6 import/export functionality (otherwise ts may not resolve types automatically)?

**Comment by mckernanin** [comment]
I’ll check it out and let you know!

**Comment by mckernanin** [comment]
I had overriden the type declaration for `@casl/ability` in my project. Removing it fixed the issue.

**Comment by stalniy** [comment]
Glad to see you found a solution!
