### ISSUE TITLE
Enhancement: fields a user is allowed to see

### ISSUE THREAD

**Issue by nidkil** [stalniy/casl#137]
Hi Sergii,

Great library!

I know abilities have the option to set fields which can updated. I think it would be beneficial to also be able to specify which fields an ability can view. Not very useful in the frontend, but for the backend of great value. My backend is setup with Feathersjs and I would like to filter out fields that a user is not allowed see to based on the abilities, before passing the data to the frontend.

Is this an enhancement you would consider?

**Comment by stalniy** [comment]
You can define fields which user can read the same way as you define fields which user can update :)

```js

AbilityBuilder.define(()=>{
   can(“read”, “Post”, [“title”, “description”])
})
```

**Comment by nidkil** [comment]
Yep, figured that much out after posting the issue :) Thx for the reply.

**Comment by stalniy** [comment]
Ok, then I’m closing this :) thanks for using CASL!
