### ISSUE TITLE
Question: tips on how to test abilities

### ISSUE THREAD

**Issue by nidkil** [stalniy/casl#138]
Hi Sergii,

Do you have any suggestions how to go about unit testing the defined abilities?

Regards, nidkil

**Comment by mckernanin** [comment]
Here's an example in an app of mine: https://github.com/tahosalodge/unitelections-backend/blob/master/src/modules/user/__tests__/roles.ts

**Comment by stalniy** [comment]
I used custom chai assertion which is defined in https://github.com/stalniy/casl/blob/master/packages/casl-ability/spec/spec_helper.js#L6

To be more expressive

**Comment by stalniy** [comment]
close in favor of #145

**Comment by stalniy** [comment]
> Here's an example in an app of mine: https://github.com/tahosalodge/unitelections-backend/blob/master/src/modules/user/__tests__/roles.ts

file is now here - https://github.com/tahosalodge/unitelections-backend/blob/master/src/utils/__tests__/ability.ts
