### ISSUE TITLE
Very simple example doesn't produce expected result

### ISSUE THREAD

**Issue by RedShift1** [stalniy/casl#153]
In nodejs:

```
const { AbilityBuilder } = require('@casl/ability');

function standardUser()
{
    return AbilityBuilder.define(
        (can, cannot) =>
        {
            can('update', 'bla', { userId: **5** });
        }
    );
}

const abilities = standardUser();

console.log(abilities.can('update', 'bla', {userId: **9**}));
```

The result is true? This is supposed to be false?

**Comment by stalniy** [comment]
You are doing the common mistake when using CASL. 

ability.can and AbilityBuilder.can are different methods with different signatures (you can check TS definitions)

ability.can accepts: action, subject (either instance of subject type or subject type), field

So, your example will work if you do:

```js
class bla {}

const instance = new bla()
bla.userId = ...

ability.can(“update”, instance)
// or
ability.can(“update”, “bla”)
```

**Comment by RedShift1** [comment]
Hmm I read this from the documentation but didn't quite comprehend it, so subtlety here is that whatever you're putting through ability.can needs to be an instance of a class named "bla", it cannot be an anonymous object. So this means anything that's coming in (from a database for example) needs to mapped to a corresponding class (or DTO, or whatever you want to call it). Follow-up question, does it have to be? Can't we just ability.can() anonymous objects?

**Comment by stalniy** [comment]
Close, as at least for now I don't plan to change this. Thanks for the interest in CASL!
