### ISSUE TITLE
React Can component mutates Ability handler array when events are fired

### ISSUE THREAD

**Issue by richard-vc** [stalniy/casl#159]
When the ability object is updated the 'emit' method is fired and there is a foreach over all the attached handlers for the particular event. See [here](https://github.com/stalniy/casl/blob/b5c27e429ba29a76bb043f4c4bbe34b6539ffd35/packages/casl-ability/src/ability.js#L196). 

The problem is, the React Can component attaches a handler that calls 'forceUpdate' which forces a render and the render method removes the old handler and attaches a new one subsequently mutating the handler array. 

A quick fix would be to change the line to the following 
`handlers.map(h => h).forEach(handler => handler(payload));`

**Comment by richard-vc** [comment]
If you had three components like this 
`<Can>1</Can>
<Can>2</Can>
<Can>3</Can>`

After the first render the handler array for 'Updated' would look like the following 
`[
   () => this.forceUpdate(), //Component 1
   () => this.forceUpdate(), //Component 2
   () => this.forceUpdate() //Component 3
]`

When the ability is updated the first handler is triggered, which unregisters the first handler (removes Component 1 handler from the list) then re-registers it (pushing it to the end of the list) After the first handler as fired the handler array now looks like this
`[
   () => this.forceUpdate(), //Component 2
   () => this.forceUpdate(), //Component 3
   () => this.forceUpdate() //Component 1
]`
The foreach loop counter is now pointing to the second element in the list, which is of course the wrong one, resulting in the Component 2 handler never being executed

**Comment by stalniy** [comment]
I see. Thanks for the issue! I’ll fix tomorrow. 

Probably a better solution is to do what you suggested + check whether ability reference changed

**Comment by richard-vc** [comment]
@stalniy Thanks for getting back so quick.

I think checking the Ability reference would fix it in this scenario but I think it may be better to fix it at the `Ability` level as the api would still be broken.

It's not uncommon for event handlers to un-register themselves (one time only subscription) and in this scenario the array would still be mutated during execution of the forEach statement, resulting in any handlers coming next in the invocation list not being fired.

**Comment by stalniy** [comment]
Yes, this is my plan:
- fix on ability level
- fix on react component level

**Comment by stalniy** [comment]
fixed in 
* `@casl/abiliry@3.0.1`
* `@casl/react@1.0.2`

**Comment by richard-vc** [comment]
Nice one. Thanks for the quick fix :-)
