### ISSUE TITLE
Request for Prisma support

### ISSUE THREAD

**Issue by tanekim77** [stalniy/casl#161]
## Requirements

* working on support for https://www.prisma.io/docs/concepts/components/prisma-client
* casl rules needs to be translated in `where` part of prisma query https://www.prisma.io/docs/concepts/components/prisma-client/filtering-and-sorting#filtering
* `toPrismaQuery` should automatically detect queries on related entities and provide the correct `include`  (https://www.prisma.io/docs/concepts/components/prisma-client/relation-queries)
* no support for JSON column in Postgres
* use PrismaWhere object to define conditions in rules, so the DX is more prismy (no need to know MongoQuery)

## Progress
- [x] ~interpreter for model properties~
- [x] custom js interpreter for PrismaQuery
- [x] get Prisma's `WhereInput` type in generic way
- [x] casl rules transformer
- [x] PrimaAbility & types for custom Ability conditions matcher
- [x] testing
- [x] Docs
- [ ] ~add to prisma e2e tests https://github.com/prisma/e2e-tests/~
- [x] prisma example

## Usage

```ts
import { AbilityBuilder } from "@casl/ability";
import { PrismaAbility, toPrismaQuery } from "@casl/prisma";

const { can, build } = new AbilityBuilder(PrismaAbility);

can("read", "User", { firstName: { startsWith: "John" } });

const ability = build();

await prisma.user.findMany({
  include: abilitiesQuery.include,
  where: {
    AND: [
       acessibleBy(ability).User, // permissions conditions
       { // business logic related conditions
         deleted: false
       }
    ]
  ]
});
```

**Questions**:
1. Do I need to add `definePrismaAbility()` similar to `defineAbility` which creates `Ability` instance that supports MongoQuery?

**Comment by stalniy** [comment]
Hi,

Thanks for the issue. Prisma is an interesting project
I’ll need to investigate it. 
Meantime PRs or implementation suggestions are very welcome

**Comment by stalniy** [comment]
Guys, if you are still interested in Prisma.js support, please help to implement interpreter for prisma.js in [ucast](https://github.com/stalniy/ucast) repository.

To do this, you need to implement Prisma interpreter which will convert conditions AST into prisma where statement.

**Comment by stalniy** [comment]
ucast is a library which will eventually replace sift.js and will allow to integrate casl with any database system, including ElasticSearch, Casandra and other NoSQL dbs.

**Comment by stalniy** [comment]
This will be possible to do in userland (including ucast side) when #350 is finished. So, close this as wontfix

**Comment by lloydclosson** [comment]
@stalniy what would you charge to write first-class support for Prisma, what would the timeline be, and how would I pay you.

**Comment by stalniy** [comment]
@lloydclosson 
- it will take about 3-5 days (including docs and tests), depending on whether you have any specific/custom requirements or use cases on how you plan to use prisma and casl together
- you can [support casl js project on open collective](https://opencollective.com/casljs)
- it will cost about $1000

actually it’s pretty same as for TypeORM

**Comment by lloydclosson** [comment]
@stalniy This is great news. What I am looking for the same features available for Moongoose: https://casl.js.org/v5/en/package/casl-mongoose

Would you be ok with me paying $600 initially and $400 when it is complete? Are you available to start immediately? If not when can you start? Will this go in a general release so other people can use it, test it, etc. That is what I would prefer. I am ready to pay today.

**Comment by stalniy** [comment]
@lloydclosson 

1. payment OK
2. I can start on 4th May
3. I’m OK to release it as general release available for everybody
4. Yes, for latest prisma

**Comment by lloydclosson** [comment]
@stalniy 
This is great. I paid the $600. Really looking forward to having this support in CASL. If the timeline on the start / end dates change please let me know.

**Comment by stalniy** [comment]
Sure!

**Comment by stalniy** [comment]
@lloydclosson are you happy with requirements?

**Comment by stalniy** [comment]
The main difference of this package will be conditions language. It will use PrismaWhere conditions structure to define conditions in rules. This will allow people who know Prisma but do not know Mongo easily to start working with CASL and define complex permissions

**Comment by stalniy** [comment]
looks like `include` is not required for relational filters, so no need to collect it

**Comment by lloydclosson** [comment]
Sounds great. I am excited this is getting started. Let me know if I can do
anything else.

**Comment by chaunceyau** [comment]
Super exciting to see this being worked on! I was just exploring different authorization libraries. I'll chip on open collective - thanks @stalniy and @lloydclosson for making it happen!

**Comment by stalniy** [comment]
The major work is done! Tomorrow, I plan to add tests and if all good, I will release the 1st alpha either tomorrow or on Mon

**Comment by stalniy** [comment]
I've just published the 1st alpha release! Everything is working fine, the package is in alpha until I get some positive feedback and we understand that API I've build is developer friendly.

Docs - https://casl.js.org/v5/en/package/casl-prisma 
npm - https://www.npmjs.com/package/@casl/prisma
release - https://github.com/stalniy/casl/releases/tag/%40casl%2Fprisma%401.0.0-alpha.1

**Comment by lloydclosson** [comment]
@stalniy Thank you so much for this.  I won't be able to spend any time really using it until this weekend. I apologize for my delay. I do have two really quick questions and I apologize if the answers are obvious. 

1.) In the readme you show this:

import { User, Post, Prisma } from '@prisma/client';
import { AbilityClass, AbilityBuilder, subject } from '@casl/ability';
import { PrismaAbility, Model } from '@casl/prisma';

type AppAbility = PrismaAbility<[string, Models<{
  User: User,
  Post: Post
}>]>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
const { can, cannot, build } = new AbilityBuilder(AppAbility);

can('read', 'Post', { authorId: 1 });
cannot('read', 'Post', { title: { startsWith: '[WIP]:' } });

const ability = build();
ability.can('read', 'Post');
ability.can('read', subject('Post', { title: '...', authorId: 1 })));

Just copying and pasting the code I have issues with this line: 
type AppAbility = PrismaAbility<[string, Models<{ 
The Models object is not found and if I change it to Model is gives an error as well. What am I missing?

2. Will this work with storing the permissions in a JSON field in the DB as described here? https://casl.js.org/v5/en/cookbook/roles-with-persisted-permissions

**Comment by chaunceyau** [comment]
I believe `Models` should be `Subjects` from `@casl/prisma`

**Comment by stalniy** [comment]
@lloydclosson 

1. @chaunceyau is correct, I used Models name initially but then changed it to Subjects. So, this is a typo I will fix it
2. Yes, you can store it in db but very likely you will need to cast it to particular WhereInput type when retrieving it. I’ll double check whether there is easier way to solve this for your case

**Comment by jthomaschewski** [comment]
> So, feedback is very welcome!
Thank you very much @stalniy  and @lloydclosson for making this possible.

I've implemented this in an existing app and have the following feedback.

- It was easy to get started. It was just a bit confusing to me at first that *all* prisma models must be specified as ability model with the `PrismaAbility` helper - else typescript will complain with a difficult to grasp error message.
In my case I have many models of whom many are not used as ability model at all.
I would prefer this to require only a subset of all prisma models.
It's not a huge issue though, I think it would be good to have this documented.

- The `accessibleBy` helper is awesome! It really helps in all `fetchMany` situations.

- One thing which was confusing/problematic in my case: The prisma `in`-operator is not supported when defining abilities.
e.g:
`can(action, subject, { role: {  in: [ 'user', 'moderator' ] } })` - typescript is happy but it doesn't work  
`can(action, subject, { role: {  $in: [ 'user', 'moderator' ] } })` - typescript complains but it does work  
workaround: `can(action, subject, { role: {  in: [ 'user', 'moderator' ] } } as any )`

it would be good if mongodb-style operators would be accepted in cases where no prisma equivalent is supported

**Comment by stalniy** [comment]
Thank you @jthomaschewski for the feedback!

could you please show examples of 1st and 3rd issues?

It’s quite strange that `in` because there are tests for it: 
https://github.com/stalniy/casl/blob/master/packages/casl-prisma/spec/prismaQuery.spec.ts#L79

**Comment by stalniy** [comment]
Regarding suggestion to support mongo operators. It would be good to get some examples. So, I can evaluate the need. 

The issue with prisma integration is that their types are statically generated and it’s a bit hard to reuse it or build custom ones on top of them. I created several issues in their repo.

**Comment by stalniy** [comment]
@lloydclosson did you have a change to play with casl/prisma?

**Comment by lloydclosson** [comment]
@stalniy I have a use case that is similar to this - https://casl.js.org/v5/en/guide/conditions-in-depth#match-nested-property-value, but it is a property in a related table.

Is it possible to have a condition that follows a relationship to another table? For example this condition:

`{
    action: "read",
    subject: "ReferenceRequest",
    conditions: { "reference.companyId": "${user.company.id}" },
  }`

The RefereneceRequest table has a many to one relationship with the Reference table which has the field I want to make the condition on. I would like accessibleBy(ability).ReferenceRequest work. If this is possible and it requires development, let me know what it would cost and the timeline. Thanks for all you do. It is greatly appreciated.

**Comment by stalniy** [comment]
@lloydclosson use prisma query operators to search over properties of related table. It should work for queries in db and for checks in runtime you need to populate the whole record

**Comment by lloydclosson** [comment]
@stalniy My hope was that accessible by would actually generate that query. The goal for me was to be able to use the accessibleBy(ability) and be confident that it is secured correctly and not have to think about security in the queries. Do you think this is possible. I will pay for development.

**Comment by stalniy** [comment]
`accessibleBy` already generates this :) but you need to define query in terms of Prisma query (without dot notation). For example:

```ts
can('read', 'ReferenceRequest', {
  reference: {
    is: {
      companyId: "${user.company.id}"
   }
  }
})
```

**Comment by lloydclosson** [comment]
@stalniy Thank you! With this knowledge, the Prisma package does everything I need for my app. Thank you for the library.

**Comment by macmillen** [comment]
I am also looking for a way to automatically apply the CASL permissions to all Prisma queries automatically since I am using the [typegraphql-prisma](https://github.com/MichalLytek/typegraphql-prisma) CRUD generator. Is there a way to add the permissions to all Prisma operations (see below) for every Prisma model? Maybe this could be solved with Prisma middlewares.

In theory it should be possible to map all the defined CASL-Prisma abilities to these operations, or am I wrong?
```
aggregate
count
create*
delete*
find*
groupBy
update*
upsert
```

This would enable a really nice workflow:
1. define Prisma models
2. generate CRUD resolvers with [typegraphql-prisma](https://github.com/MichalLytek/typegraphql-prisma)
3. define Prisma-CASL abilities
4. automatically map abilities to all Prisma CRUD operations (e.g. by Prisma middleware?)

**Comment by Orcioly** [comment]
Good afternoon,

I'm starting with casl/prism and I did the test below and it worked, however how do I make it so instead of being: can('read', 'User', { email: 'admin@admin.com' }). How do I search for the email that was logged in?

Then I will refactor the code and separate them into a file for better organization. I need to know how do I check with the logged in user?

Thanks.

Follow the code below:
`
import { accessibleBy, PrismaAbility } from '@casl/prisma';
import {
  User,
  Client,
  Product,
  OrderClient,
  Role,
  Permission,
  UserPermissionRole,
  Prisma,
} from '@prisma/client';
import prismaClient from '../prisma';
import { AbilityClass, AbilityBuilder, subject } from '@casl/ability';
import { Subjects } from '@casl/prisma';

// const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      User: User;
      Client: Client;
      Product: Product;
      OrderClient: OrderClient;
      Role: Role;
      Permission: Permission;
      UserPermissionRole: UserPermissionRole;
    }>,
  ]
>;

const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

const { can, cannot, build } = new AbilityBuilder(AppAbility);

can('read', 'User', { email: 'admin@admin.com' });

const ability = build();
class ListUserService {
  async execute() {
    const user = await prismaClient.user.findMany({
      // include: abilitiesQuery.include,

      where: {
        AND: [accessibleBy(ability).User],
      },
      select: {
        id: true,
        name: true,
        email: true,
        isAdmin: true,
        created_at: true,
        updated_at: true,
      },
    });

    return user;
  }
}

export { ListUserService };


`

**Comment by Orcioly** [comment]
`import { accessibleBy, PrismaAbility } from '@casl/prisma';
import {
  User,
  Client,
  Product,
  OrderClient,
  Role,
  Permission,
  UserPermissionRole,
  Prisma,
} from '@prisma/client';
import prismaClient from '../prisma';
import { AbilityClass, AbilityBuilder, subject } from '@casl/ability';
import { Subjects } from '@casl/prisma';

// const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      User: User;
      Client: Client;
      Product: Product;
      OrderClient: OrderClient;
      Role: Role;
      Permission: Permission;
      UserPermissionRole: UserPermissionRole;
    }>,
  ]
>;

const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

const { can, cannot, build } = new AbilityBuilder(AppAbility);

can('read', 'User', { email: 'admin@admin.com' });

const ability = build();
class ListUserService {
  async execute() {
    const user = await prismaClient.user.findMany({
      // include: abilitiesQuery.include,

      where: {
        AND: [accessibleBy(ability).User],
      },
      select: {
        id: true,
        name: true,
        email: true,
        isAdmin: true,
        created_at: true,
        updated_at: true,
      },
    });

    return user;
  }
}

export { ListUserService };
`

**Comment by Orcioly** [comment]
Good afternoon,

I'm starting with casl/prism and I did the test below and it worked, however how do I make it so instead of being: can('read', 'User', { email: 'admin@admin.com' }). How do I search for the email that was logged in?

Then I will refactor the code and separate them into a file for better organization. I need to know how do I check with the logged in user?

Thanks.

Follow the code below:

```typescript
import { accessibleBy, PrismaAbility } from '@casl/prisma';
import {
  User,
  Client,
  Product,
  OrderClient,
  Role,
  Permission,
  UserPermissionRole,
  Prisma,
} from '@prisma/client';
import prismaClient from '../prisma';
import { AbilityClass, AbilityBuilder, subject } from '@casl/ability';
import { Subjects } from '@casl/prisma';

// const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      User: User;
      Client: Client;
      Product: Product;
      OrderClient: OrderClient;
      Role: Role;
      Permission: Permission;
      UserPermissionRole: UserPermissionRole;
    }>,
  ]
>;

const AppAbility = PrismaAbility as AbilityClass<AppAbility>;

const { can, cannot, build } = new AbilityBuilder(AppAbility);

can('read', 'User', { email: 'admin@admin.com' });

const ability = build();
class ListUserService {
  async execute() {
    const user = await prismaClient.user.findMany({
      // include: abilitiesQuery.include,

      where: {
        AND: [accessibleBy(ability).User],
      },
      select: {
        id: true,
        name: true,
        email: true,
        isAdmin: true,
        created_at: true,
        updated_at: true,
      },
    });

    return user;
  }
}

export { ListUserService };


```

**Comment by enheit** [comment]
Hi @Orcioly, it seems that you need to create a unique ability instance for each HTTP request. Usually, you can do it in middlewares which have access to the current `userId`. For instance, if you use `JWT` + `GraphQL` you should do something like this

```typescript
const context = async (context: ExpressContext): Promise<ContextPayload> => {
  const authroizationHeader = context.req.headers.authorization // "Bearer yJhbGciOiJIUzI1N..."

  const accessToken = authroizationHeader?.replace('Bearer ', '') // "yJhbGciOiJIUzI1N..."
  const accessTokenPayload = await authenticationService.validate(accessToken) // { userId: 1, email: "example@email.com" }

  const abilities = buildAbility(accessTokenPayload) // Abilities were created according to the user information, e.g. email, id etc

  return { abilities } // return ability, and access it from GraphQL resolvers
}

const buildAbility = (user: User) => {
  const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
  
  const { can, cannot, build } = new AbilityBuilder(AppAbility);
  
  can('read', 'User', { email: user.email }); // Here, you add dynamic emails like you wanted

  return build()
} 

```

example of resolver

```typescript
const resolvers = {
  Query: {
    user: async (parent, args, context, info) => {
       const prisma = await prisma.user.findUnique({ where: { id: args.userId } })

       if(!context.ability.can('read', 'User')) { throw new ForbiddenError('You are not allowed to read a user info')

       return user
    }
}
```

I hope it helps

**Comment by enheit** [comment]
> The issue is that GraphQL will not be used in this project

CASL `AbilityBuilder` is not bound to the concrete implementation

> My intention is really to do it in Middleware

Yes, you can use it in middleware. The only think that you need is current user of the session (request). If you have access to this user object, then you "insert" this user into CASL rules as I showed in the previous example.

> The first part you put above would I put in Middleware?

Yes, you can put it inside your authentication middleware. Authentication middleware is a function that is called before any controller. You can use this place to validate JWT as well as construct CASL abilities. 

> Does const resolvers ira within Middleware as well?

Could you elaborate on this?

**Comment by Orcioly** [comment]
Just to understand if the second part of the code you uploaded, I say this code below if it needs to be in the same Middleware file, i.e. continuing below the first code you uploaded or return it to put it inside the User Search Service?

```typescript
const resolvers = {
  Query: {
    user: async (parent, args, context, info) => {
       const prisma = await prisma.user.findUnique({ where: { id: args.userId } })

       if(!context.ability.can('read', 'User')) { 
         throw new ForbiddenError('You are not allowed to read a user info')
       }

       return user
    }
}
```

**Comment by enheit** [comment]
In the first example I showed how to configure CASL and let ability builder to be aware of the current user (who is requesting data). In second example I showed how you can use it inside your services (or wherever you need).

So, yes you can use the second code snippet as an example and mimic this approach in your service (search service)

**Comment by Orcioly** [comment]
Thanks.

**Comment by Orcioly** [comment]
Good afternoon @enheit!

I was looking at your example above where this context is coming from: ExpressContext on the line: const accessTokenPayload = await authenticationService.validate(accessToken) where is this validity coming from? I'm already using JWT and I didn't find this validity.

I will send below my Middleware code that I had already implemented and is already working, but without Casl.

Middleware:

ensureAuthenticated.ts

```typescript
import { Request, Response, NextFunction } from 'express';
import { verify } from 'jsonwebtoken';

interface IPlayload {
  sub: string;
}

export function ensureAuthenticated(
  request: Request,
  response: Response,
  next: NextFunction,
) {
  const authToken = request.headers.authorization;

  if (!authToken) {
    return response.status(401).json({
      errorCode: 'token.invalid',
    });
  }

  const [, token] = authToken.split(' ');

  try {
    const { sub } = verify(
      token,
      process.env.JWT_SECRET as string,
    ) as IPlayload;

    request.user_id = sub;

    return next();
  } catch (err) {
    return response.status(401).json({ errorCode: 'token.expired' });
  }
}


```

**Comment by enheit** [comment]
Hi @Orcioly 

> const accessTokenPayload = await authenticationService.validate(accessToken) where is this validity coming from?

In my example, this line of code

```typescript
...

const accessTokenPayload = await authenticationService.validate(accessToken)

...
```

equals to yours

```typescript
...

const { sub } = verify(
      token,
      process.env.JWT_SECRET as string,
    ) as IPlayload;

    request.user_id = sub;

...
```

They both __verify__ validity of the token and returns it's body. As far I understand your question was how to replace static id of CASL rule with an id of your user.

> however how do I make it so instead of being: can('read', 'User', { email: '[admin@admin.com](mailto:admin@admin.com)' }). How do I search for the email that was logged in?

To replace hardcoded value in the CASL rule (e.g. `'hard_coded_email@email.com'`)

```typescript
...

 can('read', 'User', { email: 'hard_coded_email@email.com' })

...
```

you need to create a function, whcih accepts a `user` object (e.g. `{ userId: 1, email: 'user_admin@email.com }`) and populate CASL rules

```typescript
interface User {
  userId: number
  email: string
}

const buildAbilities = (user: User) => {
  const { can, build } = new AbilityBuilder(PrismaAbility);

  can("read", "User",  { email: user.email });

  return build()
}
```

And use the result of this call wherewer you need. Create it once (per request) and pass it to your controllers (or what you have)

```
const middleware = (req, res, next) => {
    const user = db.user.findById(req.user_id)

    const ability =  buildAbilities(user) // returns list of abilities

    req.ability = ability

   return next()
}

...

const controller = (req, res) => {
  const user = db.user.findById(req.data.requested_user_id) // pseudo code

  if (!req.ability.can('read', 'User', user)) {
    throw new AuthorizationError('You are not allowed to read a user')
  }

  ...
}

```

**Comment by Orcioly** [comment]
Thank you so much for your patience my friend. Examples of him clarified the doubts I had. I will test soon.

Thank you very much.

**Comment by soulchild** [comment]
@stalniy In theory, should it be possible to have a condition reaching down two-levels deep into the relation hierarchy? 

I have the following ability defined:

```ts
can('update', 'ManyToManyLinkTable', ['aColumn'], {
  linkedEntity: {
    nestedLinkedEntity: {
      some: {
        id: someId,
      },
    },
  },
});
```

but when checking the ability with:

```ts
ability.can('update', subject('ManyToManyLinkTable', anEntity), 'aColumn')
```

@casl/prisma complains that:

`"equals" does not supports comparison of arrays and objects`

Am I doing something wrong or is this just not supported?

**Comment by stalniy** [comment]
You need to provide operator for nestedLinkedEntity (I.e., some). Otherwise casl thinks you are trying to use equality comparison with object:  

read the docs: https://casl.js.org/v6/en/package/casl-prisma

**Comment by soulchild** [comment]
Thanks, @stalniy! 

sorry, I should have mentioned that I already tried this: 

```ts
can('update', 'ManyToManyLinkTable', ['aColumn'], {
  linkedEntity: {
    some: {  // some (or any of the other operators) is not allowed there
      nestedLinkedEntity: {
        some: {
          id: someId,
        },
      },
    },
  },
});
```

Or is that not the correct way of using the operators in this case?

**Comment by stalniy** [comment]
As far as I remember this should work

**Comment by soulchild** [comment]
I believe you are correct! I need to do some more testing but I think I have it working now by using the `is` operator. Thanks a lot!

**Comment by adrianwix** [comment]
Is it possible to supply a subject with properties that are different as the ones specified in the prisma models?
I need Casl to work using the Prisma conditions but I need freedom to define them however I want

I have the following

```ts
const rules = [
    {
        subject: 'Task',
        action: 'create',
        conditions: ((opts: CreateTaskRuleOptions): SubjectDefinition => {
            const subject = {
                params: {},
                body: <Prisma.TaskWhereInput>{},
                query: {},
            }

            const body: Prisma.TaskWhereInput = {
                board: {},
            }

            if (opts.visibility || opts.projectId || opts.workspaceId) {
                body.board.project = {}
            }

            if (opts.visibility) body.board.project.visibility = opts.visibility
            if (opts.projectId) body.board.project.id = opts.projectId
            if (opts.workspaceId)
                body.board.project.workspaceId = opts.workspaceId
            if (opts.tenantId) body.board.tenantId = opts.tenantId

            subject.body = body

            return subject
        })(),
    },
]

const ability = new AppAbility(rules)

const request = {
    body: createTaskPayload,
}

const createTaskSubject = {
    body: <CreateTaskDto>{
        // This comes from the request
        ...request.body,
        // This will come from the PIP
        board: {
            id: 1,
            tenantId: 1,
            project: {
                id: 1,
                visibility: ProjectVisibilityEnum.PUBLIC,
                workspaceId: 1,
                workspace: {
                    id: 1,
                    tenantId: 1,
                },
            },
        },
    },
}

ability.can('create', subject('Task', createTaskSubject))
```

But I am getting

```bash
    s [Error]: "equals" does not supports comparison of arrays and objects
        at Object.name [as validate] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@casl/prisma/src/prisma/PrismaQueryParser.ts:24:51)
        at m.value [as parseInstruction] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:111:41)
        at m.value [as parseField] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:101:47)
        at m.defaultOperatorName (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ucast/core/src/parsers/ObjectQueryParser.ts:163:46)
        at m.condition (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@casl/prisma/src/prisma/interpretPrismaQuery.ts:18:40)
        at Object.conditionsMatcher (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@ucast/core/src/translator.ts:15:47)
        at $.this [as i] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@casl/ability/src/Rule.ts:66:64)
        at $.matchesField [as matchesConditions] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@casl/ability/src/Rule.ts:90:3)
        at PrismaAbility.subject [as relevantRuleFor] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@casl/ability/src/PureAbility.ts:29:38)
        at PrismaAbility.args [as can] (/home/adrian/code/posterlab-mvp/nest-backend/node_modules/@casl/ability/src/PureAbility.ts:19:42)
```

**Comment by sidharthv96** [comment]
Will [Client Extensions](https://github.com/prisma/prisma/issues/15074) help with the extra column issue?

**Comment by lance13c** [comment]
@sidharthv96 - Unsure if you are talking about needing to add an extra column to specify the modelName. If you are, yes, the extensions can help.

You can do the following to add the __modelName (or your preferred name) on all results. It will even add it to nested results on relational prisma models you include (i.e. include: { author: true }. There is probably a more efficient way to write this.

This is working for me using prisma version 4.9.0 and nextjs version 12.3.4.

```
const xprisma = prisma.$extends({
  name: 'add-model-name',
  result: {
    user: {
      __modelName: {
        needs: {},
        compute: () => 'User',
      },
    },
    content: {
      __modelName: {
        needs: {},
        compute: () => 'Content',
      },
    }
    // ... etc
  },
});
```

**Comment by orcioly** [comment]
Good morning my friend!

Thank you, I will check.

**Comment by LilaRest** [comment]
Hi there :blush: I've just opened an issue about specifically enforcing CASL fields restrictions on Prisma queries. Feel free to join the discussion: https://github.com/stalniy/casl/issues/760

**Comment by stalniy** [comment]
I've just created an example of CASL + Prisma + Fastify -> https://github.com/stalniy/casl-examples/tree/master/packages/fastify-prisma-blog

So, close this issue as done

**Comment by bsor-dev** [comment]
@stalniy Is it possible to store permissions in database using casl & prisma with complex conditions? I need to add and remove permissions dynamically
