### ISSUE TITLE
overwriting "read all" rule gives the wrong result

### ISSUE THREAD

**Issue by csmarrero** [stalniy/casl#164]
Hi,

First things first, my congratulations for this tool, thanks.
Now the fault I'm having, 
Setting this rules for devel role: 

"rules": [
        { "actions": "read", "subject": "all" },
        { "actions": "read", "subject": "ads", "conditions": { "userId": "{{username}}" } },
        { "actions": "read", "subject": "subscriptions", "conditions": { "userId": "{{username}}" } },
        { "actions": "read", "subject": "channels", "conditions": { "userId": "{{username}}" } }
      ]

I get ALL de ads, subscriptions and channels documents, it does not applies the conditions for this collections. Then I try to unable read for this collections and set again with conditions with the same result. I can read ALL not only mine

"rules": [
        { "actions": "read", "subject": "all" },
        { "actions": "read", "subject": "ads", "inverted": true },
        { "actions": "read", "subject": "subscriptions", "inverted": true },
        { "actions": "read", "subject": "channels", "inverted": true }
        { "actions": "read", "subject": "ads", "conditions": { "userId": "{{username}}" } },
        { "actions": "read", "subject": "subscriptions", "conditions": { "userId": "{{username}}" } },
        { "actions": "read", "subject": "channels", "conditions": { "userId": "{{username}}" } }
      ]

So, in this point I don't know if I'm setting wrong the rules or exist a bug in the code,

Thanks and best regards,

**Comment by stalniy** [comment]
Hello,

As soon as you define `read all`, you can read everything :) despite the conditions in the next rules. Rules are not overlap each other they are applied with logical OR (regular rules, not inverted)

So in your case you said that you can read everything that’s why conditions are not used after all

**Comment by csmarrero** [comment]
Mystery solved. :)

Thanks again.
