### ISSUE TITLE
npm run build hangs

### ISSUE THREAD

**Issue by peebles** [stalniy/casl#166]
I've forked your repo and am attempting to build it, before I start making some mods I am thinking of.  The first problem was that "ngc" was not found so I "npm install --save-dev ngc", and then try "npm run build" again, but this time, after succeeding a number of commands,  it just hangs forever on

```sh
rollup -c ../../tools/rollup.umd.js -i src/extra.js -o dist/umd/extra.js -n casl.extra
```

What am I doing wrong here?

**Comment by stalniy** [comment]
```sh
git clone git@github.com:stalniy/casl.git
cd casl
npm ci
npm run bootstrap
```

After that you can navigate to any package and do `npm run build`. But you don't need actually to do this because tests work with source files. Built files are used only during release process

**Comment by stalniy** [comment]
updated [contribution guidelines](https://github.com/stalniy/casl/blob/master/CONTRIBUTING.md#-submitting-a-pull-request-pr) with this info 

**PS**: `ngc` is a part of `"@angular/compiler-cli"` package. You don't need to install any dependencies manually
