### ISSUE TITLE
casl-react: an alias doesn't work

### ISSUE THREAD

**Issue by shayshu11** [stalniy/casl#169]
Using casl-react (1.0.2) Can component with an doesn't work.
a\of\on\this are fine, the problem is quite clear:
https://github.com/stalniy/casl/blob/master/packages/casl-react/src/Can.js#L72

Using "a" for now,
Thanks!

**Comment by stalniy** [comment]
Hi, 

Thanks for the issue PR is very welcome

**Comment by stalniy** [comment]
fixed in @casl/react@1.0.3
