### ISSUE TITLE
ability update is working only after Refreshing the page in VueJS

### ISSUE THREAD

**Issue by bakhti-uzb** [stalniy/casl#172]
**I used ability in router (vue-router)** like this 
in _router/index.js_
```
{
	path: 'warehouses',
	name: 'Warehouses',
	component: Warehouse,
        meta: {
		hasPerm: ability.can('list', 'warehouse-balances')
		}
},
``` 
and **updating**  ability when `loginSuccess` mutation is executed 
in _store/ability.js_
``` import { Ability } from '@casl/ability'

export const ability = new Ability()

export const abilityPlugin = (store) => {
	ability.update(store.state.rules);
	return store.subscribe((mutation) => {
		switch (mutation.type) {
			case 'loginSuccess':
				let formattedRules = [];
				if(mutation.payload.permissions.length > 0) {
					formattedRules = mutation.payload.permissions.map(perm => {
						let formattedObj = {};
						formattedObj.actions = perm.substr(0, perm.indexOf(' '));
						formattedObj.subject = perm.substr(perm.indexOf(' ')+1);
						return formattedObj;
					})
				}
				ability.update(formattedRules);
				break
			case 'logoutSuccess':
				ability.update([{ actions: 'read', subject: 'all' }])
				break
		}
	})
 } 
```
**But** ability is updating only when page is _refreshed_
I am **checking** the **route meta** in `beforeEach` _guard_ it is **returning false** but it _should be true after login_

_router/index.js_
```
router.beforeEach((to, from, next) => {
	const isPublic = to.matched.some(record => record.meta.public);

	// CHECK IF USER HAS PERMISSION FOR THIS URL
	const isOpen = ('hasPerm' in to.meta) ? !!to.meta.hasPerm : true;
	//ability.update(store.state.rules);

	const onlyWhenLoggedOut = to.matched.some(record => record.meta.onlyWhenLoggedOut);
	const loggedIn = !!TokenService.getToken();
	if (!isPublic && !loggedIn) {
		return next({
			path: '/pages/login',
			query: {redirect: to.fullPath}
		})
	}

	if (!isOpen) {
		return next('/');
	}

	if (loggedIn && onlyWhenLoggedOut) {
		return next('/');
	}

	next();
});
```
I don't know if it is a bug or I am doing something wrong. 
Any help would be appreciated ! 
This issue is also published in <a href="https://forum.vuejs.org/">Forum vuejs</a> here is the link  <a href="https://forum.vuejs.org/t/plugin-for-vuex-only-working-after-refresh/49350">Question about this issue</a>

**Comment by stalniy** [comment]
It’s just the way roger works. 

Do something like this: https://gist.github.com/stalniy/5adcccf8117177078ada0454e6a6d300

Or convert `hasPerm` to a function:

```js
meta: {
   hasPerm: () => ability.can(...)
}
```

and call that function in `beforeEach`

**Comment by stalniy** [comment]
Close as there are no action items from my side. But feel free to request reopen

**Comment by bakhti-uzb** [comment]
Thank you! It worked . I converted **hasPerm** in meta to function like you said. 
But why when it was not a function it didn't work ?

**Comment by stalniy** [comment]
This is the way things works :)

If you do assignment to a variable it will never be changed until you change the variable. You just cached results of the ability, into object key. Vue router is initialized once and its routes are also initialized once and are not re-evaluated in `beforeEach`. 

So, this example is the same as:

```js
let isAllowed = false
const can = () => isAllowed

const route = {
  meta: {
    hasPerm: can()
  }
}

isAllowed = true

console.log(can(), route.meta.hasPerm)
```

**Comment by bakhti-uzb** [comment]
aah got it! Thanks
