### ISSUE TITLE
What data return for session.rules ?

### ISSUE THREAD

**Issue by xmannv** [stalniy/casl#173]
Hello, 

I don't understand what data sample from session.rules. Could you please give me some example data for session.rules.

![screenshot_104](https://user-images.githubusercontent.com/6252311/55153153-b4142080-518c-11e9-96a6-da31d4bc650b.png)

**Comment by stalniy** [comment]
Hello,

Please check Typescript definition (search for `interface Rule`) in docs https://stalniy.github.io/casl/abilities/2017/07/20/define-abilities.html

So, you need to pass an array of such objects.
