### ISSUE TITLE
Dynamic abilities for logged in user for <Can/> and <AbilityContext.Provider/>

### ISSUE THREAD

**Issue by gibelium** [stalniy/casl#174]
I just started to use CASL in a meteor/react context. I am storing the abilities per user within the user object in the mongo collection.

Now I wonder how to use <Can/> or <AbilityContext.Provider/> tags within react components that do update their internal information based on the abilities for the logged in user.

Basically I have something like this where Meteor.user() is null when no user is logged in and Meteor.user().abilities depends on the logged in user.

```
// Can.js
import { Meteor } from 'meteor/meteor';
import { createCanBoundTo } from '@casl/react';
import { AbilityBuilder } from '@casl/ability';

const Can = createCanBoundTo(Meteor.user().abilities);
export { Can };
```

I want to find a way how the Can constant may change based on the logged in user. It works when I use createCanBoundTo in each render function of all our components but I am searching for a more elegant solution where I can define the Can component in a single file and use it via imports.

Any ideas?

**Comment by gibelium** [comment]
I found a way to update the abilities stored in the DB for each user. I decided to use the AbilityContext variant shown in the [casl/react documentation](https://github.com/stalniy/casl/tree/master/packages/casl-react).

#### Updating the abilities based on the logged in user includes three steps:

##### 1) Provide the Meteor.user() as property to App.jsx
````
// AppContainer.jsx
export const AppContainer = withTracker(() => {
  return {
    currentUser: Meteor.user(),
  };
})(App);
````

##### 2) Define the initial state and react on the property changes within App.jsx
````
// App.jsx
  constructor(props) {
    super(props);
    this.state = {
      currentUser: null,
      abilities: null,
    };
  }

  static getDerivedStateFromProps(props, state) {
    let newState = {
      abilities: state.abilities,
    };
    if (props.currentUser === state.currentUser && state.abilities === null) {
      newState.currentUser = state.currentUser;
      newState.abilities = new Ability();
    } else if (props.currentUser !== state.currentUser && props.currentUser !== null) {
      newState.currentUser = props.currentUser;
      newState.abilities = new Ability(props.currentUser.abilities);
    }
    return newState;
  }
````

##### 3) Have a render function that wraps the apps content in a AbilityContext.Provider using the current abilities from the state:
````
// App.jsx

  render() {
    return (
      <AbilityContext.Provider value={this.state.abilities}>
        <BrowserRouter>
          <Route render={({ location }) => this.renderRedirect(location) || this.renderContent(location)} />
        </BrowserRouter>
      </AbilityContext.Provider>
    );
  }
````


**Unfortunately defining the a Can constant in a separate file (e.g. AbilityContext.js see below) and using it in components to check the permissions needs a second call to render() (e.g. a browser refresh) to render the correct content.**
When defining ````const Can = createContextualCan(AbilityContext.Consumer);```` locally in the render function the content is correctly rendered with the first call to render(). Could this be an issue using the AbilityContext.Consumer together with a BrowserRouter?

**Please find a simple showcase at [GitHub](https://github.com/gibelium/meteor-react-antd-casl).**

**Comment by stalniy** [comment]
Hi,

Thanks for the issue I’ll take a look tomorrow. 

Quick note: you need to update ability instance by calling its `update` method

**Comment by gibelium** [comment]
Thank you for your support...

In the meantime I added a new branch **_'ant-menu'_** where I changed the page structure and added a sidebar menu which also seems to ignore the <Can/> component.

Regarding your comment I added the call to the update function to App.jsx line 37 (in both master and ant-menu branch). Is this the right way to trigger the update?

**Comment by stalniy** [comment]
I sent you [PR](https://github.com/gibelium/meteor-react-antd-casl/pull/1). Everything works as expected.

I'm closing this. Thanks for using CASL!

**Comment by gibelium** [comment]
Thank you for this enlightened code changes and thank you very much for the amazing CASL library.
