### ISSUE TITLE
Vue plugin breaks when using UglifyJS Webpack plugin

### ISSUE THREAD

**Issue by brianjohnhanna** [stalniy/casl#175]
Been trying to track down a rather annoying little issue and have not had much luck, hoping there may be some insight on how to fix this.

The problem I'm running into is that when running my Webpack dev config, everything runs fine and all the checks in the app work with the given abilities. However, when running through a production build, I found that checking against _model instances_ did not work as it did when running the webpack-dev-server and the dev conf. (However, checking against model names works)

Works in dev + prod builds:
```
$can('read', 'users')
```

Works in dev but not in production build:
```
$can('read', user)
```

After a lot of troubleshooting, If found that when commenting out the uglify webpack config in `webpack.prod.conf.js`, everything works again.

Here's the uglify block in question
```
{
  plugins: [
    new UglifyJsPlugin({
      uglifyOptions: {
        compress: {
          warnings: false
        }
      },
      sourceMap: config.build.productionSourceMap, // evaluates to true
      parallel: true
    }),
    // ... more plugins
  ]
}
```

I have tried using the [`exclude`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin#exclude) option but no luck there. Any idea what might be causing this and how it could be fixed? I know [`uglifyjs-webpack-plugin`](https://github.com/webpack-contrib/uglifyjs-webpack-plugin) is used in a lot of projects, so hoping that this may help someone else as well.

Probably also worth mentioning that I haven't had any issues with any other dependencies (of which there are a lot, very large project).

**Comment by Olena-Stotska** [comment]
Do you use ES6 classes (or constructor functions) for your models? 

If so, look at https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html#instance-checks (there is an **Important** section below the 2nd paragraph about minification)

**Comment by brianjohnhanna** [comment]
I actually did see that note before creating this issue. However, I am fetching all the data from a remote server and don't have complete control over the classes on the client. I'm using [FeathersVuex](https://github.com/feathers-plus/feathers-vuex) which does a tremendous job at abstracting the remote and store layer in a Vue app, but doesn't give you complete control over the classes (i.e. every class is an instance of `FeathersVuexModel` and I don't see a way to add a static `modelName` method).

What I have done is add a `modelName` property to every resource that comes out of the server, which I figured would avoid any potential issues that could be caused by minification.

Here's the relevant client side logic

```
// ability.js

const ability = new Ability([], {
  subjectName(subject) {
    let name;
    if (!subject || typeof subject === 'string') {
      return subject;
    }
    if (subject.constructor.name === 'FeathersVuexModel') {
      return subject.modelName;
    }
    return name;
  }
});

feathersClient.on('authenticated', res => {
  const rules = res.rules;
  ability.update(unpackRules(res.rules));
});

export default ability;
```

I'm not sure why this wouldn't work even with minification/uglification but it's not. Any ideas?

**Comment by stalniy** [comment]
I guess because `FeathersVuexModel` name is uglified. So your check `subject.constructor.name` doesn’t work. 

So 2 ways to fix:
- use instanceof if possible
- otherwise rely on property existence `return subject.modelName || subject.constructor.modelName`

**Comment by brianjohnhanna** [comment]
That did it! Feels simple now. Thanks for your help and input and a great library!

**Comment by stalniy** [comment]
Cool! You are welcome :)
