### ISSUE TITLE
Upload dist folder to the repo for cdnjs support

### ISSUE THREAD

**Issue by tmikaeld** [stalniy/casl#178]
Would be great if you could upload the dist folder and submit it to cdnjs for inclusion, this way we can easily load casl in a jsfiddle or directly on the front-end when using plain es6 or umd.

**Comment by stalniy** [comment]
Thanks for the issue. I don't like to keep autogenerated code in git repo because of stupid conflicts :)

To include casl and related packages in jsfiddle, you can use `https://unpkg.com`

* https://unpkg.com/@casl/ability@latest
* https://unpkg.com/@casl/vue@latest
* etc

**Comment by tmikaeld** [comment]
Ok, thanks!
