### ISSUE TITLE
`manage` keyword does not work as expected 

### ISSUE THREAD

**Issue by TarekAlQaddy** [stalniy/casl#180]
We are using vue with rails api, in rails we define some users' abilities to be like
action: `manage`, subject: ModelName
But in vue when I try to test any action against the same ModelName subject it returns false, Actually seems like manage is an alias for CRUD actions only I saw that while I was debugging 
![image](https://user-images.githubusercontent.com/17699683/56474385-51efc800-6479-11e9-9e77-471c0f7ceb00.png)

Any solution for this?

**Comment by stalniy** [comment]
Hello,

Indeed `manage` is an alias for CRUD until casl/ability v3. Starting from v3 it’s an alias for any action

**Comment by stalniy** [comment]
So, just upgrade to casl/Vue and casl/ability and it should work as expected

**Comment by stalniy** [comment]
https://github.com/stalniy/casl/blob/master/packages/casl-ability/CHANGELOG.md#breaking-changes

**Comment by stalniy** [comment]
Close as there are no action items
