### ISSUE TITLE
[Vue] Is `this.$ability.update()` limited in its scope?

### ISSUE THREAD

**Issue by wishinghand** [stalniy/casl#181]
When a user logs in, an API call is made to check their permissions, which then gets run through a Vuex action. In the User modules in my Vuex store I import CASL like so:
```
import { Ability } from '@casl/ability'
const ability = new Ability()
```

and in the action I iterate through the permissions like so:
```
params.forEach(permission => {
    ability.update([{subject: permission.subject, actions: permission.action}])
})
```

However, when in a Vue component and I use ``v-if="$can('update', 'Event.Event')"`` to check for a permission, it always resolves as false.

Is `ability.update()` scoped to the Vuex file? Do I need to export it? When I tried `export const ability = new Ability()` there was no change.

**Comment by stalniy** [comment]
Do you have line like this?https://github.com/stalniy/casl-vue-api-example/blob/master/src/main.js#L13

You must use the same instance in Vuex and in Vue plugin

**Comment by wishinghand** [comment]
I did have that line but wasn't updating the same instance. I thought I could just set it up isolated in that one Vuex file. I have it working now after following the example more closely.
