### ISSUE TITLE
No need for vue instance for vue ≥ 2.6.0

### ISSUE THREAD

**Issue by bodograumann** [stalniy/casl#184]
Since vue 2.6.0 you can create an observable with `Vue.observable` (cf. https://vuejs.org/v2/api/#Vue-observable). So you don’t have to create a whole new vue instance in `@casl/vue, createWatcherFor`.

**Comment by stalniy** [comment]
Not sure that I want to restrict usage to 2.6 only right now. But I can use `Vue.util.defineReactive` to simplify this. Thanks! 

By the way, PRs are very welcome!

**Comment by bodograumann** [comment]
I’d be glad to write a PR, but I usually ask for feedback first so that the change has a chance of being accepted.

I don’t know what `Vue.util.defineReactive` does exactly. It seems to be more of an internal functionality so there is no documentation and I would think it shouldn’t be used outside of vue itself.

Of course I did not mean to restrict the vue version to greater 2.6.0. I would suggest `Vue.observable` as an alternative to the existing solution, if it is available. So for older vue version there is always a fallback.

**Comment by stalniy** [comment]
Make sense. I approve the change :)

Thanks!
