### ISSUE TITLE
Allow Ability to accept class or constructor function as subject type

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#187]
This was already done at `AbilityBuilder` level in #58 . This ticket aims to add support for the same thing but at `Ability` level. So,

```js
ability.can('read', User) === ability.can('read', 'User') // true
```
subject type should be detected based ono subject name. Probably all classes and functions should be perceived as subject types

**Comment by ridermansousa-ap** [comment]
And about `ability.can('read', 'User', { id: 1, isAdmin: true }) // true`

Today this generates an error `expects 3rd parameter to be a string`

**Comment by stalniy** [comment]
> And about `ability.can('read', 'User', { id: 1, isAdmin: true }) // true`
> 
> Today this generates an error `expects 3rd parameter to be a string`

This is by design. Please read a link in the error. It has nothing to do with this issue

**Comment by ridermansousa-ap** [comment]
Yes I know.
But my question is, how can I check the ability (with condition) without having a class instance. Just simple object `{  }`

**Comment by stalniy** [comment]
If you need this for the frontend, then you can check examples in my GitHub. There are examples for 4 UI frameworks. 

Anyway read more about `subjectName` option in https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html#instance-checks

**Comment by ridermansousa-ap** [comment]
Awesome!  I can use the `modelName`  attribute.

Thanks @stalniy
