### ISSUE TITLE
[Question] Get permission from AbilityContext to use it in state or as prop

### ISSUE THREAD

**Issue by gibelium** [stalniy/casl#189]
I want to set a form to readonly by wrapping it in a `<fieldset disable={someState}>` tag.

Now I wonder if I can use the AbilityContext which already holds the correct Ability instance to check if for a specific user the form should be en- or disabled. For sure I can create a new Ability object based on the permissions stored for the logged in user in the class component that contains the form but this would somehow mean to duplicate the Ability instance.

Here is a short code snippet which visualizes the described scenario in the first line of the render function:
```javascript
import React from 'react';
import { Form, Input } from 'antd';
import PropTypes from 'prop-types';

class WrappedEditor extends React.Component {
  constructor( props ) {
    super(props);

    this.state = {
      editable: false,
    };
  }

  render() {
    const { getFieldDecorator } = this.props.form;
    return (
      // TODO: How can I use the AbilityContext to set fileset :: disabled to a dynamic permission based value?
        <fieldset disabled={!this.state.editable}>
          <Form id="editor">
            {getFieldDecorator('someText', {
              rules: [{ required: true, message: 'Please enter a text', initialValue: this.props.editableObject.someText }],
            })}
            <Form.Item label="Some Text">
              <Input/>
            </Form.Item>
          </Form>
        </fieldset>
    );
  }
}

WrappedEditor.propTypes = {
  form: PropTypes.object.isRequired,
  editableObject: PropTypes.object.required,
};

const Editor = Form.create()(WrappedEditor);
export {Editor};
```

**Comment by stalniy** [comment]
If you directly use `AbilityContext` then you will be forced to create a new instance of `Ability` for every permission change or user change. 

Alternatively, you can use `<Can passTrough>` which will not hide children but rather allow you to decide what to do with the permission check inside `children function` and later when you call `ability.update` it will trigger rerendering of all `<Can>` components. 

For more information see Readme of CASL/react package: https://github.com/stalniy/casl/blob/master/packages/casl-react/README.md

**Comment by stalniy** [comment]
Hopefully this helps you :)

**Comment by stalniy** [comment]
You may also check this https://codesandbox.io/s/y2vzprmnvz?fontsize=14 for a real example

**Comment by gibelium** [comment]
Thank you for thinking along. The missing link in my brain was about the programatically access to the AbilityContext within a component. I now defined the static `ContextType` within my component and then can access the ability with `this.context.ability`.

```javascript
class WrappedEditor extends React.Component {

...

  render() {
    const { getFieldDecorator } = this.props.form;
    const editorDisabled = !this.context.can('access', 'myEditor');

    return (
      // TODO: How can I use the AbilityContext to set fileset :: disabled to a dynamic permission based value?
      <fieldset disabled={editorDisabled}>
        <Form id="editor">
          {getFieldDecorator('someText', {
            rules: [{ required: true, message: 'Please enter a text', initialValue: this.props.editableObject.someText }],
          })}
          <Form.Item label="Some Text">
            <Input/>
          </Form.Item>
        </Form>
      </fieldset>
    );
  }
}

...

WrappedEditor.contextType = AbilityContext;
const Editor = Form.create()(WrappedEditor);
export {Editor};
```

I guess this is the way to go with the new Context API even though `this.context` is marked as deprecated in my IDE. Might this have something to do with `createContextualCan` returning a `StatelessComponent` which is also marked as deprecated?

**Comment by stalniy** [comment]
I couldn't find deprecation warnings in [React changelog](https://github.com/facebook/react/blob/master/CHANGELOG.md) about this. And no information about deprecation in [docs](https://reactjs.org/docs/context.html#classcontexttype). So, this is the way to go but keep in mind that if you using `Context API` you will need to create a new instance of `Ability` each time you want to update its rules, that means you can't use `ability.update()` method

**Comment by gibelium** [comment]
Thank you for the hint regrading he ability.update() function.

I guess that the deprecation warning is a problem with the WebStorm IDE or some kind of version clash. Perhaps WebStorm cannot handle the context specific deprecation defined in the Context API:

```javascript
        /**
         * If using the new style context, re-declare this in your class to be the
         * `React.ContextType` of your `static contextType`.
         *
         * ```ts
         * static contextType = MyContext
         * context!: React.ContextType<typeof MyContext>
         * ```
         *
         * @deprecated if used without a type annotation, or without static contextType
         * @see https://reactjs.org/docs/legacy-context.html
         */
        // TODO (TypeScript 3.0): unknown
        context: any;
```

The deprecation of `StatelessComponent` is mentioned in the code like this:
```javascript
    /**
     * @deprecated as of recent React versions, function components can no
     * longer be considered 'stateless'. Please use `FunctionComponent` instead.
     *
     * @see [React Hooks](https://reactjs.org/docs/hooks-intro.html)
     */
    type StatelessComponent<P = {}> = FunctionComponent<P>;
```

**Comment by stalniy** [comment]
Thanks for the hint. I will not update this until the next major release. Don’t want to break types for users who uses older version of react
