### ISSUE TITLE
[React] How to use a plain object (or literal) for conditions? 

### ISSUE THREAD

**Issue by enheit** [stalniy/casl#191]
Is it possible to pass a plain object as a conditional parameter? Can't find any example of it. 

```javascript
AbilityBuilder.define((can, cannot) => {
  cannot('delete', 'user', { role: 2 }) // <- 2
});
```

```javascript
// export const Can = createContextualCan(AbilityContext.Consumer);
<Can I="delete" a="user" of={{ role: 1 }}>
    <p>Should be visible</p> // <- is not visible :(
</Can>
```

How to make it work?

**Comment by stalniy** [comment]
Hi,

Thanks for the issue! 
You actually trapped in common pitfall of CASL beginners. In react `<Can>`, both `a` and `of` represents subject to check. 

You can read explanations in this ticket: https://github.com/stalniy/casl/issues/59
Also I’d recommend to double check documentation and example app for React.

**Comment by stalniy** [comment]
Close in favor of https://github.com/stalniy/casl/issues/192

**Comment by enheit** [comment]
@stalniy thank you for clarification, but unfortunately after revising documentation and suggested tickets by you I didn't find any answer for my question.

I understood that I used props in a wrong way and should specify a custom `subjectName` function. 

Could you please give me an example of how to use it correctly? Currently, I would like to do something like this:

```javascript
function subjectName(item) {
    if(typeof item === 'object') {
        return item.__type;
    }

    return item;
}

AbilityBuilder.define({ subjectName }, (can, cannot) => {
    cannot('delete', 'member', { role: 1 })
}
```

```javascript
<Can do="delete" this={{__type: 'member', role: 1}} />
```

There is no obvious example neither in documentation nor stackoverflow.

**Comment by stalniy** [comment]
@enheit actually according to this example:
```js
AbilityBuilder.define({ subjectName }, (can, cannot) => {
    cannot('delete', 'member', { role: 1 })
}
```

 it should not render at all. By default `Ability` forbids all operations unless you allow something to do. Here you have only 1 rule, this rules forbids to delete a member with role = 1. Later you check whether you `can delete member with role equals to 1` and it correctly say you that you can't.

This is a bit explained in https://stalniy.github.io/casl/abilities/2017/07/20/define-abilities.html#combining-abilities

Thanks for the issue! I plan to revisit documentation and improve it this will be more improvement :)

**Comment by projectashik** [comment]
utlize subject function provided by casl to do it.

can("delete", subject("user", {
role: 1,
}), "role");

<Can I="delete" a={subject("user", {
role: 1,
})} field="role" />
