### ISSUE TITLE
Conditions being ignored

### ISSUE THREAD

**Issue by abelta** [stalniy/casl#196]
Been trying for hours but I can't get to make conditions work on an ability.

My current setup is:
```
import { AbilityBuilder } from '@casl/ability';

const subjectName = item => (
  (!item || typeof item === 'string')
    ? item
    : item.type
);

export default AbilityBuilder.define({ subjectName }, (can, cannot) => {
  can('create son', 'father', { id: 1 });
});
```

In my component:
```
<Can
  I="create son"
  on={father}
  ability={ability}
>
```

However, no mater how I code it, it seems like any condition is able to pass and fathers with any id other than 1 have the ability.

Am I doing something wrong?

**Comment by stalniy** [comment]
You can’t use spaces in action name in React’s Can component 

Check CASL/react Readme: https://github.com/stalniy/casl/blob/master/packages/casl-react/README.md

**Comment by stalniy** [comment]
close as duplicate of #157
