### ISSUE TITLE
CASL - GraphQL-yoga. Instance checks.

### ISSUE THREAD

**Issue by wmwart** [stalniy/casl#198]
Hey. Thanks for the project!
I have a question. I try to make an ability check according to the documentation Instance checks:\

> ...
> In case if the default behavior is not satisfied for you, it’s possible to pass custom subjectName option in Ability constructor, which should return passed object type. This may be useful if you want to define actions for RPC procedures (e.g., in CQRS or GraphQL interfaces).
> ...

As subject, the server returns the following object:
```
Object {
	args:Array(1) [Object]
	astNode:Object {kind: "FieldDefinition", description: undefined, name: Object, …}
	deprecationReason:undefined
	description:""
	isDeprecated:false
	name:"Order"
	resolve:async function (...props) { … }
	type:GraphQLObjectType {name: "Order", description: "", astNode: Object, …}
	__proto__:Object {
		...
		constructor:function Object() {
		...
			name:"Object"
		...
		}
	}
}
```
As you can see, the standard function subjectName (subject) does not fit, and as stated in the documentation I wrote my own.

```
const rules = [ { actions:["read"], subject:["Order"]}, ];
const ability = new Ability(rules, { subjectName(subject) {
	if (!subject || typeof subject === 'string') {
		return subject;
	}

	const Type = typeof subject === 'object' ? subject.type : subject;
		return Type.name;
	}
})

ability.can("read", subject ) // false
ability.can("read", "Order" ) // true
```
However, the test fails. Where am I wrong?

**Comment by stalniy** [comment]
Hi,

I guess the issue is somewhere in your code. Your example perfectly works: https://scrimba.com/c/c39PNwSb

**Comment by wmwart** [comment]
It looks very strange. This is the same code that runs on the server. Did you encounter a difference in javascript operation in the browser and on the nodejs server (v10.15.0)?

**Comment by stalniy** [comment]
There is no difference between browser and nodejs version. 

Which package manager do you use? And which version?

**Comment by stalniy** [comment]
![casl-node](https://user-images.githubusercontent.com/1159966/58905602-ccfffb80-8712-11e9-9fd0-b43314653ec4.gif)

**Comment by stalniy** [comment]
So, did you find where the issue is ?

**Comment by wmwart** [comment]
I apologize, now there is no possibility of debugging physically. Please do not close the branch. I will definitely return to this issue and talk about the result.

**Comment by stalniy** [comment]
Any updates?

**Comment by stalniy** [comment]
Close as stale, please fill free to reopen or create a new issue when you have more details
