### ISSUE TITLE
Specify client side data model

### ISSUE THREAD

**Issue by Victordmdb** [stalniy/casl#200]
Currently, the ability package expects the data model to be structure as mongoose structure. But it would be practical if it were possible to specify the data fields (ie `_id`, `name`, `ownerId`...), then in another field specify which data structure it's referring to.

Or perhaps use an "alias" field in the data context in react for example.

My current workaround on the casl-react lib is to augment the data passed to the `Can` component:

`<Can I="update" this={{...data, constructor: {name : "MyStruc" }}} > {...}</Can>`

But this isn't very elegant. Or am I missing something.

**Comment by stalniy** [comment]
what you want to do it to change `subjectName` option. This function allows to determine subject name based on its instance. More info https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html#instance-checks and check this example https://github.com/stalniy/casl-react-example/blob/master/src/config/ability.js#L6

**Comment by Victordmdb** [comment]
@stalniy That work perfectly, you already thought of everything 👍
