### ISSUE TITLE
Is it possible to have rule for any action

### ISSUE THREAD

**Issue by martinschayna** [stalniy/casl#201]
Hi, coming from Java & Apache Shiro. Is there any chance to define a rule for any action with a given (or all) subjects? Such as the asterisk ones in Apache Shiro? E.g.

```
if (admin) {
  can("all", "all");
} else {
  ...
  can("read", "all");
  can("create", ["order", "customer"]);
  can("update", "customer");
  cannot("delete", "order");
}
```
Thanks.

**Comment by stalniy** [comment]
Everything what you wrote works, except of `can('all', 'all')`. It should be `can('manage', 'all')`. You can read more about this in [documentation](https://stalniy.github.io/casl/abilities/2017/07/20/define-abilities.html#can-dsl-function)

**Comment by Mihailoff** [comment]
As a new CASL user, it took some time to discover the special meaning of `can('manage', 'all')`.

I think it would be good to add a more verbose option with an asterisk `can('*', '*')`

Or use predefined constants (then it doesn't matter)
```JS
import { AnyAction, AnySubject } from '@casl/ability'

can(AnyAction, AnySubject)
```

**Comment by stalniy** [comment]
The first example in [the guide](https://casl.js.org/v5/en/guide/intro) uses `manage` and `all` keywords and right after that there is an explanation:

> manage and all are special keywords in CASL. manage represents any action and all represents any subject

At least at this point, I don’t plan to improve this in any way
