### ISSUE TITLE
Casl doesn't work with mongodb discriminator

### ISSUE THREAD

**Issue by Victordmdb** [stalniy/casl#212]
I've tried applying `accessibleBy` to a [mongoose discriminator](https://mongoosejs.com/docs/discriminators.html) but when i do the mongodb isn't actually queried. Any idea how to get it to work?

**Comment by stalniy** [comment]
Ill check it. Could you please share some code so it’s easier to setup for me?

**Comment by Victordmdb** [comment]
Sorry I haven't been able to test this code out

`
const BaseSchema = new mongoose.Schema({
	name : String
});

const ExtendedSchema = new mongoose.Schema({
	type : String
});

const BaseModel = mongoose.model('Base', BaseSchema);

const ExtendedModel = BaseModel.discriminator("Extended", ExtendedSchema);


const document = await ExtendedModel.create({name:"base", type:"extended"});

const { rules, can, cannot } = AbilityBuilder.extract();

can ( "manage", "Base" );

const abilities = new Ability(rules);

ExtendedModel.accessibleBy(abilities).findOneAndUpdate({_id:document._id}, {type:"distended"});
`

**Comment by stalniy** [comment]
I guess the query to Mongo is not sent because there are no permissions to send this query.
You give permission to `manage Base` model but there is no permissions for `Extended` one.

What you need to do is to add 

```js
can('manage', 'Extended')
```

**Comment by stalniy** [comment]
It works. Please check this example: https://github.com/stalniy/casl-mongoose-example/blob/example/disciminator/index.ts

**Comment by stalniy** [comment]
You can actually pass multiple subjects when you define permissions:

```js
can(“read”, [“Event”, “SpecificEvent”, “TooSpecificEvent”])
```

casl allows only 1 subject type per object, so currently it’s impossible to do what you ask and frankly speaking I don’t see much value in this.

**Comment by codemaniac** [comment]
Thanks! Very helpful
