### ISSUE TITLE
Documentation about how testing components wrapped by CASL

### ISSUE THREAD

**Issue by ac-coding** [stalniy/casl#216]
I am running into some issues when trying to implement simple tests for components wrapped by CASL, and I can't find much information about how to implement those test in this kind of cases.

Here is an example of what's happening to me:

I have some simple components that are just wrapped by a simple <Can I="see" a="post>:
````js
const PostSection = () => (
  <Can I="see" a="post">
    {() => (
      <Section>
        [...]
      </Section>
    )}
  </Can>
);
````

But when I try to build a simple test such as the following dummy one it fails to pass the condition and the snapshot ends as a simple `exports['Can I see a post'] = 'null';`

````js
describe('Can I see a post', () => {
  beforeAll(() => {
    ability.update([]);
    const rules = {
      action: 'see',
      subject: 'post',
    };

    ability.update(rules);
  });

  it('Renders just fine', () => {
    const component = renderer.create(<Post />).toJSON();

    expect(component).toMatchSnapshot();
  });
});
````

I have console logged abilities after updating it and its rules are just empty, but I have implemented it as I do in the app itself. I am missing something here (probably very simple) but I just don't see what it is.

**Comment by stalniy** [comment]
You passed rules as an object but it expects to receive an array. So, change your beforeAll to this:

```js
beforeAll(()=>{
  ability.update([{ action: “see”, subject: “post” }])
})
```

**Comment by stalniy** [comment]
Also I’d not recommend using snapshot testing: https://blog.usejournal.com/whats-wrong-with-snapshot-tests-37fbe20dfe8e

**Comment by ac-coding** [comment]
You were right. I didn't spot that I was missing the array. That was an easy one, haha.

Thank you very much (great library by the way!)

_Note: Thanks for the suggestion about avoiding snapshots. I'll take a look to that link._
