### ISSUE TITLE
Check for multiple abilities in logical OR

### ISSUE THREAD

**Issue by rahulpsd18** [stalniy/casl#217]
I can't seem to find a way to check for multiple abilities (logical OR) in the documentation:

My use case is:
Suppose there are 4 possible abilities ('A', 'B', 'C', 'D') on a resource "Product", I want a button to be visible to the user in case he has ability **_A or B_** .

I did came across "Define own aliases" in the [readme](https://stalniy.github.io/casl/abilities/2017/07/20/define-abilities.html#define-own-aliases) which states that we can define "modify" alias as a **combination** of _update_ and _delete_ actions:
> // user can `modify` only if he has **both** `update` and `delete` permission
Ability.addAlias('modify', ['update', 'delete'])

but I need an **"OR"** case instead of **"AND"**.

Any help would be appreciated. Thanks!

**Comment by stalniy** [comment]
There is no support for OR logic. 

Do you have suggestions how to implement it in clear way?

What you can do now:

```js
if (ability.can(“A”, “Product”) || ability.can(“B”, “Product”)) {
  // do something 
}
```

**Comment by stalniy** [comment]
Close due to inactivity. Feel free to suggest and reopen the issue
