### ISSUE TITLE
Recommendation for differences between server and client side structures

### ISSUE THREAD

**Issue by Victordmdb** [stalniy/casl#220]
If the server-side ability is defined as `can("update","Post", { "user" : "me"})`, because the mongoose document just stores an id reference, how to match it if the client-side has a populated "user" field, so that the id is now under a sub-field `_id` like ` { "user" : { "_id" : "me", "name" : "Ben" } }`.

**Comment by stalniy** [comment]
There are 3 ways to handle this:
- probably the easiest one is to use `userId` field and virtual populate in mongoose (I hate when in one case `user` is an id and in another one is an object). So, better to split this. Then send `userId` to the client together with `user` object (looks a bit like a hack)
- add possibility to provide a getter (this is not supported right now), so then you can do something like:

```js
function getField(owner, field) {
  return typeof owner[field] === 'object' && owner[field].id ? owner[field].id : owner[field]
}
```
This is how I approached this issue in the past but this as well looks like a hack
- preprocess rules when send them to client. So, if you know that on the client rule should be `user.id: 5` and not `user: 5`, you can preprocess this logic inside middleware before sending rules to the client. This one is the best in my opinion but here you need to somehow define logic that `user` is transformed to `user.id`

**Comment by Victordmdb** [comment]
I've opted for the 2nd option for sake of expedience but i'll definitely look into that 3rd option.
