### ISSUE TITLE
Casl support custom abilities?

### ISSUE THREAD

**Issue by glopezep** [stalniy/casl#222]
in my project i have custom permissions in these formats:

module-name::actions::add-role
module-name::view-sections::product-services

can i create custom abilities?

**Comment by stalniy** [comment]
You don’t need any customization. What you need to do is to map your permissions to casl’s terminology. 

So, you can use module name as subject. Action as action, possible mapping may look like this:

```js
can(“add”, “module-name.role”)
can(“view”, “module-name.product-service”)
```

**Comment by stalniy** [comment]
Alternatively you can use `all` subject type and your string as action name, so it will look like this:

```js
can(“module-name::actions::add-role”)
can(“module-name::view-sections::product-services”)

// and then check

ability.can('module-name::view-sections::product-services') // true
```

this is undocumented feature which doesn't have TypeScript support but perfectly works in JavaScript. For more details check [this comment](https://github.com/stalniy/casl/issues/107#issuecomment-508181122) and https://github.com/stalniy/casl/issues/107

**Comment by stalniy** [comment]
Close as there is no action items from my point. Feel free to comment and ask any questions
