### ISSUE TITLE
Request for ability to customize instance checks' "discriminator" key other than `instance.constructor.modelName`

### ISSUE THREAD

**Issue by pdfowler** [stalniy/casl#224]
Currently when checking abilities against an instance, the `getSubjectName` function returns either `modelName` or `name` from constructor.

from [utils.js](https://github.com/stalniy/casl/blob/35ca852cbcc3a1d196b0a1fa9230bf2ea2e576e6/packages/casl-ability/src/utils.js#L22)
```
const Type = typeof subject === 'object' ? subject.constructor : subject;

return Type.modelName || Type.name;
```

In my frontend code, this is causing a bit of difficulty maintaining proper model names across my mobX stores. For the most part it works, but when it doesn't, I'm seeing really strange behavior; cross pollination of `modelName` values across stores, etc. Probably some interesting weirdness w/ how JS and my stores implementation references the `instance.constructor` instance.

We hydrate our abilities from the db roughly as follows:
```
    const [user, company] = await Promise.all([
      this.loadRoleAbilities(this.user),
      this.loadCompanyAbilities(this.user),
    ]);

    const abilities = [...user, ...company];

    runInAction(() => {
      this.access = new Ability(abilities);
    });
```

First: Is there an existing way to override the behavior of `getSubjectName`? I see that the `AbilityBuilder` takes `subjectName` as a param, but I'm not sure how that helps on rehydration from the DB in my case.

I have a functional implementation in our app, but I'm still not 100% comfortable with my understanding of CASL. Here are some thoughts on how to handle *my* needs...

1. Allow the use of a discriminator key property directly on the instance, rather than on the constructor. Similar to mongoose discriminators which default to `__t`. 
2. Allow defining a `getSubjectName` function on each instance.
3. Allow defining a global `getSubjectName` override function within the `Ability` constructor

I'm happy to dig in a bit, but would appreciate some guidance before doing so.

**Comment by stalniy** [comment]
`Ability` constructor already supports this:
https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html (Search for `subjectName`)

`subjectName` is a function which accepts subject (2nd arg from `ability.can`) and returns the name of the subject. 

So, you can easily define discriminator logic yourself. There is an example of this for Vue framework. Check this file please:  https://github.com/stalniy/casl-vue-example/blob/master/src/config/ability.js#L6

**Comment by stalniy** [comment]
The requested functionality is available, so I close this. Feel free to comment if you have any questions
