### ISSUE TITLE
Best way to display a message when a user does not have proper ability?

### ISSUE THREAD

**Issue by csaguil** [stalniy/casl#226]
I would like to show a message explaining that a user is not allowed to view a particular field. Ideally, I would like to do something like this:

```
<Can I="click" a="button" otherwise={<h3>You are not allowed to click this button</h3>}>
    
     <Button>Click Me</Button>

</Can> 
```

Is there an easy way to get this sort of functionality?

**Comment by stalniy** [comment]
Hi,

You can use `passThrough` prop and implement the logic by yourself:

```jsx
<Can I="click" a="button" passThrough>{can => can 
   ? <Button>Click Me</Button>
   : <h3>You are not allowed to click this button</h3>
}</Can> 
```

**Comment by stalniy** [comment]
Close as there are no action items from my side. 

Thanks for using CASL!
