### ISSUE TITLE
FeathersJs(v4): getting e.rulesFor is not a function, using objection.js as orm for mariadb

### ISSUE THREAD

**Issue by UDB** [stalniy/casl#228]
I am following [this post for FeathersJs authorization](https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff). New to Feathers.js and objection.js. I am trying to stop a particular category of users  _`the travellers`_ to only able to create and  login i.e. use `find` and `create` to get authenticated and not able to list other travellers i.e. `/users` and `/travellers`. 

The example code given in casl documentation to convert rules to query is for Sequelize, I am using it for Objection.js. I think my naivety in using Objection and Feathers is causing the problem. Please can you suggest a solution?

[source code for abilities.js](https://gist.github.com/UDB/a728ecb513478128109ca9a9d6c03ac2)

[source code for app.hooks.js](https://gist.github.com/UDB/d97438687561a173fe278260686369d6)

[source code for traveller.hooks.js](https://gist.github.com/UDB/e549c20c1638975917b4ea2ccdd6578c)

**Comment by stalniy** [comment]
Sorry, I don’t have experience neither with Feathers 4 nor objection, so can’t help. 

In general the advice is this, after configuring permissions, you can get them from `ability` instance. There is a helper method in `@casl/ability/extra`, `rulesToQuery`. Take a look how it’s used in `@casl/mongoose` to construct db query. 

Basically you need to create a converter permissions -> objection query instance. 

Let me know what you end up with eventually :)
