### ISSUE TITLE
Why did you create own ACL library?

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#231]
Discussion about why existing ACL libraries don't fit project needs. And why people create own solutions.

Feel free to tell me your story in comments, so I will know how to adapt CASL in order to make it more useful

**Comment by weilies** [comment]
i really appreciate i found CASL for Angular at this moment and i really need it! but frankly, the lack of detail documentation probably the reason we develop our own ACL lib

**Comment by stalniy** [comment]
You can find docs about complementary libs in README. For angular. 

https://github.com/stalniy/casl/blob/master/packages/casl-angular/README.md

**Comment by stalniy** [comment]
> i really appreciate i found CASL for Angular at this moment and i really need it! but frankly, the lack of detail documentation probably the reason we develop our own ACL lib

by the way, added links to complementary packages README files, so it will be easier to find them :)

**Comment by stalniy** [comment]
close as there is no much discussion, probably it should be posted as an article or something like that.
