### ISSUE TITLE
Unable to filter with custom type 'Leave', 'claim'

### ISSUE THREAD

**Issue by weilies** [stalniy/casl#232]
i have my code

```
export function defineAbilitiesFor(role) {
  const { can, rules } = AbilityBuilder.extract();

  if (role === "admin") {
    can("manage", "all");
  } else if (role === 'client') {
    
  } else {
    can("read", "Leave" ); 
    can("manage", "Todo", { assignee: "me" });
  }

  return rules;
}
```

```
<div *ngIf="(leave | can: 'read')">  ESS leave read</div>
<div *ngIf="(leave | can: 'update')">  ESS leave update</div>
<div *ngIf="(claim | can: 'read')">  ESS claim read</div>
<div *ngIf="(claim | can: 'update')">  ESS claim update</div>
```
And i want my non-admin to be able to access 'leave' detail but it never show the output 
"ESS leave read"

What's the missing code?

code sample
https://stackblitz.com/edit/ng-casl?file=src%2Fapp%2Fservices%2Fability.service.ts

**Comment by stalniy** [comment]
I’m currently at the conference. Will look at it tomorrow. Thanks for the issue

**Comment by weilies** [comment]
I found the root cause..! it was due to missing ' (single-quote). Once i changed from

`<div *ngIf="(claim | can: 'read')">  ESS claim read</div>`
to **'Claim'**
`<div *ngIf="('Claim' | can: 'read')">  ESS claim read</div>`
and it's now able to detect and filter correctly

**Comment by stalniy** [comment]
I've just looked through your code and yes, you are right. As you don't have property `claim` on your class, then you should use subject type - `Claim`
