### ISSUE TITLE
Angular Example with Custom Pipe or Memoized Ability

### ISSUE THREAD

**Issue by Vbboi24** [stalniy/casl#235]
Hi, Thanks for this awesome library, I saw the ability of the casl to be overloaded. [Link to Performance Issue with Pipe](https://github.com/stalniy/casl/tree/master/packages/casl-angular).

Can i have an example based on the memoized usage / custom pipes which overrides the default ablity of can pipe of casl ?

**Comment by stalniy** [comment]
Hi,

In majority of cases the pipe should work fast enough. 

There is no example with caching. But if you need something general, you can just wrap CanPipe.can method using lodash.memoize but be careful with cache size. You probably will need something as LRU cache store.

**Comment by Vbboi24** [comment]
Thanks for the response, Sure i will try it and revert back.

**Comment by stalniy** [comment]
I’d appreciate if you will leave a link to that example here :)

**Comment by stalniy** [comment]
Close as there is nothing to do from my side. 

Thanks for trusting CASL!
