### ISSUE TITLE
Checking if User Has More than one rule at a Time

### ISSUE THREAD

**Issue by clmorales** [stalniy/casl#237]
How Can I check more than one rule a a time.  What I want is to verify if the user has one of the rules.

The following will return true if the user has this set of rules
can('read','Post)
can('create','Post')
can('read','Task')
can('create','Task')

ability.can(['read','create'], ['Post','Task']); // true;

**Comment by stalniy** [comment]
Just call `ability.can` several times. 

```js
ability.can(“read”, “Task”) && ability.can(“create”, “Task”)
```

Casl doesn’t support arrays in arguments of `ability.can` because the meaning is ambiguous. Some may expect it to check by OR logic (because this is what his app needs) and others will expect AND logic

**Comment by stalniy** [comment]
Close as there is nothing to do from my side. 

Thanks for trusting CASL!
