### ISSUE TITLE
$can is not working with v-if in my nuxt application instead of it's work with with only v-show 

### ISSUE THREAD

**Issue by tapanbavaliya** [stalniy/casl#238]
if use v-if as doc says its shows me error of child node mismatch in server call & client call, please tell me what to do in this case.
v-show is not ideal case to use in case of v-if, please suggest me.

i am using these plugins
```
"@casl/ability": "^3.2.0",
"@casl/vue": "^0.5.1",
```

`/static/roles_permissions.js`
```js
export function c(can) {
  can('book', 'read');
  can('book', 'update');
  can('book', 'add');
}
```

`/plugins/ability.js`
```js
import { c } from '@/static/js/roles_permissions';
import { AbilityBuilder } from '@casl/ability';

export const ability = AbilityBuilder.define(can => c(can));

export default function({ store }, inject) {
  ability.update(store.state.permissions);
  inject('ability', ability);
  if (process.client) {
    if (store.state.permissions && store.state.permissions.length) {
      localStorage.setItem('permissions', store.state.permissions.length);
    } else {
      localStorage.removeItem('permissions');
    }
  }
  return store.subscribe((mutation, state) => {
    switch (mutation.type) {
      case 'setUser':
        ability.update(state.permissions);
        inject('ability', ability);
        break;
    }
  });
}

```

plugin -> `/plugins/casl.js`

```js
import Vue from 'vue';
import { abilitiesPlugin } from '@casl/vue';
import { ability } from '@/plugins/ability.js';

Vue.use(abilitiesPlugin, ability);
```

`pages/books.js`
```vue
<template>
  <div>
    <div v-show="$can('book', 'read')">
      <books />
    </div>
    <div v-show="!$can('book', 'read')">
      <no_permission />
    </div>
  </div>
</template>

<script>
import books from '@/components/books.vue';
import no_permission from '@/components/no_permission.vue';

export default {
  middleware: 'authenticated',
  components: {
    books,
    no_permission
  },
  async asyncData({ store, params, route, redirect, query, app }) {
    store.commit('books', {});

    if (app.$ability.can('books', 'read')) {
      store.commit('isLoading', true);
      await store
        .dispatch('books')
        .then(() => {
          store.commit('isLoading', false);
        })
        .catch(() => {
          store.commit('isLoading', false);
        });
    }

    return {};
  }
};
</script>
```

i am using vuex also & permissions will be updated using `nuxtServerInit` using JWT token

`/store/actions.js`
```js
nuxtServerInit({ commit }, { req }) {
    let user = null;
    /* istanbul ignore else */
    if (req.headers.cookie) {
      const cookieparser = process.server ? require('cookieparser') : undefined;
      const parsed = cookieparser.parse(req.headers.cookie);
      /* istanbul ignore else */
      if (parsed.jwt_auth) {
        try {
          const jwtDecode = require('jwt-decode');
          const decodedJWT = jwtDecode(parsed.jwt_auth);
          user = decodedJWT;
        } catch (err) {
          // No valid cookie found
        }
      }
    }
    commit('setUser', user);
  },
```

**Comment by stalniy** [comment]
As far as I see you store `permissions.length` In localStorage, is this correct? Shouldn’t you store `permissions`?

Also a working example on codesandbox or scrimba would be more helpful. 

I don’t think that the issue is in casl. It is completely isomorphic, i.e. doesn’t use any browser or server specific functions.

**Comment by stalniy** [comment]
@tapanbavaliya did you solve the issue?

**Comment by stalniy** [comment]
@tapanbavaliya please provide a working example (github repo or codesandbox), so I can easily reproduce the issue.

**Comment by tapanbavaliya** [comment]
sorry for the late reply. we using JWT token to extract the permissions list & the issue it that we don't get problems in locally, but we do get issue when we deploy in server, at that time issue across.

**Comment by stalniy** [comment]
so, are you saying that locally everything works as expected but when you deploy the app you see this error?

**Comment by tapanbavaliya** [comment]
> so, are you saying that locally everything works as expected but when you deploy the app you see this error?

true @stalniy.

**Comment by tapanbavaliya** [comment]
and sad part is that i couldn't give you demo so you can give in more, all that i have this code to show you @stalniy

**Comment by stalniy** [comment]
I guess the issue is in different permissions during server rendering and ui rendering. Please check whether it's a case

**Comment by tapanbavaliya** [comment]
let's consider you case, then why it's not giving error in development. it should give error in development also.

**Comment by stalniy** [comment]
From what I see you use casl and nuxt a bit incorrectly:
about nuxt:
- why do you put permissions in js file inside `static` folder?

about casl:
- you mixed up subject and action names (it must be `can('read', 'book')`)

**Comment by stalniy** [comment]
I cannot reproduce your issue. Please check this repo - https://github.com/stalniy/casl-nuxt-example it seems like everything works just fine

**Comment by tapanbavaliya** [comment]
can you deploy this somewhere @stalniy, if that reproduce error.

**Comment by stalniy** [comment]
hey :) 

I do this in my spare time, so please if you care about your question, `git clone` and run it locally or deploy where-ever you need/want.

It does not reproduce the error, all works good.

**Comment by tapanbavaliya** [comment]
thanks for this help, will dig in my own now, if resolve will update you can close this question for now.

**Comment by KamranMaqbool** [comment]
> I cannot reproduce your issue. Please check this repo - https://github.com/stalniy/casl-nuxt-example it seems like everything works just fine

this repo give error
type error
_casl_ability__WEBPACK_IMPORTED_MODULE_1__.AbilityBuilder.define is not a function

**Comment by stalniy** [comment]
Did you use `npm ci` to install reps from package-lock?
