### ISSUE TITLE
"TypeError: Cannot read property 'can' of undefined" testing in React with Enzyme

### ISSUE THREAD

**Issue by GianfrancoCorrea** [stalniy/casl#240]
I'm trying to test but I can't mount the components

![image](https://user-images.githubusercontent.com/46355516/69641815-9bbc1480-103f-11ea-8f79-c199377213d7.png)

in jest.setup.js I have a global.ability to set it globally, and the tests have access 
![image](https://user-images.githubusercontent.com/46355516/69642005-e342a080-103f-11ea-834e-4e91714661d1.png)

any idea to can mount my components? with shallow aren't problems

"@casl/ability": "3.2.0"
"react": "16.8.4",
"react-dom": "16.8.4",
"enzyme": "3.9.0",
"enzyme-adapter-react-16": "1.13.0",
"jest": "24.6.0",

**Comment by stalniy** [comment]
From dependencies I see that you don’t use `@casl/react` and `@casl/ability` is a pure es6 code. 

So, the issue is somewhere in your components. Probably you have a race condition between assigning global ability and component creation

**Comment by stalniy** [comment]
Try to reproduce on codesandbox or similar and provide an example if the issue is reproducible with simple setup.

**Comment by stalniy** [comment]
@GianfrancoCorrea did you solve the issue?

**Comment by stalniy** [comment]
close as stale. Please fill free to reopen the issue if you think I can do something with this. But please provide a working example, so I can easily reproduce it.

**Comment by givethemheller** [comment]
@stalniy I actually just thit this. No React involved, but Jest is the test runner. User SuperTest for api testing. 

Seen anything similar to this lately?

**Comment by stalniy** [comment]
@givethemheller Could you please provide a minimum steps to reproduce, repl or codesandbox?

**Comment by givethemheller** [comment]
yeah - its pretty odd.
My use case essentially - working on a repro
```
import { AbilityBuilder, Ability } from "@casl/ability";
export function defineAbilityFor( user: User){
  const { can, cannot, rules } = new AbilityBuilder();
  console.log(can, cannot, rules)
 // logs [Function (anonymous)] [Function (anonymous)] [] as expected
  can("view", "UserModel");
  // throws TypeError: Cannot read property 'can' of undefined
  return new Ability(rules);
}
```

**Comment by givethemheller** [comment]
https://codesandbox.io/s/caslability-debug-74v99?file=/src/App.tsx

**Comment by stalniy** [comment]
Replied in #289
