### ISSUE TITLE
Error in documentation

### ISSUE THREAD

**Issue by bodograumann** [stalniy/casl#242]
On https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html you write about `throwUnlessCan`.
In the example you use `cannot` for subject `Product`, but then check for `Post`. According to the description I would assume that it should be `Post` everywhere, but the error message

```console.log(error.subject) // "Post", does not equal `subjectName` when check on instance```

confuses me.

**Comment by stalniy** [comment]
Thanks for the issue I will check it today!

**Comment by stalniy** [comment]
Indeed, fixed. Thanks again!
