### ISSUE TITLE
Receiving rules from API

### ISSUE THREAD

**Issue by JoakimBrandt** [stalniy/casl#244]
Hi!

I'm mighty impressed by this library and I will find it extremely useful as soon as I get the hang of updating the ruleset for the current user by an API call.

> ability.js

```
import { AbilityBuilder } from '@casl/ability'

export default AbilityBuilder.define(can => {
  
})
```

> if user successfully signs in and receives a token containing the rules
```
const decodedToken = jwt.verify(localStorage.getItem('rules_token'), 'secret')
this.$ability = new Ability(decodedToken.rules)
```

> hard coded rules sent from the REST API
```
 const rulesToken = jwt.sign({
                        id: user.userid,
                        rules: [
                            {
                                "actions": ["read"],
                                "subject": ["testing"]
                            },
                            {
                                "actions": ["read"],
                                "subject": ["yeehaw"]
                            }
                        ]
                    }, jwtSecret, { expiresIn: "1h" }, { jti: randomString.generate(7) });
```

> user profile page, where he/she is taken after successful login
```
<div v-if="$can('read', 'testing')">
                            You can read this
                        </div>
```

I can't see the "You can read this" unless I add "can('read', 'all')" to the export in ability.js. I have tried working around this for a whole day now, I'd really love some assistance.

**Comment by stalniy** [comment]
Hi, 

I’m glad that you was impressed :)

So, quick answer - please setup this repository https://github.com/stalniy/casl-vue-api-example together with complementary one for nodejs

**the reason ** why it doesn’t work is that `this.$ability = ...` doesn’t update the ability in the app but just for this component (this is how JS prototype inheritance works). That’s why you don’t see the expected result

The right way is not to change $ability but to update it `this.$ability.update(rulesFromToken)`

**Comment by JoakimBrandt** [comment]
It was the this.$ability.update that solved it, as you said! I had problems with that specific method earlier, but now it is working smoooooothly. Thanks a lot!

**Comment by stalniy** [comment]
Cool! So, let’s close the issue. 

Thanks for trusting casl!
