### ISSUE TITLE
Support for redux / monorepo (nrwl nx)

### ISSUE THREAD

**Issue by iangregsondev** [stalniy/casl#247]
Hi,

I was wondering if there is an example with redux (react). My situation is that I am using Nrwl NX to separate code. So my libs are separated into features.

I was hoping for some example of storing the data in a store (redux) and each feature asking for "it's" permissions - is there some kind of examples?

Also, I was wondering if abilities (defining) can be set in different files.

The library looks great but I am still a little confused about how to implement using a redux/ monorepo 

Any help really appreciated, or examples on github would be helpful.

**Comment by stalniy** [comment]
Please go through comments in [these issue](https://github.com/stalniy/casl/issues?q=is%3Aissue+redux+is%3Aclosed) and you will find some examples for redux and react

**Comment by iangregsondev** [comment]
Ok, thank you. I will take a look now.
