### ISSUE TITLE
Sift 9.0.4 syntax error on IE 11

### ISSUE THREAD

**Issue by anderschbe** [stalniy/casl#250]
I know I know, it would be great if that f... browser would finally die, but when I tried to update our @casl/ability to 3.3.0, I run into sift trouble again. 

How to reproduce: 

update @casl/ability to 3.3.0 on a aurelia (or probably any webpack) framework), with sift dependency  going to 9.0.4

-> syntax error sift... min.js could not be found.

**Comment by stalniy** [comment]
I don’t think this is an issue of IE11.

Could you please tell what package manager and version you use (npm or yarn)? 

And send me please output of `npm ls sift`

**Comment by raduflp** [comment]
looks like the latest `sift` release breaks IE 
in `sift.min.js` you have on line 134 `$in: (n, t) => n(t),` which breaks IE as arrow functions are not supported

**Comment by stalniy** [comment]
Could you please create the same issue for sift?

Cc: @crcn

**Comment by stalniy** [comment]
Ok, looks like it should be fixed in 9.0.6, so close this
