### ISSUE TITLE
Can I use top-level operators in can/cannot rules?

### ISSUE THREAD

**Issue by jnardone** [stalniy/casl#252]
I'm trying to track down some failures when we went from 3.2.0->3.4.0 (well, 3.3.0 is where the breakage is, likely with the bump of `sift`).  Our automated tests have some failures and the rules they're failing on seem to follow a specific pattern.

      can('read', 'thing', {
        $and: [{ thing: { $ne: 50 } }]
      });

Namely: it appears any rule that has a top-level operator like this in the `conditions` section.  We do  both `$or` and `$and` and these worked in 3.2.0 but fail now.

So:
- is this a syntax that should work?
- if not, do you have any suggestions on how this would be expressed?  We want to append additional things to compare against the resource row

**Comment by stalniy** [comment]
This is documented in “combining abilities” section here - https://stalniy.github.io/casl/abilities/2017/07/20/define-abilities.html
