### ISSUE TITLE
Check for "all" entities instead of "at least one"

### ISSUE THREAD

**Issue by Varkal** [stalniy/casl#259]
Hi, 

I currently have this ability : 

    can("read", "User", { id: this.id });

Basically, every user in the app have the permission to read their own profile. But admins can read every profiles so, they have this ability

    can("read", "User");

And everything is ok for individual profiles check.

But il also have a list of all users. And only admin can see this list. 

The check `can("read", "User");` returns true for both, because, as specified in the documentation, every user can read at least one user : themselves. 

How can I check for "can read ALL users" ? 

Thanks you in advance for response

**Comment by stalniy** [comment]
You need to have logic like this:

```js

If (user.isAdmin) {
  can(“read”, “User”)
} else {
  can(“read”, “User”, { id: user.id })
}
```

**Comment by Varkal** [comment]
Sorry, but i don't understand. It's already what i've done : 

This is a code who build my ability 
```typescript
getAbility() {
    return AbilityBuilder.define((can: Function) => {
      if(!this.roles.length) { //You don't have any roles, you're a basic user, so give only default permissions
          can("read", "User", {id: this.id})
      }
      else {
          this.roles
            .reduce((acc, cur) => new Set([...acc, ...cur.permissions]), new Set<Permission>())
            .forEach(permission => {
              //Map my custom permission objects to CASL can() calls 
              //For example, Customer service people have this permission :  
              can("read", "User")
        });
      }
    });
}
```


But later, when i check the permission to see the users list, which should be only accessible to users with the right permission, i can't do 
```typescript
   currentUser.getAbility().can("read", "User")
```

Because everyone match this check. 
I can't check for roles, because, they are dynamicaly create from an interface.

Maybe this doesn't have any solution than casl can provide, but seems a very basic usage from my point of view

**Comment by stalniy** [comment]
Ok. I understood where the issue is. When user has permission like this:

```js
can('read', 'User', { id: user.id })
```

In my expectations, the next code:

```js
const users = await userService.findAll()
```

should return an array with single record because user can read information about himself. CASL was built based on this concept. `@casl/mongoose` provides this kind of functionality, so you can write `User.accessibleBy(ability).find()` and it returns an array with single record for the described case.

You want a bit **different behavior**, you want the example above to return an error (in terms of REST or other API). So, what you can do is to define a separate action (e.g., `readList`) or subject (e.g., `UserList`) for user list. 

```js
return AbilityBuilder.define((can: Function) => {
  if(!this.roles.length) { //You don't have any roles, you're a basic user, so give only default permissions
      can("read", "User", { id: this.id })
  }
  else {
      this.roles
        .reduce((acc, cur) => new Set([...acc, ...cur.permissions]), new Set<Permission>())
        .forEach(permission => {
          //Map my custom permission objects to CASL can() calls 
          //For example, Customer service people have this permission :  
          can("read", "User")
          can("readList", "User")
    });
  }
});

// later
currentUser.getAbility().can("readList", "User")
```

Use whatever you think is better.

**Comment by Varkal** [comment]
Ok, i've got it! 

Thank you very much for your help !

**Comment by Gleb-Gaiduk** [comment]
Help please: https://stackoverflow.com/questions/70584146/nest-js-authorization-with-casl-doesnt-work-as-expected
