### ISSUE TITLE
Timing problem when persisting state

### ISSUE THREAD

**Issue by GsHeri** [stalniy/casl#262]
heya,
i'm using casl-vue in a vue app with vuex-persistedstate

## This is fixed for now by updating permissions in App.vue:created()
~in my sidebar i have 
```
<v-list-item v-if="$can('view', 'modFunctions')">
```
everything works when i log into an account, the menu point is being displayed for users that are mods.

the problem is if i refresh the page (and reload state from localstorage), it's not working.~

in another place, i have
```
router.beforeEach((to, from, next) => {
  if (!to.meta.accessRestricted || (to.meta.accessRestricted && router.app && router.app.$can('view', to.name))) {
    next()
  } else {
    console.log('access restricted! redirecting to dashboard')
    next('dashboard')
  }
```
which also works when logging in normally, but if i refresh on that same page, this guard doesn't work anymore, because `$can is not a function`

i assume casl (or $can) is loaded too late to work with reloading/persisted state.
is there something i can do to fix this? has something like this ever been reported? am i just doing something wrong?

#UPDATE  
I've managed to fix the sidebar menu problem by forcing an ability-update in the App.vue:created() hook

the above mentioned route guard doesn't get fixed that way though, because the route guard seems to be evaluated before everything else. this is my console output when refreshing the page (i put console.logs in the respective hooks)

```
index.js?cb0f:186 route guard
main.js?c112:129 beforecreate
main.js?c112:126 created
App.vue?234e:372 app.vue beforecreate
App.vue?234e:381 app.vue created
```
i want to block certain routes for "non-mods" in this case. pretty sure that's possible. is my approach completely wrong?

i'd really appreciate any help, thanks <3

**Comment by stalniy** [comment]
Hi

Casl is not responsible for retiring state in your app. You need to do it yourself. Take a look at this line in example repo: https://github.com/stalniy/casl-vue-api-example/blob/master/src/store/ability.js#L4

**Comment by stalniy** [comment]
Closing as this is not an issue in casl or something I can fix. 

Thanks for using casl!

**Comment by GsHeri** [comment]
sorry but yes, i know that :D
like i said, i'm using vuex-persistedstate to persist my state.. :D 
my problem is that i need to have the "can" function ready before (or when) vue route guards are evaluated.
if this is not possible to do, then nevermind and sorry for bringing it up again <3
and i was hoping you know a way how to do that

**Comment by stalniy** [comment]
Don't call `new Vue` in `main.js` until you restore state in vuex. SOmething like this:

```js
// main.js
restoreVuexState()
  .then(() => new Vue({ .... }))
```

**Comment by GsHeri** [comment]
nice! i think i can work something out with that. thank you very much! <3
