### ISSUE TITLE
Investigate possibility to replace lerna with pnpm or yarn

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#263]
This will allow to get rid of `.npmrc` with its onload-script. The main issue with that is if some npm script fails it shows an error that cannot load `onload-script` and it confuses a lot

**Comment by mrfambo** [comment]
Just out of Curiosity. Any specific reason to shift away from Lerna to pnpm or yarn?

**Comment by stalniy** [comment]
I only use Lerna to link packages between themselves. yarn and pnpm supports this out of box, so no need for extra bootstrap step and extra dev dependency
