### ISSUE TITLE
Download ability using fetch/vue-resource in VUE

### ISSUE THREAD

**Issue by Ewelina436** [stalniy/casl#269]
I need to download the ability from external api. I have already tried many ways but I still have problems.  My external returns json: { "actions":"update", "subject":"Trasa1" }

This is my code:
in _components/Permission.vue_:
```
created() {
  this.$http.get(`http://localhost/permissionuser1.js`)
        .then(response => response.json())
        .then(function(result){
          this.prepareAbility(result);
        });
}

methods: {
      prepareAbility: function(result){
        this.myAbility= new Ability([result]);  
        console.log(this.myAbility.can('update', 'Trasa1'))  //turns back the truth and that's ok
    },
```

Only in function returns correct result: true. He gets a mistake everywhere else in the component:
"TypeError: _vm.myAbility.can is not a function".
__________
I also tried to use fetch and ability.update, but it returns false:
in _components/Permission.vue_:

```
import {ability} from '../permission'

fetch(`http://localhost/permissionuser1.js`)//dla SOP
      .then(response => response.json())
      .then(data=> {
      ability.update(data);
      });

```
in _permission/index.js_:
```
export const ability = AbilityBuilder.define(can => {
  can('read', 'Post');
});
```
but return false...

Please help...

**Comment by stalniy** [comment]
Please check this vue api example https://github.com/stalniy/casl-vue-api-example . There is no difference whether you fetch using vue resource, fetch API, axios or GraphQL.

And also check this [README](https://github.com/stalniy/casl/tree/master/packages/casl-vue)
