### ISSUE TITLE
<Can /> or condition

### ISSUE THREAD

**Issue by jkeruzec** [stalniy/casl#278]
Hi,

Versions used : 
```
"@casl/ability": "^3.4.0",
"@casl/react": "^1.0.4",
```

New to casl React, I've set it up with my permissions model and rest services.
I've used it on a first component successfully : 
```js
 <Can I="create" a="product">
        <Button variant="contained" className={classes.button} size="small" onClick={this.startCreation} data-cy="create-user-button">
              <AddIcon classes={{root: classes.iconThemeColorGreen}} className={classes.leftIcon} />
                   Create {this.componentName}
          </Button>
 </Can>
```

But now, I have a case where user can go on a product with one button and permission Read OR Edit.

How can I make it using usefull component  `<Can />` and without having to write a multiple test with `ability.can || ability.can` .. and create a specific variable injected in my JSX afterwards ? 

Thanks,

**Comment by stalniy** [comment]
Hi,

In my assumption if user can edit then he can read. So, just check if user can read and on the next view show button only if user can edit.

I don't see other ways to achieve what you ask, except if you use `useContext` or `contextType` to inject `Ability` instance and do checks yourself.

CASL doesn't support "OR" and "AND" logic in its parameters because it's hard to express so that it's clear for everybody (if you pass an array some people may assume OR logic and other AND)

**Comment by stalniy** [comment]
Unfortunately there is nothing I can do with this. If you have suggestion, go ahead and share it!

**Comment by jkeruzec** [comment]
Yeah, Thank you for your anwsers !  I understand.

Finally, I had to set up all my tests in my app. So I did a wrapper to ability.can with some options array,..., any,... 

I will do if necessary someday a special Can component of my own.. to do what I want.

Thanks.

**Comment by stalniy** [comment]
OK, let me know if you find a good way to express this logic!

**Comment by lasithaguruge** [comment]
> Yeah, Thank you for your anwsers ! I understand.
> 
> Finally, I had to set up all my tests in my app. So I did a wrapper to ability.can with some options array,..., any,...
> 
> I will do if necessary someday a special Can component of my own.. to do what I want.
> 
> Thanks.

Hi, I would be grateful if you can share your wrapper for this logic. Thanks!.

**Comment by jkeruzec** [comment]
I have check and I did both world : it was a long time ago .. 

In ability:

```
  /**
     * Wrapper for simple ability can API
     * 
     */
    can(I, object) {
        if(Array.isArray(I) && I.length > 0) {
            return I.some(perm => {
             return this.ability.can(perm, object);
            });
        } 
        return this.ability.can(I, object);
    }
    
    /**
     * Wrapper for simple ability cannot API
     * 
     */
    cannot(I, object) {
        return !this.can(I, object);
    }

```

Use it : 
`abilityServices.can([SecurityConst.permissionType.edit], this.props.form.formObject)`

OR 

```
import { createCanBoundTo } from "@casl/react"
import abilityServices from "../../../services/security/AbilityServices"

export default createCanBoundTo(abilityServices.ability)
```

Then
`//Security
import Can from '../../../../components/ui/security/CanControl'`

and finally:
`<Can I={SecurityConst.permissionType.create} a={SecurityConst.permission.toolAdministration.module + "_" + SecurityConst.permission.toolAdministration.objects.user}>`

**Comment by lasithaguruge** [comment]
> I have check and I did both world : it was a long time ago ..
> 
> In ability:
> 
> ```
>   /**
>      * Wrapper for simple ability can API
>      * 
>      */
>     can(I, object) {
>         if(Array.isArray(I) && I.length > 0) {
>             return I.some(perm => {
>              return this.ability.can(perm, object);
>             });
>         } 
>         return this.ability.can(I, object);
>     }
>     
>     /**
>      * Wrapper for simple ability cannot API
>      * 
>      */
>     cannot(I, object) {
>         return !this.can(I, object);
>     }
> ```
> 
> Use it :
> `abilityServices.can([SecurityConst.permissionType.edit], this.props.form.formObject)`
> 
> OR
> 
> ```
> import { createCanBoundTo } from "@casl/react"
> import abilityServices from "../../../services/security/AbilityServices"
> 
> export default createCanBoundTo(abilityServices.ability)
> ```
> 
> Then
> `//Security import Can from '../../../../components/ui/security/CanControl'`
> 
> and finally:
> `<Can I={SecurityConst.permissionType.create} a={SecurityConst.permission.toolAdministration.module + "_" + SecurityConst.permission.toolAdministration.objects.user}>`

Thank you for your quick reply and sharing this. This is great! Cheers!
