### ISSUE TITLE
In casl-react i keep getting this issue.

### ISSUE THREAD

**Issue by The-Code-Monkey** [stalniy/casl#279]
So if i use this in my page it works but i want to make a wrapper component to add functionality but for some reason whenever i move it into my wrapper file it throws that ts error.

 JSX element type 'Can' does not have any construct or call signatures.

it works as expected in the page. Why would i get this.

**Comment by stalniy** [comment]
I have no idea :) 

1. Do you use `createContextualCan` or `createCanBoundTo` or do you use `Can` and pass `ability` prop? 
2. How do you make a wrapper?

Give some code please otherwise I can't help ;)
