### ISSUE TITLE
Jest, Enzyme testing example

### ISSUE THREAD

**Issue by The-Code-Monkey** [stalniy/casl#280]
I cant seem to find an implementation example this library with testing.

**Comment by stalniy** [comment]
I've never worked with enzyme, that's why there is no such example. But if you could provide such an example, it'd be great!

**P.S.:** there shouldn't be anything special with integration of CASL and enzyme. I guess it should work in the similar way as other libraries.

**Comment by The-Code-Monkey** [comment]
thats what i thought but i keep getting this error, 

```
Error: ReactShallowRenderer render(): Shallow rendering works only with custom components, but the provided element type was `object`.

**Comment by stalniy** [comment]
Could you please share some code or repro in codesandbox so I can suggest something. Without this, I can’t help you.

**Comment by The-Code-Monkey** [comment]
dont worry about it, it was a bug on my end not yours.

**Comment by stalniy** [comment]
Close as there is nothing to do from my side. Thanks for using CASL!
