### ISSUE TITLE
Complex permission check (array in a subfield)

### ISSUE THREAD

**Issue by carlespibernat** [stalniy/casl#281]
Hi!

I have a document which can be shared with other users. So the document is accessible for the owner and for all the users who have the document shared with them.  
 
The document object could be something like:
```javascript
{
  __typename: 'Document',
  name: 'My document',
  owner: {
    name: 'Name',
    id: 'me'
  },
  sharedUsers: [
    {
      name: 'User',
      id: 'other'
    }
  ]
}
```

Now I can use `can` to check if the owner can view a document:
```javascript
can(['view'], 'Document', { 'owner.id': user.id});
```

But is there any way to check if the logged user is one of the users who the owner has shared the document to? I don't find any way to achieve that, but I suppose I'm missing something...

**Comment by stalniy** [comment]
Hi,

Did you try this?

```js
can(['view'], 'Document', { 'owner.id': user.id});
can(['view'], 'Document', { 'sharedUsers.id': user.id });
```

**Comment by carlespibernat** [comment]
No I haven't! I'll check It out and I say something!

**Comment by carlespibernat** [comment]
Amazing! It does work!

But I have another problem now.. 😞 
Now only the users with sharing permission `edit` can edit a document. So to edit a document a user must be the owner or must have edit permissions in a share:

```javascript
{
  __typename: 'Document',
  name: 'My document',
  owner: {
    name: 'Name',
    id: 'me'
  },
  shares: [
    {
      permission: 'edit',
      user: {
        name: 'User',
        id: 'other'
      }
    }
  ]
}
```

Is there any option to perform like an and condition in an object array? I've tried different ways but I can't get it working...

**Comment by stalniy** [comment]
you need to use `$elemMatch`:

```js
can('edit', 'Document', { 'owner.id': user.id});
can('edit', 'Document', { 
  $elemMatch: { 
    permission: 'edit', 
    'sharedUsers.id': user.id 
  }
});
```

Take a look at http://docs.mongodb.org/manual/reference/operator/query/ . Currently I'm working on improving documentation, some of this common questions will be documented.

**Comment by stalniy** [comment]
I close this as I don't want it to become a question/answer issue. Please ask questions on [stackoverflow](https://stackoverflow.com/questions/tagged/casl) so others can find them as well.

Thanks for using CASL!
