### ISSUE TITLE
TypeScript error with @casl/vue: no exported member 'Can'

### ISSUE THREAD

**Issue by spinningarrow** [stalniy/casl#283]
I'm getting the following error when using `@casl/vue` with TypeScript:

```
 Module '"../<path/to/my/project>/node_modules/@casl/vue"' has no exported member 'Can'.
```

Looking at the typings for `@casl/vue` it does indeed appear that there is no exported declaration for the `Can` component.

**Comment by stalniy** [comment]
This is fixed in 4.x. I’ll release it this week. Finalizing documentation changes. 

Thanks for using CASL

**Comment by stalniy** [comment]
#268
