### ISSUE TITLE
typing for Abilities() is incorrect

### ISSUE THREAD

**Issue by givethemheller** [stalniy/casl#289]
`Ability(rules)` is throwing a type error. If overloaded to `as any`

Simple Reproduction
https://codesandbox.io/s/caslability-debug-74v99?file=/src/App.tsx

**Comment by stalniy** [comment]
Starting from 4.0 `AbilityBuilder` accepts `AbiltiyType` as a first argument. See API docs for details https://stalniy.github.io/casl/v4/en/api/casl-ability#constructor

It was done for better tree-shaking support as of 4.0 there are 2 types of `Ability` classes: `PureAbility` and `Ability`

**Comment by stalniy** [comment]
So, change the code to:

```ts
const { can, cannot, rules } = new AbilityBuilder<Ability>(Ability);
```

**Comment by Olena-Stotska** [comment]
By the way, the article has been published recently! https://medium.com/@sergiy.stotskiy/casl-4-0-what-is-inside-7c43c969b7b8
