### ISSUE TITLE
Is the `crud` alias gone in Ability 4?

### ISSUE THREAD

**Issue by jnardone** [stalniy/casl#290]
When `manage` changed a few releases ago, the changelog noted

```
To migrate the code, just replace `manage` with `crud` and everything will work as previously.
```

These had been in https://github.com/stalniy/casl/blob/%40casl/ability%403.4.0/packages/casl-ability/src/ability.js#L6

In 4.0, this seems to be gone.  Is that intentional?  I didn't see it in the changelog. Do we just need our own `crud` alias now?

**Comment by stalniy** [comment]
Hi,

Thanks for the issue!

Yes, it’s gone. Aliasing functionality was refactored to be tree-shakable. Sorry, it looks like I forgot to mention about CRUD alias in the changelog. I’ll add 

You can read about aliasing in https://stalniy.github.io/casl/v4/en/guide/define-aliases

**Comment by stalniy** [comment]
**alias**: no more default aliases are shipped with `@casl/ability`. So, if you used `crud`, you need to add it yourself.

  Before:

  ```js
  import { AbilityBuilder } from '@casl/ability';

  const ability = AbilityBuilder.define((can) => {
    can("crud", "Post");
  });

  ability.can("crud", "Post"); // true
  ```

  After:

  ```js
  import { defineAbility, createAliasResolver } from '@casl/ability';

  const resolveAction = createAliasResolver({
    crud: ['create', 'read', 'update', 'delete']
  });
  const ability = defineAbility({ resolveAction }, (can) => {
    can("crud", "Post"); 
  });

  ability.can("crud", "Post"); // true
  ```

**Comment by qqilihq** [comment]
@stalniy I've just stumbled over this as well, thanks. However, your example replaces `AbilityBuilder` with `defineAbility`, yet the documentation recommends to go with `AbilityBuilder`.

1. Is the recommendation to rather use `AbilityBuilder` still up-to-date?
2. How would I use the `resolveAction` with the `AbilityBuilder`

**Comment by stalniy** [comment]
AbilityBuilder is recommended because it doesn’t add additional nesting and the final code is easier to read. 

resolveAction is just an AbilityOption. If you use typescript or modern IDE it will help you with where to put it. 

```ts
import { AbilityBuilder } from ...

const { can, build } = new AbilityBuilder(Ability);

// define rules

const resolveAction = ....

build({ resolveAction })
```

**Comment by qqilihq** [comment]
Apologies, I totally missed this. Many thanks! 🙂
