### ISSUE TITLE
CASL Angular: MS Edge issue

### ISSUE THREAD

**Issue by wickedsp1d3r** [stalniy/casl#295]
Hello,
With latest `@casl/angular`, Microsoft Edge throws an error and the application is broken.

```
SCRIPT5022: SCRIPT5022: Expected identifier, string or number
```

**Comment by stalniy** [comment]
Hello,

Does it show some stacktrace? 

Frankly speaking the code became simpler in latest version. So, it’s hard to guess we’re the issue is

**Comment by stalniy** [comment]
According to [stackoverflow](https://stackoverflow.com/questions/53628191/edge-script1028-expected-identifier-string-or-number) edge doesn't support rest object destructuring. `@casl/angular` does not use it.

But it uses rest arguments, according to [MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Functions/rest_parameters). They are supported. So, doesn't seem to be a CASL's issue.

I'll try to test it somehow and will get  back to you

**Comment by stalniy** [comment]
Tested `@casl/angular` in codesanbox and Edge 81 through browserstack. Everything works good. Check [this app](https://firn9.csb.app/) in your Edge

**Comment by stalniy** [comment]
Close as not related to CASL
