### ISSUE TITLE
Question with JSON defined abilities

### ISSUE THREAD

**Issue by JSilversun** [stalniy/casl#300]
I'm trying the following dummy example: 
```js
const ability = new Ability([{ action: 'read', subject: 'article' }], {
        detectSubjectType:subject => subject.subject
    })
    console.log(ability.can('read', {subject: 'article'})); // Returns false
```
but it doesn't work, I have used this library before, not sure if this is a bug, I hope you can help me :)

**Comment by JSilversun** [comment]
I was able to get this working with the version 3.4.0, of course using the method `subjectName` instead of `detectSubjectType`, so not sure if this is a bug, for now, I will use the older version of the library.

**Comment by stalniy** [comment]
Starting from 4.0, CASL supports classes as subjects. Because of this `detectSubjectType` is called for each rule at `Ability` creation time in order to detect type of the subject. 

In your case, the function handles only passed subjects as objects (with `subject` field) but it should also work properly with strings. 

You have 2 options here:
* check if subject is a string and if so return it as it's 
  
  ```js
  const ability = new Ability([{ action: 'read', subject: 'article' }], {
     detectSubjectType: subject => typeof subject === 'string' ? subject : subject.subject
  })
  ```
* use default `detectSubjectType` as fallback
 
  ```js
  import { Ability, detectSubjectType } from '@casl/ability';
  const ability = new Ability([{ action: 'read', subject: 'article' }], {
     detectSubjectType: subject => subject && subject.subject ? subject.subject : detectSubjectType(subject)
  })
  ```

**Comment by stalniy** [comment]
Similar to #6

**Comment by stalniy** [comment]
I will double check the docs to ensure it’s there

**Comment by stalniy** [comment]
In section [Custom subject type detection](https://stalniy.github.io/casl/v4/en/guide/subject-type-detection#custom-subject-type-detection), the docs says:

Custom detection function must return `string` and handle the next cases:
* when `subject` is `undefined`
* when `subject` is a `string` or a `function` (this should be perceived as a subject type)
* when subject is an `object`

If you don't want to handle all that cases, you can fallback to built-in `detectSubjectType` function which will do this for you.

**Comment by stalniy** [comment]
Close as it works as expected
