### ISSUE TITLE
React, Redux TypeError: AbilityBuilder.extract is not a function

### ISSUE THREAD

**Issue by ilove3q** [stalniy/casl#302]
Hello, I try to begin with casl but, when I create a config, and test then, it show an error: `TypeError: _casl_ability__WEBPACK_IMPORTED_MODULE_0__.AbilityBuilder.extract is not a function`? I don't understand how come the error is? I imitated 2 blogs: 
- https://dev.to/dwalsh01/managing-user-roles-in-react-using-casl-11f6
- https://github.com/stalniy/casl-examples/blob/master/packages/react-todo/src/config/ability.ts

my error show:
![image](https://user-images.githubusercontent.com/36936865/80986207-8c33c980-8e30-11ea-8b95-44eae82f0718.png)

and my code:

with my type the auth:
```
auth: {
    validedSignin: false,
    "@id": "",
    username: "",
    roles: []
}
```

ability.js
```
import { Ability, AbilityBuilder } from "@casl/ability";
import { store } from "../reducers/index";
function subjectName(item) {
    if (!item || typeof item === "string") {
        return item;
    }
    return item.__type;
}

const ability = new Ability([], { subjectName });

let currentAuth;
store.subscribe(() => {
    const prevAuth = currentAuth;
    currentAuth = store.getState().auth.signinedReducer;
    if (prevAuth !== currentAuth) {
        ability.update(defineRulesFor(currentAuth));
    }
});

function defineRulesFor(auth) {
    const { can, rules } = AbilityBuilder.extract();
    if (auth.roles.includes("ROLE_ADMIN")) {
        can("remove", "Item");
    }
    return rules;
}

export default ability;
```
Can.js
```
import { createCanBoundTo } from "@casl/react";
import ability from "../../config/ability";

export default createCanBoundTo(ability);
```
How to fix that? 

And I want to a question:
I want to delete item when role is admin or the creator the item, but I don't understand how to check that? I don't know the parameter `{ assignee: 'me' }`, how to add data onto `can` to check that?

**Comment by stalniy** [comment]
`extract` is removed in 4.0. Please check the latest docs - https://stalniy.github.io/casl/v4/en/

**Comment by stalniy** [comment]
Your `Item` should have some field which indicates that particular user is a creator. Usually it’s `userId` or `createdBy`. In this case you need to use:

```js
If (auth.roles.includes(“admin”) {
  can(“remove”, “Item”)
} else {
  can(“remove”, “Item”, { userId: auth.userId })
}
```

**Comment by stalniy** [comment]
Close as there is nothing to do from my side. Thanks for using CASL!

I recommend you to start from the guide https://stalniy.github.io/casl/v4/en/guide/intro this should clarify all questions.
