### ISSUE TITLE
TypeError: "t.on is not a function" - using casl with vue

### ISSUE THREAD

**Issue by VBCF-JakobJung** [stalniy/casl#314]
Hi there, I am currently trying to get CASL to work with vue by using the @casl/vue npm repository. I've tried including CASL just like described in the npm docs, however, whenever using $can in any vue templates I immediately receive this type error.

I include CASL just like this (as instructed in the docs):

main.js
```
import { abilitiesPlugin } from '@casl/vue'
import ability from './utils/authorization'

Vue.use(abilitiesPlugin, ability);
```

Here is the ability which I've defined as documented in the @casl/ability npm repo.

utils/authorization.js
```
import { AbilityBuilder } from '@casl/ability'

export default function defineAbilitiesFor(user) {
  return AbilityBuilder.define(
    { subjectName: item => item.type },
    can => {
      can(['read', 'create'], 'Post');
      can(['update', 'delete'], 'Post', { user: user });
    }
  );
}
```

And when checking for any permissions in my templates with v-if="$can(['read'], 'Post')" I immediately get these errors:

```
[HMR] Waiting for update signal from WDS... log.js:24
[Vue warn]: Error in render: "TypeError: t.on is not a function"

found in

---> <Import> at src/pages/Import.vue
       <VContent>
         <Content>
           <VApp>
             <Application>
               <Dashboard>
                 <App> at src/App.vue
                   <Root> vue.esm.js:628
TypeError: "t.on is not a function"
    node_modules index.js:5
    node_modules index.js:5
    render Import.vue:16
    VueJS 49
        _render
        updateComponent
        get
        Watcher
        mountComponent
        $mount
        $mount
        init
        merged
        createComponent
        createElm
        createChildren
        createElm
        createChildren
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mountComponent
        $mount
        $mount
        init
        createComponent
        createElm
        patch
        _update
        updateComponent
        get
        Watcher
        mountComponent
        $mount
        $mount
        init
        createComponent
        createElm
        updateChildren
        patchVnode
        updateChildren
        patchVnode
        patch
        _update
        updateComponent
        get
        run
        flushSchedulerQueue
        nextTick
        flushCallbacks
vue.esm.js:1897
```

I am very sorry if this is an obvious mistake or if this is not caused by CASL itself.

**Comment by stalniy** [comment]
`AbilityBuilder.define` is removed in 4.0, which version of casl do you use?

**Comment by stalniy** [comment]
check this example for details - https://github.com/stalniy/casl-examples/tree/master/packages/vue-todo

**Comment by VBCF-JakobJung** [comment]
Thanks for the fast response. At the moment I am using @casl/vue version 1.1.0 and @casl/ability 4.0.8.

The example you link uses typescript, however, I solely use js in my application. I've now tried modelling my ability like the example in @casl/ability with the following code:

```js
import { AbilityBuilder, Ability } from '@casl/ability'

export default function defineAbilitiesFor() {
  const { can, rules } = new AbilityBuilder();

  can('read', 'Post');

  return new Ability(rules);
}
```

Unfortunately, I receive the exact same error as before, TypeError: "t.on is not a function". I've also tried downgrading @casl/vue because I saw that the latest version was only two days old, however, this didn't yield any positive results either.

**Comment by stalniy** [comment]
the issue is in this line:

```js
import ability from './utils/authorization' // <---

Vue.use(abilitiesPlugin, ability);
```

inside `utils/authorization` you export a function! but `abilitiesPlugin` expects to receive `Ability` instance! That's why it doesn't work.

**Comment by stalniy** [comment]
close as there is nothing to do from CASL side.

Thanks for using CASL!

**Comment by stalniy** [comment]
You can check a bit outdated CASL vue example - https://github.com/stalniy/casl-vue-example
