### ISSUE TITLE
Is there a way to return all fields in permittedFieldsOf helper?

### ISSUE THREAD

**Issue by cerino-ligutom** [stalniy/casl#318]
I have roles that can update certain fields only. However I have other roles (e.g. `superadmin`, `admin`) that only has `can('manage', 'all')` defined. Since there are no `fields` explicitly defined here, the `permittedFieldsOf` helper is not picking up anything. What's your advice for a situation like this?

**Comment by stalniy** [comment]
Return all fields using model details. This how I did this for mongoose: https://github.com/stalniy/casl/blob/master/packages/casl-mongoose/src/accessible_fields.ts#L41

Check also the API docs of that method: https://stalniy.github.io/casl/v4/en/api/casl-ability-extra

**Comment by cerino-ligutom** [comment]
Checked the mongoose code. Correct me if I'm wrong but you're suggesting that we do the checking on userland right? Basically, if `permittedFieldsOf` doesn't return anything, it could mean that no explicit field restrictions were enforced and we can assume all fields are good as permitted. Correct?

**Comment by stalniy** [comment]
Correct. Because on the the level of `permittedFieldsOf` we cannot get all fields. Somewhere in the docs it should be written that if  fields are omitted then user has access to all fields

**Comment by cerino-ligutom** [comment]
Great! That's fine, a simple check won't hurt but it could probably help other newcomers if you can add that as a tip/note. Great work btw, this library is doing wonders in standardizing the approach for authorization, keep it up and stay awesome!

---

To future readers, I use PostgreSQL w/ ObjectionJS. Here's what I did (in TypeScript):

I created a `screenPermittedFields` utility function (so that it can be used as a standalone if needed)
```ts
import { Ability, subject } from '@casl/ability';
import { permittedFieldsOf } from '@casl/ability/extra';
import { pick } from 'lodash';
// This is app specific
import { SystemAbilityAction, SystemAbilitySubject } from '@app/core/authorization';

interface IScreenPermittedFieldsArgs {
  ability: Ability;
  modelName?: Extract<SystemAbilitySubject, string>;
  action: SystemAbilityAction;
}

export const screenPermittedFields = <T extends object>(
  data: T,
  { ability, modelName, action }: IScreenPermittedFieldsArgs,
): Partial<T> => {
  if (Array.isArray(data)) {
    throw new Error(`"data" is an array. "data" must be of type object.`);
  }

  let fields: string[] = [];

  // Check if "data" is a plain object
  if (data?.constructor?.name === 'Object') {
    // Must then supply a "modelName" to aid with Subject identification
    if (!modelName) {
      throw new Error(`"data" is a plain object but no "modelName" was supplied.`);
    }

    fields = permittedFieldsOf(ability, action, subject(modelName, data));
  } else {
    // "data" must be a model instance. The helper can derive the "Subject".
    fields = permittedFieldsOf(ability, action, data);
  }

  if (fields.length === 0 || fields.includes('*')) {
    return data;
  }
  return pick(data, fields);
};
```

Then in my `Objection BaseModel` class, I make use of the `$set` method from the Objection class for self-assigning and let the utility function we created earlier to hitch a ride here:
```ts
// SystemAbilitySubject uses `InferSubjects` type from CASL so it's mixed 
// but we're interested with the string values as valid values for the 
// static readonly modelName property
type ModelName = Exclude<Extract<SystemAbilitySubject, string>, 'all'>;

interface ISetOptions {
  ability: Ability;
  action: SystemAbilityAction;
}

// Model from ObjectionJS
export class BaseModel extends Model {
  /**
   * For CASL Ability Subject
   */
  static readonly modelName: ModelName;

  private get _modelName(): ModelName {
    const model = this.constructor as typeof BaseModel;
    return model.modelName;
  }

  set(values: PartialModelObject<this>, options?: ISetOptions): this {
    if (!options) {
      return this.$set(values);
    }

    const { ability, action } = options;
    const screenedValues = screenPermittedFields(values, {
      ability,
      action,
      modelName: this._modelName,
    });

    return this.$set(screenedValues);
  }
}
```

Then as for usage, imagine we have a `Product` objection model and we'll be doing an update operation:
```ts
// Interface layer (think Controller for REST or Resolver for GraphQL)
const form = new Product();
form.set({
  // properties received from request
}, {
  ability: userAbility,
  action: 'update',
});

// Then pass the form to a service that does the operation
```

```ts
// Business Logic Layer
async function updateProduct(product: Product) {
  // Business logic stuffs

  const updatedProduct = await Product.query().update(product);

  // Other business logic after the update operation

  return updatedProduct;
}
```

Can refer to my [GraphQL-Starter repo](https://github.com/cerino-ligutom/GraphQL-Starter) for more context about the setup and [relevant](https://github.com/cerino-ligutom/GraphQL-Starter/blob/master/src/utils/screen-permitted-fields.util.ts#L13) [files](https://github.com/cerino-ligutom/GraphQL-Starter/blob/master/src/db/models/common/BaseModel.ts#L36) [used](https://github.com/cerino-ligutom/GraphQL-Starter/blob/master/src/core/authorization/system.ability.ts#L17).
