### ISSUE TITLE
Throw an exception when trying to check by field without fieldMatcher

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#330]
Relates to #328

**Comment by qqilihq** [comment]
Thanks for this! :-)

**Comment by stalniy** [comment]
After some thinking, I understood it’d better to check this at Ability creation stage. It’s better because it’ll be analyzed once per instantiation and it make more sense to fail fast + I can add here validation on empty fields array

**Comment by stalniy** [comment]
Validation on empty fields array will produce a warning because this is potentially a breaking change

**Comment by stalniy** [comment]
released in `@casl/ability@4.1.3`
