### ISSUE TITLE
json defined abilities, subject detection and conditions

### ISSUE THREAD

**Issue by meddMeddinski** [stalniy/casl#332]
Hello and thank you very much for maintaining casl, it's a great library!
I was able to implement the most basic usecases, however, I'm struggling with implementing the combination of the traits mentioned in the title.
What I have so far is this: (I'm using vue btw)
#### **`ability.js`**
```javascript
import { Ability } from '@casl/ability';
import subjectTypeFromGraphql from './subjectTypeFromGraphql';

export default new Ability([
    {
        detectSubjectType: subjectTypeFromGraphql
    }
])
```
#### **`subjectTypeFromGraphql.js`**
```javascript
import { detectSubjectType } from "@casl/ability";

export default subject => {
  if (subject && typeof subject === "object" && subject.__typename) {
    return subject.__typename;
  }

  return detectSubjectType(subject);
};
```
#### **`AbilityService.js`** (get's called on Login, would later be filled with backend data)
```javascript
import { Component, Vue } from "vue-property-decorator";
import subjectTypeFromGraphql from '@/services/subjectTypeFromGraphql';

import { AbilityBuilder } from "@casl/ability";
@Component
export default class AbilityService extends Vue {
  updateAbility() {
   
    this.$ability.update(
      [
        {
          action: "read",
          subject: "Example",
        },
       {
          action: "read",
          subject: "AnotherExample",
          conditions: {state: 'contemplating'}
        },
      ],
        {
          detectSubjectType: subjectTypeFromGraphql
        }
    );
  }
}

```

Wherever I call the no condition _can_ in a component with classname as a string it works as intended 
`$can('read', 'Example') \\true`

However, when trying to resolve from object it doesn't seem to work
`object_item={__typename: 'Example'}`
`$can('read', object_item) \\false`

Furthermore, when using conditions, it seems to be validated that any conditions are present, but the conditions themselves are not validated. But this I can only test in String based classname, so it probably has to do with subject detection.

Any help would be really appreciated

**Comment by stalniy** [comment]
Hello

The configuration in the 1st example is invalid. It should be `new Ability([], { detectSubjectType: ... })`

Pay attention at brackets.

**Comment by stalniy** [comment]
Close as there is nothing to do from CASL side. 

Thanks for using CASL!
