### ISSUE TITLE
Check permission in template with condition

### ISSUE THREAD

**Issue by sonphnt** [stalniy/casl#334]
Hi. I can not make conditions work in template.

`const rules2 = [
        {
          actions: ["read"],
          subject: ["all"]
        },
        {
          actions: ["manage"],
          subject: ["Post"],
          conditions: {
            author_id: 1
          }
        }
      ];`

`<h3 v-if="$can('manage', 'Post', { author_id: 2 })"  >`

In this case, this h3 should not be shown but it still shows because of conditions are not triggered

How can we make conditions work, I can not find any examples in documenations

Thanks

**Comment by stalniy** [comment]
Hi

You incorrectly use casl. Check [this line](https://github.com/stalniy/casl/blob/master/packages/casl-ability/src/PureAbility.ts#L205) of code. 

Unfortunately you don’t see the exception. I’ll fix this today

**Comment by stalniy** [comment]
Please read the docs 

1.https://stalniy.github.io/casl/v4/en/guide/intro
2. https://stalniy.github.io/casl/v4/en/guide/subject-type-detection
3. https://stalniy.github.io/casl/en/api/casl-ability#can-of-pure-ability
4. https://github.com/stalniy/casl-examples/tree/master/packages/vue-todo

**Comment by sonphnt** [comment]
I checked casl. But most of example written in code with ability.can. I would like to ask about writing the check in template html

**Comment by stalniy** [comment]
`$can` is just a reactive wrapper around ability.can :)

**Comment by stalniy** [comment]
So, accepts the same arguments

**Comment by stalniy** [comment]
Probably the best explanation can be found here - https://github.com/stalniy/casl/issues/59#issuecomment-387288324

**Comment by sonphnt** [comment]
Thanks. I love this implementation, so we can use with a dynamic model without creating a class.
 https://stalniy.github.io/casl/v4/en/guide/subject-type-detection
