### ISSUE TITLE
Angular 8 AOT

### ISSUE THREAD

**Issue by jbonet** [stalniy/casl#337]
Works as expected in dev builds. 

As soon as AOT is enabled, errors come up.

`Module not found: Error: Can't resolve '@casl/ability/dist/types/Ability'`

Is CASL not compatible with Angular 8?

**Comment by antony2809** [comment]
Having the same problem on my project. Any solution for this?

**Comment by Olena-Stotska** [comment]
yes, looks like it doesn't work with Angular 8. And as always Angular errors are very helpful...

**Comment by antony2809** [comment]
> yes, looks like it doesn't work with Angular 8. And as always Angular errors are very helpful...

Yeah ofc, forgot about it. Is just give the errors when `aot` is enabled on the build

`ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/ability/dist/types/Ability' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app'
ERROR in ./src/app/modules/home/home.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/ability/dist/types/Ability' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\home'
ERROR in ./src/app/modules/user/services/user.service.ts
Module not found: Error: Can't resolve '@casl/ability/dist/types/Ability' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\user\services'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/ability/dist/types/PureAbility' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app'
ERROR in ./src/app/modules/navigation-bar/components/navigation-navigate/navigation-navigate.component.ngfactory.js
Module not found: Error: Can't resolve '@casl/ability/dist/types/PureAbility' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\navigation-bar\components\navigation-navigate'
ERROR in ./src/app/modules/startups/modules/startup-discover/components/startup-filter-component/startup-filter.component.ngfactory.js
Module not found: Error: Can't resolve '@casl/ability/dist/types/PureAbility' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\startups\modules\startup-discover\components\startup-filter-component'
ERROR in ./src/app/app.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app'
ERROR in ./src/app/modules/collections/collections.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\collections'
ERROR in ./src/app/modules/dealflow/dealflow.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\dealflow'
ERROR in ./src/app/modules/events/events.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\events'
ERROR in ./src/app/modules/home/home.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\home'
ERROR in ./src/app/modules/investment-tracker/investment-tracker.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\investment-tracker'
ERROR in ./src/app/modules/smart-sheets/modules/smart-sheets-detail/smart-sheets-detail.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\smart-sheets\modules\smart-sheets-detail'
ERROR in ./src/app/modules/smart-sheets/modules/smart-sheets-directory/smart-sheets-directory.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\smart-sheets\modules\smart-sheets-directory'
ERROR in ./src/app/modules/startups/modules/startup-discover/startup-discover.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\startups\modules\startup-discover'
ERROR in ./src/app/modules/today/today.module.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/AbilityModule' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\today'
ERROR in ./src/app/modules/navigation-bar/components/navigation-navigate/navigation-navigate.component.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/pipes' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\navigation-bar\components\navigation-navigate'
ERROR in ./src/app/modules/startups/modules/startup-discover/components/startup-filter-component/startup-filter.component.ngfactory.js
Module not found: Error: Can't resolve '@casl/angular/dist/types/pipes' in 'C:\Users\Anthony\Desktop\Development\playbook\Playbook-Frontend\frontend\src\app\modules\startups\modules\startup-discover\components\startup-filter-component'`

**Comment by Olena-Stotska** [comment]
use `@casl/angular-v2.1.1` as a workaround, it should work. The latest one for sure works with v9. Maybe the issue due to using angular cli 9 to compile package

**Comment by antony2809** [comment]
> sue due to using angular cli 9 to compile package

Yes, actually I have a different project with Angular 9 and is working perfectly. Just broke in Angular 8. Thanks for the anwer

**Comment by antony2809** [comment]
@Olena-Stotska is `@casl/ability-v4.1.3` compatible with `@casl/angular-v2.1.1`

**Comment by Olena-Stotska** [comment]
This is what we need to investigate :)

**Comment by antony2809** [comment]
Yeah, it works now. Thank you

**Comment by Olena-Stotska** [comment]
fixed in `@casl/ability@4.1.5` and `@casl/angular@4.1.3`. Guys, please test!

**Comment by Olena-Stotska** [comment]
[angular example app](https://github.com/stalniy/casl-examples/tree/master/packages/angular-todo) works fine, so close this. 

Thanks for the issue!
