### ISSUE TITLE
Further info required on using 2 x instances

### ISSUE THREAD

**Issue by wrabit** [stalniy/casl#338]
Hello, after some scouring I feel this plugin is almost what I need vs all the rest, but I am still missing some info in order to proceed.

![image](https://user-images.githubusercontent.com/5918271/84144546-b5abca80-aa58-11ea-88c0-e14d2064717e.png)

My project has one entry, main.js but 2 areas ("dashboard" and "manager"), each with separate sets of permissions, so I don't want the various methods affecting permissions in both sides.

Where to go from here? What does `./services/ability` look like? It's not a plugin file? I cannot see any sample of it in the docs or Medium walkthrough. 

![image](https://user-images.githubusercontent.com/5918271/84145224-c7da3880-aa59-11ea-97ee-73344446636c.png)

If this is where I will find out, this is a dead link.

**Comment by wrabit** [comment]
In addition, is there a recommended way we can access $can for example from router?

```
import Vue from 'vue'

Vue.$can(..) ?
```

**Comment by stalniy** [comment]
Hello,

Check this example - https://github.com/stalniy/casl-examples/tree/master/packages/vue-todo

If the same user has access to both areas then I’d recommend to use single ability instance for the app. Anyway you have different entities in both areas (I guess). 

Thanks for the note about dead link. I’ll check and fix today a bit later.

**Comment by stalniy** [comment]
> In addition, is there a recommended way we can access $can for example from router?
> 
> ```
> import Vue from 'vue'
> 
> Vue.$can(..) ?
> ```

Use ability instance directly. You don’t need  reactivity in the router. Check this comment as well https://medium.com/@sergiy.stotskiy/so-there-are-several-approaches-3ee962fb9fb5

**Comment by wrabit** [comment]
> If the same user has access to both areas then I’d recommend to use single ability instance for the app.

Yeah the same user cannot access either side.

**Comment by Olena-Stotska** [comment]
@wrabit read the docs on CASL's website. For vue - https://stalniy.github.io/casl/v4/en/package/casl-vue , all links there works as expected

**Comment by Olena-Stotska** [comment]
the links are fixed.

Thanks for the issue. Close as there is nothing to from CASL side

**Comment by wrabit** [comment]
Thanks @Olena-Stotska, I never knew those docs existed!
