### ISSUE TITLE
Example to use casl In Angular Component Testing

### ISSUE THREAD

**Issue by antony2809** [stalniy/casl#340]
I have been trying to test casl in Angular but at the moment not having success. After import the AbilityModule to my spec file I get the the error in the image below. Any hints on how to test casl in Angular?

![image](https://user-images.githubusercontent.com/6976497/84652456-efbf1580-af0b-11ea-980a-66f9b3db6e3c.png)

**Comment by stalniy** [comment]
You need to pass provider for Ability the same way you do in `AppModule`

**Comment by stalniy** [comment]
Also take a look at casl/angular tests - https://github.com/stalniy/casl/blob/master/packages/casl-angular/spec/spec_helper.js#L48

**Comment by stalniy** [comment]
Close as there is nothing to do from casl side.

**Comment by rodcisal** [comment]
any idea how to set the value on a component so the **able pipe** picks up the right permissions?

I can't get to mock the pipe so my template renders elements based on permissions, help, please! :)
