### ISSUE TITLE
Populated fields

### ISSUE THREAD

**Issue by tonxxd** [stalniy/casl#341]
Thank you very much for this awesome library!
I am trying to filter out private fields using the accessibleFields plugin. It works fine for the main object but is not filtering out fields on populated attributes.

Eg. BlogPost has an attribute "tags" that gets populated by mongoose but the attribute x of tag which is private is shown anyway in the response.

To solve this I tried to use permittedFieldsOf iteratively on the tags attribute passing ability, read and subject('Tag', tag) as parameters. Unfortunately, I cannot get this working ad I get an empty array of fields as the function output.

Any suggestion? 
Thanks!

**Comment by stalniy** [comment]
Hi

Please l, share how you setup conditions and how you filter fields.

**Comment by tonxxd** [comment]
```
export default function defineAbilityFor(user) {
  return defineAbility((can,cannot) => {
    
    // public
    can('read', 'all', {
        status:1
    });

    cannot('read', 'Tag', ['title'])
    cannot('read', 'Post', ['author'])


    // admin
    if(user.role == 'admin'){
        can('manage', 'all')
    }

  });
}
```


```
const Tag = Schema({
     label: String,
     title: String
})

const PostSchema = Schema({
     title: String,
     author: String,
     tags: [{type: Schema.Types.ObjectId, ref:'Tag'}] 
     desc: String
})
```

I query posts like `Post.find().accessibleBy(ability).populates('tags')`
and then return `posts.map(p => p.accessibleFieldsBy(ability))` which strips post hidden fields (author) properly but does not apply filtering to the tags array (title is still there).

What I did is iterating over the tags array (which are not any more mongoose documents but just objects so I cannot call accessibleFieldsBy) using `permittedFieldsBy(ability, 'read', subject('Tag', tag)`

From permittedFieldsBy I get an empty array which I think is correct because the function doesn't know all available Tag fields (if in the abilities I set `can('read', 'Tag', ['label'])` I get `['label']` from permittedFieldsBy. At this point I don't know out to filter out hidden attributes, maybe if there is a way to retrieve hidden fields (instead of permitted) I can take the difference for each object.

Hope I explained myself, let me know if not, thanks

**Comment by tonxxd** [comment]
EDIT: I managed to achieve the result i wanted by custom detecting the model and creating a new mongoose model instance for each tag

Eg. post.tags = post.tags.map(p => pick(p, (new Tag(p)).accessibleFieldsBy(ability)))
Don't know how much it will impact performances but it should be fine, if you have any better suggestion let me know

Ps. my actual implementation of the sanitize function is this (it has a selection param from the request UR, auto-detects model from attributes, and explore the objects tree to find children models to sanitize)

```
import {
    transformCoord
} from "."
import pick from "lodash.pick"
import MockupModel from "../models/Mockup"
import WidgetModel from "../models/Widget";
import ImageModel from "../models/Image";
import UserModel from "../models/User";


const toSubject = obj => {

    if (!obj.__v)
        return false

    if (obj.layers) {
        return new MockupModel(obj)
    } else if (obj.mockups) {
        return new WidgetModel(obj)
    } else if (obj.src) {
        return new ImageModel(obj)
    } else if (obj.userID) {
        return new UserModel(obj)
    }

    return false
}

export const sanitizeResponse = (data, ability, select = []) => {

    if (!data) return data

    if (Array.isArray(data)) {
        return data.map(e => sanitizeResponse(e, ability, select))
    } else if (typeof data == 'object') {

        const isModel = toSubject(data)
        if (isModel) {
            data = select.length ? pick(pick(data, isModel.accessibleFieldsBy(ability)), select) : pick(data, isModel.accessibleFieldsBy(ability, 'read')
            )
        }

        Object.keys(data).forEach(i => {
            data[i] = sanitizeResponse(data[i], ability, select)
        })
    }
    return data;
}

```

and then `res.send(sanitizeResponse(entries.map(e => e.toJSON()), ability, Object.keys(parsedQuery.select || {})))`

**Comment by tonxxd** [comment]
EDIT: I managed to achieve the result i wanted by custom detecting the model and creating a new mongoose model instance for each tag

Eg. post.tags = post.tags.map(p => pick(p, (new Tag(p)).accessibleFieldsBy(ability)))
Don't know how much it will impact performances but it should be fine, if you have any better suggestion let me know

Ps. my actual implementation of the sanitize function is this (it has a selection param from the request URL, auto-detects model from attributes, and explores the objects tree to find children models to sanitize)

```javascript
import pick from "lodash.pick"
import MockupModel from "../models/Mockup"
import WidgetModel from "../models/Widget";
import ImageModel from "../models/Image";
import UserModel from "../models/User";


const toSubject = obj => {

    if (!obj.id)
        return false

    if (obj.layers) {
        return new MockupModel(obj)
    } else if (obj.mockups) {
        return new WidgetModel(obj)
    } else if (obj.src) {
        return new ImageModel(obj)
    } else if (obj.userID) {
        return new UserModel(obj)
    }

    return false
}

export const sanitizeResponse = (data, ability, select = []) => {

    if (!data) return data

    if (Array.isArray(data)) {
        return data.map(e => sanitizeResponse(e, ability, select))
    } else if (typeof data == 'object') {

        const isModel = toSubject(data)
        if (isModel) {
            data = select.length ? pick(pick(data, isModel.accessibleFieldsBy(ability)), select) : pick(data, isModel.accessibleFieldsBy(ability, 'read')
            )
        }

        Object.keys(data).forEach(i => {
            data[i] = sanitizeResponse(data[i], ability, select)
        })
    }
    return data;
}

```

and then 
```javascript
res.send(sanitizeResponse(entries.map(e => e.toJSON()), ability, Object.keys(parsedQuery.select || {})))
```

**Comment by stalniy** [comment]
This doesn’t work as you expect. If you don’t want tags.title to be part of the response, you need to define it that way:

`cannot('read', 'Post', ['author', 'tags.title'])`

**Comment by stalniy** [comment]
Close as there is no actions from casl side
