### ISSUE TITLE
Request for TypeORM

### ISSUE THREAD

**Issue by Herr-Mefisto** [stalniy/casl#347]
I really like your casl library and want to use it in my project. I'm using TypeORM with Postgres.
I'm not sure how use it for filtering data from database (rows and columns) based on casl rules. Are you going to implement such plugin?

**Comment by stalniy** [comment]
I plan to do this for [mikro-orm](https://mikro-orm.io/), [sequelize](https://sequelize.org/) and probably [knex](http://knexjs.org/) in the context of #8. I heard a lot of not very good feedback about TypeORM, especially from creator of mikro-orm.

So, at least not in the nearest future. As soon as I finish work on my new library [ucast](https://github.com/stalniy/ucast), you will be able to implement casl rule translation to TypeORM by yourself.

**Comment by stalniy** [comment]
Hi @Herr-Mefisto,

If you are interested in getting integrated casl with type-orm, please help to implement type-orm interpreter in [ucast](https://github.com/stalniy/ucast) repository. 

This is a new library created by me which will replace currently default conditions matcher (siftjs). The important thing is that this library uses AST to translate mongodb into boolean value. We can do the same for type-orm. 

Let me know if you are ready to help, this should not take too much time for type-orm expert. And if you have any questions, please fill free to ask!

**Comment by chorsnell** [comment]
@stalniy another request for TypeORM (with postgres)

Looking at github stats its definitely a fairly major player in terms of NodeJS based ORM's - https://www.npmtrends.com/typeorm-vs-sequelize-vs-knex-vs-mikro-orm

What was the mikro-orm creator feedback out of interest?

**Comment by stalniy** [comment]
@chorsnell you can help me to do this as part of ucast ecosystem. I’ll help you with the direction. Also you can look at @ucast/objection as a reference implementation. 

If you are interested in, please create an issue in ucast repository

**Comment by stalniy** [comment]
https://github.com/stalniy/ucast

**Comment by stalniy** [comment]
I’m currently slowly working On v5 which will use ucast under the cure instead of siftjs

**Comment by stalniy** [comment]
About TypeORM and mikro orm comparison please read https://medium.com/dailyjs/introducing-mikro-orm-typescript-data-mapper-orm-with-identity-map-9ba58d049e02 and https://mikro-orm.io/blog

**Comment by stalniy** [comment]
Alternatively you support this work financially on opencollective, so I’ll change the priorities and implement it myself

**Comment by lloydclosson** [comment]
I would also vote for a TypeORM. How much money would it require you to build and it and what would the timeframe be?

**Comment by stalniy** [comment]
I can finish this in 2 weeks or faster (2h per day), including documentation and all underlying work. So, 2h * 10d * $40 = $800

@lloydclosson if you want to support this feature financially, I’d like to know your requirements on it (or I can provide my own and you say whether they are fine for you)

**Comment by lloydclosson** [comment]
@stalniy Do you already have the requirements defined? If so can I see them? With this information, I can determine how to proceed.

**Comment by stalniy** [comment]
## Requirements

* translate MongoDB query into TypeORM query builder (casl v5 uses @ucast/* ecosystem which parses mongodb query into AST)
* when you encounter nested path `user.profile`, check whether there is a relation on this entity with name `profile` and if so, automatically join it
* expose an API (very likely a function, don't know whether there is a better solution), to extend existing QueryBuilder API with permissions query from `Ability` instance. Something like this:

  ```js
  const query = toTypeORMQuery(ability, 'read', conn.createQueryBuilder(Person, 'p'))
  ```

**Comment by stalniy** [comment]
I've already implemented alpha version of `@ucast/sql` which can translate AST into raw SQL and TypeORM QueryBuilder instance.

The last piece is to integrate this with casl and create `@casl/sql` package

**Comment by Herr-Mefisto** [comment]
@stalniy How far did you get with this? I really like your library and want to fully use it in my project!

**Comment by stalniy** [comment]
Very busy with family stuff. Plan to release v5 when finish migration of all examples. To ensure all works smoothly. 

And only then will get back to sql support

**Comment by ignaciogrondona** [comment]
Hi @stalniy , any update on this? Would be great to use this with Postgres + TypeORM. Thanks!

**Comment by stalniy** [comment]
No progress on this

**Comment by dzcpy** [comment]
From my experince, Mikro ORM have some strange issues and then I switched back to TypeORM (sometimes also buggy). But I would say as of now Mikro ORM is not as mature as TypeORM. Maybe it's just me, but considering the popularity and 3rd party integration of the two, I still hope that casl could at least support TypeORM

**Comment by stalniy** [comment]
Feel free to propose requirements in #8 for TypeORM which eventually are the same for any orm

**Comment by stalniy** [comment]
I posted [a comment](https://github.com/stalniy/casl/issues/8#issuecomment-681191411) a while back but only objectionjs users reported back useful feedback

**Comment by dzcpy** [comment]
Any updates?

**Comment by matiasf9** [comment]
Why is this closed? Any updates?

**Comment by tomisicm** [comment]
why the f did I only found this thread now. 

What alternatives are you guys using? 
This package is awesome, too bad it does not work with postress and typeorm.

**Comment by stalniy** [comment]
Do not have enough free time to work on smth big. Sorry guys

**Comment by ryaneghrari** [comment]
No worries, thanks so much for the quick reply. Would you recommend against using casl ability without a db integration? Using PureAbility?

**Comment by stalniy** [comment]
You can use alpha version of @ucast/sql. I did some progress in this direction but it may be a bit buggy

**Comment by TekuConcept** [comment]
Bit late to the discussion, but for anyone else who crosses this issue, I quickly threw together a small class that converts CASL-mongo rules to TypeORM queries: [casl-bridge](https://www.npmjs.com/package/casl-bridge) (with full-coverage unit tests)

```ts
const source = getTypeOrmSource()
const ability = getCaslAbility()

const bridge = new CaslBridge(source, ability)
const entries = await bridge.createQueryTo('read', 'Book').getMany()
```
