### ISSUE TITLE
Using custom aliases in PureAbility constructor

### ISSUE THREAD

**Issue by astralmedia** [stalniy/casl#356]
**Describe the bug**
I have spent a few days trying to crack this before I reached out...but when using a `createAliasResolver` with the `resolveAction` parameter on the `PureAbility` constructor is not working.

**To Reproduce**
1. Create an alias with the createAliasResolver()
2. Pass the alias into the resolveAction param on a PureAbility constructor

```
// Create Aliases
const resolveActions = createAliasResolver({
    patch: ['update'],
    read: ['get', 'find'],
    delete: ['remove']
})


// Construct Ability
let caslAbility = new PureAbility(Builder.rules, {
    detectSubjectType: subject => (subject && subject.subject ? subject.subject : detectSubjectType(subject)),
    conditionsMatcher: conditions => {
        return createQueryTester(conditions, { operations: { $in, $eq } })
    },
    resolveAction: normalize => {
        return resolveActions
    }
})
```

**Expected behavior**
I expect the aliases to work.

**CASL Version:**

`@casl/ability` - v **^4.1.5**

**Environment**:
Node v8.17.0

**Comment by stalniy** [comment]
Check the docs please.

Replace 

```js
resolveAction: normalize => {
        return resolveActions
    }

```

With

```js
resolveAction: resolveActions
```

And it will work
