### ISSUE TITLE
Combining two rules seems to exclude the other and vice versa

### ISSUE THREAD

**Issue by bitflower** [stalniy/casl#362]
Hi,

thanks for this great lib. I've just started using it and like it's abstraction layer so far.

I've come over a situation where I can't seem to make all permissions to be fullfilled though.

My use case:
- I want to disallow some records based their on `_id` not being present in an array
- I want to disallow some record's fields based on the record's `name`property 

I've created 2 rules to define this scenario but it seems that one over rules the other.

The records: 
```
  const dummyWartung = {
    _id: 'abc',
    name: 'Wartung 1'
  };
  const disallowedDummyWartung = {
    _id: 'xxxx',
    name: 'Wartung 2'
  };
  const disallowedDummyWartungWithFIeld = {
    _id: 'yyyy',
    name: 'Wartung mit Sound',
    notificationSoundId: 'theSoundfgdfgfd'
  };
```

The rules (loaded via `JSON`):
```
const rules = [ 
{ 
    action: [ 'edit', 'create' ],
    subject: 'wartungen',
    conditions: { name: { '$eq': 'Wartung mit Sound' } }, // Disallow property "notificationSoundId" for records matching the "name"
    fields: [ 'notificationSoundId' ],
    reason: '',
    inverted: true 
},
{ 
    action: [ 'edit', 'create' ],
    subject: 'wartungen',
    conditions: { _id: { '$nin': [ 'xxxx', 'anotherid' ] } }, // Disallow these ids
    reason: '',
    inverted: false 
}
]
```

Both my test cases and my actual code tell me that the `disallowedDummyWartungWithFIeld` record is allowed to be access though.

I have the feeling that I have  wrong expectation of how rules have to be defiend to fulfill my "excluding thinking". I understand it that way that we can define several rules that will be "run though" when checking a record and if all return `true` the record is allowed. Is that correct?

If not how could I achieve limiting certain records to a property A and some other to a property B but only one having an additional `fields` restricition by doing this in one rule?

Thanks upfront for some input!

**Comment by bitflower** [comment]
Some more background: These rules are part of my ABAC system where roles can be freely configured and multiple roles be assigned to a user. So it's crucial to my concept. It would be good to know if CASL is able to fulfill this requirement. I really was impressed when I found the lib by the sheer possibilities and believe that's the mistake is on my end.

**Comment by stalniy** [comment]
Hello,

Please, create an issue that follows proposed template. According to your assumptions this is a bug. So, please create a bug or ask a question on stackoverflow.

**Why is it important?**

Your steps to reproduce are not enough for me to understand where the issue is, because:
* I don't have example, and need to spend time creating one
* I don't have details on how you check/test abilities (there common misunderstanding in how checking logic works, make sure you read through [CASL guide](https://casl.js.org/v4/en/guide/intro), especially [this part about inverted conditions](https://casl.js.org/v4/en/guide/intro)).

So, I can't help you as I don't have enough details.

**Comment by stalniy** [comment]
close as issue doesn't follow template recommendations

**Comment by bitflower** [comment]
HI, I swear the template didn't show up when clicking `New issue`...

Anyway, of course I wanna cooperate and open a new one following the rules to reduce your workload!

**Comment by stalniy** [comment]
![Screenshot from 2020-07-27 11-12-06](https://user-images.githubusercontent.com/1159966/88519022-1cca1200-cffa-11ea-9ae6-a286f00c7be4.png)

This is what you should see when clicking "New issue" button

**Comment by stalniy** [comment]
You probably clicked on "Open a blank issue." link

**Comment by bitflower** [comment]
Hey, I'm quite sure I didn't. Don't wanna stress the beaucracy any longer. YOu are right, and that's how it should be done ;-)

To come to the good news: Your answer helped me to find the solution: ordering the rules was what was wrong. At some stage I think I had this right by accident and all worked. Then in a new environment all rules where setup from scratch and it failed. Your comment helped find it. Thanks so much!

**Comment by bitflower** [comment]
For reference or maybe usage in docs or FAQ here is the repo:
https://github.com/bitflower/casl-rule-intersection-issue

**Comment by stalniy** [comment]
Cool! I'm glad that you solved the issue :+1:
