### ISSUE TITLE
TypeError: Cannot read property 'throwUnlessCan' of undefined

### ISSUE THREAD

**Issue by madhu0309** [stalniy/casl#363]
- req.ability.throwUnlessCan("create", user);
- ForbiddenError.from(ability).throwUnlessCan("create", user);

I am trying to apply **create** condition on a Model using **casl-mongoose** package. I tried both the methods but I am still getting the error. I want to know how to make it work.

**Comment by stalniy** [comment]
Hello,

Please, create an issue that follows proposed template. According to your assumptions this is a bug. So, please create a bug or ask a question on stackoverflow.

**Why is it important?**

Your steps to reproduce are not enough for me to understand where the issue is, so I can't help

**Comment by stalniy** [comment]
close as issue doesn't follow template recommendations
