### ISSUE TITLE
Help with 'Can' (ability.can working fine)

### ISSUE THREAD

**Issue by Zeds112** [stalniy/casl#365]
**Describe the bug**
`Can` not showing when rules are met

**To Reproduce**
So I have this code where `ability.can` is working fine but using a `Can` component is not.

```
        < RoleContext.Consumer>
          {
            (user) => {

              const ability = defineAbilityFor(user.state)
              const Can = createCanBoundTo(ability);

              return <React.Fragment>

                {/*Working*/}
                {ability.can('view', 'admin') && <p>Can view admin</p>}

                {/*Not working*/}
                <Can do="view" on="admin">
                  <p>Can view admin</p>
                </Can>

              </React.Fragment>
            }
          }
        </ RoleContext.Consumer>
```

Not quite sure what I'm missing as I've been under the impression that using 'Can' is just a neater way of using `ability.can`.

**Expected behavior**
'Can' to work

**CASL Version**

`@casl/ability` - ^4.1.5
`@casl/react` - ^2.1.1

**Environment**:
Node v12.18.3

**Comment by stalniy** [comment]
First of all, your steps to reproduce doesn’t show how you setup rules. 

And, is there any reason to use `createCanBoundTo` instead `createContextualCan`?

Did you use debugging recommendations from https://casl.js.org/v4/en/advanced/debugging-testing ?

**Comment by stalniy** [comment]
Sorry closed, accidentally

**Comment by Zeds112** [comment]
Ok thanks I'll try that. Probably something small so I'll re-open if needed.

**Comment by stalniy** [comment]
I've just tested in [todo example](https://github.com/stalniy/casl-examples/tree/master/packages/react-todo), `createCanBoundTo` works properly
