### ISSUE TITLE
Nuxt js : _casl_ability__WEBPACK_IMPORTED_MODULE_1__.AbilityBuilder.define is not a function

### ISSUE THREAD

**Issue by KamranMaqbool** [stalniy/casl#373]
i'am using  pakage in nuxt js application with below configurations 

**/static/roles_permissions.js**
`export function c(can) {
  can('book', 'read');
  can('book', 'update');
  can('book', 'add');
}`

**/plugins/ability.js**
`import { c } from '@/static/js/roles_permissions';
import { AbilityBuilder } from '@casl/ability';

export const ability = AbilityBuilder.define(can => c(can));

export default function({ store }, inject) {
  ability.update(store.state.permissions);
  inject('ability', ability);
  if (process.client) {
    if (store.state.permissions && store.state.permissions.length) {
      localStorage.setItem('permissions', store.state.permissions.length);
    } else {
      localStorage.removeItem('permissions');
    }
  }
  return store.subscribe((mutation, state) => {
    switch (mutation.type) {
      case 'setUser':
        ability.update(state.permissions);
        inject('ability', ability);
        break;
    }
  });
}`

**/plugins/casl.js**
`import Vue from 'vue';
import { abilitiesPlugin } from '@casl/vue';
import { ability } from '@/plugins/ability.js';

Vue.use(abilitiesPlugin, ability);`

issue PIc
![image](https://user-images.githubusercontent.com/53546053/90310279-8a86a100-df09-11ea-8e37-11cca9f1ebdc.png)

**CASL Version**
"@casl/ability": "^4.1.5",
"@casl/vue": "^1.1.1",

using this package
`@casl/vue` - v

**Environment**:
Nuxt JS

**Comment by stalniy** [comment]
Please read the docs! https://casl.js.org/v4/en/guide/define-rules And changelog

**Comment by stalniy** [comment]
Close as the issue doesn’t follow suggested template for a bug
