### ISSUE TITLE
Add typescript typings for packages

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#38]
- [x] `@casl/angular`
- [x] `@casl/react`
- [x] `@casl/aurelia`
- [x] `@casl/vue`

**Comment by stalniy** [comment]
typings for Vue available in `@casl/vue@0.2.0`

**Comment by fskorzec** [comment]
Hi, a proposal for react typescript definition : https://github.com/stalniy/casl/pull/54

**Comment by stalniy** [comment]
published `@casl/react@0.3.0` with fixed typings for react 15.x and 16.x

**Comment by stalniy** [comment]
published `@casl/aurelia@0.2.0` and `@casl/angular@0.2.0`
