### ISSUE TITLE
Column must be greater than or equal to 0, got -21 in Angular v10.0.5

### ISSUE THREAD

**Issue by egenita** [stalniy/casl#382]
**Describe the bug**
ng serve at dev machine returns -> "Column must be greater than or equal to 0, got -21" error

**To Reproduce**
Use the following Angular project versions:
 "@angular/core": "10.0.5",
 "@casl/ability": "4.1.5",
 "@casl/angular": "4.1.4",

**Expected behavior**
An error occurred when trying to run the application via "ng serve". See screenshot below:
![image](https://user-images.githubusercontent.com/2075962/91655317-45a26300-eae2-11ea-90be-7c2b9b3675b0.png)

"dependencies": {
    "@angular/animations": "10.0.5",
    "@angular/cdk": "10.1.0",
    "@angular/common": "10.0.5",
    "@angular/compiler": "10.0.5",
    "@angular/core": "10.0.5",
    "@angular/flex-layout": "10.0.0-beta.32",
    "@angular/forms": "10.0.5",
    "@angular/material": "10.1.0",
    "@angular/material-moment-adapter": "10.1.0",
    "@angular/platform-browser": "10.0.5",
    "@angular/platform-browser-dynamic": "10.0.5",
    "@angular/router": "10.0.5",
    "@casl/ability": "4.1.5",
    "@casl/angular": "4.1.4",
    "@ngx-translate/core": "13.0.0",
    "@swimlane/ngx-datatable": "17.1.0",
    "@types/prismjs": "1.16.1",
    "aws-sdk": "2.718.0",
    "bn-ng-idle": "1.0.1",
    "lodash": "4.17.19",
    "moment": "2.27.0",
    "ng2-charts": "2.3.2",
    "ngx-cookie-service": "3.1.2",
    "ngx-tinymce": "10.0.1",
    "perfect-scrollbar": "1.5.0",
    "prismjs": "1.20.0",
    "rxjs": "6.6.0",
    "tslib": "^2.0.0",
    "web-animations-js": "2.3.2",
    "zone.js": "0.10.3"
  }

**Comment by stalniy** [comment]
Thanks for the issue. Haven’t tested with the latest angular. Will check it tomorrow, looks like an issue with sourcemaps

**Comment by stalniy** [comment]
Unfortunately, I can't reproduce this issue by fixed sourcemaps to point to TypeScript sources instead of intermediate transformation. hopefully this fixes the issue.

Let me know if not and I'll reopen the issue.
