### ISSUE TITLE
Handling ForbiddenError in Node

### ISSUE THREAD

**Issue by leongwq** [stalniy/casl#384]
I've followed the example in the repo and added the error-handler.js file in my node server. It is the last line after importing all the routes.

However when this line is executed, `ForbiddenError.from(req.ability).throwUnlessCan('read', 'AWSAccounts');`.

The error is not caught by the error handler and it throws `(node:12352) UnhandledPromiseRejectionWarning: ForbiddenError: Cannot execute "read" on "AWSAccounts"`

The function where ForbiddenError is called
```
const getAWSAccounts = async (req, res) => {
  ForbiddenError.from(req.ability).throwUnlessCan('read', 'AWSAccounts');
  try {
    return res.json(await awsAccountsDB.getAWSAccounts(req.user.id));
  } catch (error) {
    res.status(400).send(error);
  }
};
```
App.js
 ```
const router = express.Router();
  COMPONENTS.forEach((moduleName) => {
    const appModule = require(`./components/${moduleName}`); // eslint-disable-line

    if (typeof appModule.configure === "function") {
      appModule.configure(app, router);
    }
  });

  app.use("/api", router);
  app.use(errorHandler);
```

**Comment by stalniy** [comment]
Hello, 

Please, move your question to stackoverflow (https://stackoverflow.com/questions/tagged/casl), this is not an issue with casl, so should not be in this repository.

I'm going to close this because the issue doesn't follow suggested templates
