### ISSUE TITLE
Doesn't work with Angular 7.x

### ISSUE THREAD

**Issue by bacmanni** [stalniy/casl#410]
I am trying to get casl(angular) to work on my project and found some problems considering documentation. I am using 7.x version of angular and after installing casl and casl/angular I just got compile errors. After some tinkering I found out that newest version of casl/angular requires newer version of angular. This is ok, but I think required versions should be explained clearly on documentation.

Also it would be nice if older versions on documentation would be available more easily. I mean something like how ngx-bootstrap does it: https://valor-software.com/ngx-bootstrap/#/documentation

**Comment by stalniy** [comment]
Thanks for the issue.

It doesn't make sense for me to duplicate information from package.json `peerDependency` in documentation. However, what makes sense is to re-check that it works with angular 7 :)

You know, I hate Angular :) Sometimes, I spent just enormous amount of time to migrate this tiny library to the next angular version just because their errors sucks... unfortunately.

**Comment by stalniy** [comment]
But you didn't provide any errors and versions. Please change the issue to follow one of the suggested templates. If not, I'll close it, as I don't want to dig into errors of old angular.

Today Angular@11 is the latest version, so you are 4 versions behind now.

**Comment by bacmanni** [comment]
Maybe you can check versions from package.json, but what about the documentation? I mean when documentation updates to new version then there are no way to access the old documentation?

Updating to newer angular is not possible because there are too many dependencies and there is no way that our customer is willing to pay for the upgrade. I mean the project is big. Also, you don't need to fix the new version to work on older ones, because I'm not sure that is even possible. I mean newer angular version require typescript update and that can break a lot of things. I can live with the older version of casl and casl/angular, but using it without specific versions documentation is a bit pain :)

**Comment by stalniy** [comment]
with CASL v4, I completely rewrote docs. So, with v5 there will be a link to v4. Previously it was completely managed by Github Pages. It's possible to restore it BUT there was no documentation about complementary packages :)

**Comment by bacmanni** [comment]
Ok. Then I just have to try to figure out something else then. Maybe read it from sources or something :|
