### ISSUE TITLE
Support NPM 7

### ISSUE THREAD

**Issue by aggarwaldev** [stalniy/casl#417]
**Is your feature request related to a problem? Please describe.**
A warning is emitted while installing `@casl/ability` on npm 7.

**Describe the solution you'd like**
Support npm 7.

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

![image](https://user-images.githubusercontent.com/22045791/102611352-bf736080-4154-11eb-921a-d4d1ede8608f.png)

**Comment by stalniy** [comment]
thanks. 

I’ll remove engines. It was previously ignored by npm

**Comment by stalniy** [comment]
v5 has been released! I removed `engines` field
