### ISSUE TITLE
Casl/mongoose and official mongoose types

### ISSUE THREAD

**Issue by p-fruck** [stalniy/casl#436]
Hey @stalniy, thank you for your awesome work on this project. I just got started using the casl library for permission management and I really love it so far, but there's one small issue I wasn't able to fix: 

**Describe the bug**
I am using the `@casl/ability` and the `@casl/mongoose` package to manage database permissions within nodejs. My code runs just fine but as soon as I want to compile my typescript project using tsc, it just errors out.

**To Reproduce**
I've created `src/test.ts` within my current project with the following content:

```ts
import { accessibleRecordsPlugin } from '@casl/mongoose';
import * as mongoose from 'mongoose';

mongoose.plugin(accessibleRecordsPlugin);
```

**Expected behavior**
Running `npx tsc src/test.ts` should just compile the ts file. Instead, I get the following error message:

```log
npx tsc src/test.ts 
node_modules/@casl/mongoose/dist/types/accessible_records.d.ts:3:18 - error TS2305: Module '"mongoose"' has no exported member 'DocumentQuery'.

3 import { Schema, DocumentQuery, Model, Document } from 'mongoose';
                   ~~~~~~~~~~~~~

node_modules/@casl/mongoose/dist/types/accessible_records.d.ts:6:76 - error TS2314: Generic type 'Model<T>' requires 1 type argument(s).

6 export interface AccessibleRecordModel<T extends Document, K = {}> extends Model<T, K & {
                                                                             ~~~~~~~~~~~~~~
7     accessibleBy: GetAccessibleRecords<T>;
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
8 }> {
```

**CASL Version**

`@casl/ability` - v 5.1.2
`@casl/mongoose` - v 3.2.2

**Environment**:

Fedora 33, Node 14.15.1
`mongoose` - v 5.11.11
`typescript` -v 4.1.3

**Comment by stalniy** [comment]
Do you `esMofuleInterop` enabled? As in this tsconfig - https://github.com/stalniy/casl/blob/master/tsconfig.json#L10

**Comment by p-fruck** [comment]
Thank you for the quick answer! Yes, I do have `esMofuleInterop` enabled. I did even replace my tsconfig.json with your example, but I still get the same error.

**Comment by p-fruck** [comment]
It seems like the issue is connected to `mongoose` v 5.11.11. When downgrading to v 5.10.3 tsc works just fine, but on v 5.11.11 I get the above error. So I will stay on 5.10.3 for the time being. Will there be support for the latest mongoose version soon? :smile:

**Comment by stalniy** [comment]
Strange. Maybe in the latest version of `@types/mongoose` they removed some exports. I recently made a release of casl mongoose and tsc didn’t complain. 

Let me check it with the latest version

**Comment by stalniy** [comment]
They added official ts support in 5.11 and in 5.10 you need to use `@types/mongoose`

thats why they are incompatible

**Comment by p-fruck** [comment]
Ok thank you, but the official types included in `mongoose` v 5.11.11 seem to differ from the types provided by `@types/mongoose` v 5.10.3, because even without having `@types/mongoose` installed (those two libraries conflict for obvious reasons) tsc still wont compile. So the question whether mongoose 5.11 will be supported soon still remains

**Comment by stalniy** [comment]
This is a breaking change for casl/mongoose, so very likely I'll ship it with #404 together . Also, currently I'm on holidays, so it won't be fast. I think I'll have time to fix this in the next couple weeks.

**Comment by stalniy** [comment]
@p-fruck did you check if `npm i mongoose @types/mongoose` still works for `mongoose@5.11`?

**Comment by p-fruck** [comment]
it didn't work for me since the types provided by `@types/mongoose` (v 5.10.3) were conflicting with those provided by `mongoose` v 5.11

**Comment by stalniy** [comment]
I do not recommend to use official types as there are a bunch of TypeScript related issues introduced in mongoose@5.11.x: 
- https://github.com/Automattic/mongoose/issues/9850
- https://github.com/Automattic/mongoose/issues/9856
- and maybe others

That makes it impossible to have the same level of TS support in the package. 

So, **suggested workaround** is to use `@types/mongoose` and remove official types through `postinstall` npm hook:

```json
{
  "scripts": {
    "postinstall": "rm -f node_modules/mongoose/index.d.ts"
  }
}
```

There is nothing better I can do with this until official mongoose types are improved

**Comment by stalniy** [comment]
looks like that ts issues where fixed by mongoose and I can try to implement it one more time with official types

**Comment by mdwekat** [comment]
I work around this by setting `skipLibCheck` to `true`

``` json
"compilerOptions": {
    "skipLibCheck": true
  }
}
```

**Comment by stalniy** [comment]
fixed in @casl/mongoose@5.0.0

**Comment by leonardoviada** [comment]
Hi everyone, I'm getting this error and reading the comments above didn't help. What am I doing wrong?
I have `@casl/mongoose@5.0.0` and I'm using NestJs

```
src/restaurant/restaurant.service.ts:25:40 - error TS2339: Property 'accessibleBy' does not exist on type 'Query<(Restaurant & Document<any, any, Restaurant>)[], Restaurant & Document<an
y, any, Restaurant>, {}, Restaurant>'.

25     return this.restaurantModel.find().accessibleBy().exec();
                                          ~~~~~~~~~~~~

[5:04:27 PM] Found 1 error. Watching for file changes.
```

**Comment by soltysaleksandr** [comment]
> Hi everyone, I'm getting this error and reading the comments above didn't help. What am I doing wrong?
> I have `@casl/mongoose@5.0.0` and I'm using NestJs
> 
> ```
> src/restaurant/restaurant.service.ts:25:40 - error TS2339: Property 'accessibleBy' does not exist on type 'Query<(Restaurant & Document<any, any, Restaurant>)[], Restaurant & Document<an
> y, any, Restaurant>, {}, Restaurant>'.
> 
> 25     return this.restaurantModel.find().accessibleBy().exec();
>                                           ~~~~~~~~~~~~
> 
> [5:04:27 PM] Found 1 error. Watching for file changes.
> ```

Same problem

**Comment by stalniy** [comment]
Looks like types on Query doesn't work properly

**Comment by anuraagy** [comment]
Any update on this?

**Comment by stalniy** [comment]
Nothing new, I have one project were I have older mongoose version. As soon as I finish some refactoring and will be able to update to newer version I’ll check it.

Very low on free time right now. Also, I fed up with mongoose types so very likely will create an alternative fully typesafe mongo db DAL lib based on json schema in the next year.

**Comment by anuraagy** [comment]
I totally understand, do you have advice on how we can hide these type errors created by accessibleBy?

**Comment by anuraagy** [comment]
We were able to get types working with the following setup! Posting here for others who are running into this issue.

```javascript
import { AnyMongoAbility, Generics, Normalize } from "@casl/ability";
import { DocumentQuery, Model, Types, Document } from "mongoose";

type Schema = { _id: Types.ObjectId };


type ExtractQueryHelpersFromDocument<D> = D extends Document<any, infer QueryHelpers, any>
  ? QueryHelpers
  : never;

export type AccessibleBy<T extends Schema, D extends Document> = <U extends AnyMongoAbility>(
  ability: U,
  action?: Normalize<Generics<U>["abilities"]>[0]
) => DocumentQuery<T & D, D, ExtractQueryHelpersFromDocument<D>>;

export interface AccessibleRecordModel<
  T extends Schema,
  D extends Document,
  QueryHelpers = {},
  Methods = {}
> extends Model<
    T,
    QueryHelpers & {
      accessibleBy: AccessibleBy<T, D>;
    },
    Methods
  > {
  accessibleBy: AccessibleBy<T, D>;
}`
```

**Comment by kamalkech** [comment]
still the same issue with "mongoose": "~6.6.0" and "@types/mongoose": "^5.11.97" mean should downground the version in 2022 ???

**Comment by stalniy** [comment]
You don’t need types/mongoose anymore. Mongoose provides built-in types

**Comment by stalniy** [comment]
[tests for casl/mongoose](https://github.com/stalniy/casl/blob/master/packages/casl-mongoose/spec/accessible_records.spec.ts) are written in ts and they work. If smth doesnt work for you, please make a minimal repo where I can take a look.
