### ISSUE TITLE
Don't use class names for the identifier of subject

### ISSUE THREAD

**Issue by znewsham** [stalniy/casl#445]
**Is your feature request related to a problem? Please describe.**
When using CASL on the client side with classes, the class names get minified, often to single character names `class n = {}`. If the classes are declared in different contexts, their can be collisions, while they are separate classes, they have the same name. This can be resolved by defining a `__caslSubjectType__` on each class, but I feel this shouldn't be necessary. 

**Describe the solution you'd like**
I believe the only reason a name is required rather than a reference to the class is because the rules for the subject/action are cached based on the name. If instead of an object a map was used, the class can be used instead.

**Comment by stalniy** [comment]
You can use classes to define/check permissions or use static `modelName` property on classes

**Comment by stalniy** [comment]
You can achieve this in v5 by providing a custom `detectSubjectType`: 

```js
detectSubjecType: type => type.constructor
```

v5 uses ES Map to index rules. Check the docs on custom subject type:

https://casl.js.org/v5/en/guide/subject-type-detection

**Comment by stalniy** [comment]
I’ll add a section about classes a bit later

**Comment by znewsham** [comment]
Wow, thanks for the crazy fast reply - I have read that subject - I mention this because I just found this bug in minified code. I'm aware that there are workarounds to the issue - but still, there seems to be no reason to default to the name of the class rather than a reference to the class - it's cleaner to write `class Thing {}` than `class Thing { static modelName = "Thing" }`,

**Comment by stalniy** [comment]
The issue is that majority of frontend state management libs don’t use classes and don’t even recommend to use them. 

I expect backend developers to be more familiar  with design patterns, domain/anemic model, etc.  That’s why the defaults are more frontend friendly

**Comment by stalniy** [comment]
By the way, if you use terser to Munich JavaScript (webpack use it), then you can configure it to not minify class names or keep class names that match specified pattern
