### ISSUE TITLE
Unexpected ability checking behavior

### ISSUE THREAD

**Issue by Blaze34** [stalniy/casl#448]
**Describe the bug**
Result of ability checking not obviously depends on ability definition

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
```
class Lot {
  constructor(
    public id: number,
    public isPublished: boolean,
    public userId: number,
  ) {}
}

class User {
  constructor(public id: number) {}
}

enum Action {
  Manage = 'manage',
  Create = 'create',
  Read = 'read',
  Update = 'update',
  Delete = 'delete',
}

type Subjects = typeof Lot | Lot | 'Lot';

export type LotAbility = Ability<[Action, Subjects]>;

export class LotAbilityFactory {
  createForUser(user: User) {
    const { can, build, rules } = new AbilityBuilder<LotAbility>(
      Ability as AbilityClass<LotAbility>,
    );

    can(Action.Read, 'Lot');
    can(Action.Update, Lot);

    console.log('rules', rules);

    return build();
  }
}
```
2. How do you check abilities
```
const user = new User(1);
const lot = new Lot(2, false, user.id);
const lotAbility = new LotAbilityFactory().createForUser(user);

lotAbility.can(Action.Update, lot); // false
```

**Expected behavior**
Obviously that `lot` is a instance of `Lot` and it's should be matched with `can(Action.Update, Lot)` and return `true`

**Interactive example** (optional, but highly desirable)
[My example](https://repl.it/@Blaze34/CaslBug#index.ts) and [Rewritten example](https://repl.it/@Blaze34/CaslBug-e2#index.ts)

**CASL Version**

"@casl/ability": "5.2.1",

**Environment**:

node -v 
`v15.5.1`
ts-node -v 
`v9.1.1`
"typescript": "4.0.5"

**Comment by stalniy** [comment]
Hello,

It works as expected. The issue is that example in nestjs docs is written for casl v4 and the latest version is v5. In v5, you need to provide a custom `detectSubjectType` option if you want to use classes as subject types.

Alternatively, you may use strings and replace `can(Action.Update, Lot);` with `can(Action.Update, 'Lot');` (pay attention that the 2nd argument is a string!)

**Comment by Blaze34** [comment]
> Alternatively, you may use strings and replace can(Action.Update, Lot); with can(Action.Update, 'Lot'); (pay attention that the 2nd argument is a string!)
I found out it while was testing, but it's unobviously. Anyway documentation is confusing and should be fixed asap.

P.S. May you give an example of using `detectSubjectType`?

**Comment by stalniy** [comment]
Related to #430

**Comment by stalniy** [comment]
nestjs is not under my responsibility :) but I'll send a PR.

[Casl docs](https://casl.js.org/v5/en/guide/subject-type-detection#use-classes-as-subject-types) correctly explains the topic. Additionally, I added example with TypeScript

**Comment by stalniy** [comment]
PR to nestjs - https://github.com/nestjs/docs.nestjs.com/pull/1687
