### ISSUE TITLE
AbilityBuilder in ts - expected 1 arguments but got 0

### ISSUE THREAD

**Issue by jeremygottfried** [stalniy/casl#453]
**Describe the bug**
When using typescript and following the docs, I get two errors: 

1. On `new AbilityBuilder()`, the error is `expected 1 arguments but got 0`.
2. On `new Ability(rules)`, the error is
[
![Screen Shot 2021-01-28 at 4 58 13 PM](https://user-images.githubusercontent.com/34523280/106203880-0f006f80-618a-11eb-8670-b81d27f80ff3.png)
](url)
**To Reproduce**
```ts
import { AbilityBuilder, Ability } from '@casl/ability';

export default function defineAbilitiesFor() {
  const { can, rules } = new AbilityBuilder();

  return new Ability(rules);
};
```

**Expected behavior**
For the simplest example from the docs to work

**CASL Version**

`@casl/ability` - v 5.2.2

**Environment**:

Node 12.16.3
Typescript 4.1.3
ts-node 9.1.1
MacOS Catalina 10.15.1

**Comment by jeremygottfried** [comment]
This seems to be a documentation issue. 
https://github.com/stalniy/casl#1-define-abilities

The example there doesn't have `Ability` as an argument to `AbilityBuilder`

I will submit a PR to correct it

**Comment by stalniy** [comment]
Thank you!
