### ISSUE TITLE
Prop "I" should be available in lower case

### ISSUE THREAD

**Issue by F0rsaken** [stalniy/casl#458]
**Is your feature request related to a problem? Please describe.**
I tried to use component `<Can>` with prop `I`, but my eslint disallow HTML attributes with uppercase, which is also specified in Vue guide, cause HTML is not case sensitive and when `I` is used as `i` it still works, but I got warning:

`[Vue tip]: Prop "i" is passed to component <Anonymous>, but the declared prop name is "I". Note that HTML attributes are case-insensitive and camelCased props need to use their kebab-case equivalents when using in-DOM templates. You should probably use "i" instead of "I".`

![image](https://user-images.githubusercontent.com/21238469/107244884-d0db3980-6a2e-11eb-9d9f-0adfc6491ed4.png)

**Describe the solution you'd like**
I would like to use lowercase `i` and not getting this warning. So I propose to add prop `i: [String]` alongside normal `I: [String]`.

**Describe alternatives you've considered** (optional)
None.

**Additional context** (optional)
None.

**Comment by stalniy** [comment]
use `do` and `on`. I think that this readability is a bit overcomplicated and people don't follow it anyway

**Comment by stalniy** [comment]
close as `can` component is not a recommended way to check permissions with casl. Prefer to use `$can` or `provide/inject` functionality in Vue 3
