### ISSUE TITLE
Destructuring context triggers TypeError: Cannot read property 'relevantRuleFor' of undefined

### ISSUE THREAD

**Issue by jzecca** [stalniy/casl#462]
Using destructuring on CASL React context fails with the following error:
```
TypeError: Cannot read property 'relevantRuleFor' of undefined
```

**To Reproduce**
```js
// Working
const ability = useContext(AbilityContext);
console.log(ability.can('read', 'something'));

// Failing
const { can } = useContext(AbilityContext);
console.log(can('read', 'something'));
```

**Expected behavior**
I expected this to work, obviously.
For the sake of readability, I'd _really_ prefer to call `can()` rather than `ability.can()` in my components.

**Interactive example**
[Here's a reproducer](https://codesandbox.io/s/cool-hoover-l8y1u?file=/src/components/Test.tsx:105-243) : just change `export default Test1` to `export default Test2` on L23.

--- 

This took me forever to figure out, as I didn't (and still don't) see any reason for this to fail.
Am I missing something here?

Thanks in advance!

EDIT: I think this might be the reason for issue #407

**Comment by stalniy** [comment]
This is solvable in userland just bind `can` and whatever properties you want to provided `Ability` instance. This is what I did in one of the [casl-example](https://github.com/stalniy/casl-examples/blob/master/packages/react-blog/src/services/ability.ts#L10)s

**Comment by stalniy** [comment]
I close this as I don't plan to change the behavior at least for now. But feel free to express your thoughts here

**Comment by jzecca** [comment]
Binding `can` & `cannot` did the trick. Thanks a lot!
