### ISSUE TITLE
Unexpected results for `detectSubjectType` and `conditionsMatcher` with `PureAbility`

### ISSUE THREAD

**Issue by jfahrenkrug** [stalniy/casl#465]
**Describe the bug**
Using a very simply condition to match a class property doesn't seem to work

**To Reproduce**
Run this code:

```
import { mongoQueryMatcher, PureAbility, SubjectType } from "@casl/ability";

class Thing {
  static readonly modelName = "Thing";

  public id: string;
}

const ability = new PureAbility(
  [
    {
      action: "read",
      subject: "Thing",
      conditions: [{ id: "abc" }]
    }
  ],
  {
    conditionsMatcher: mongoQueryMatcher,
    detectSubjectType: (subject) => {
      console.log("getting subject for", subject);
      return "Thing" as SubjectType;
    }
  }
);

const thingInstance = new Thing();
thingInstance.id = "abc";

const output = [
  "<br/><b>Thing:</b>",
  `can read Thing (class): ${ability.can("read", Thing)}`,
  `can read Thing (instance): ${ability.can("read", thingInstance)}`,
  `can read Thing (string): ${ability.can("read", "Thing")}`
];

document.body.innerHTML = output.join("<br/>");
```

The output is:

```
Thing:
can read Thing (class): false
can read Thing (instance): false
can read Thing (string): true
```

This is very surprising. I'm providing `detectSubjectType` and it's hardcoded to return `"Thing"` no matter what you pass in. I'm also providing the conditionsMatcher (the default mongo one), and my condition is very simple: The `id` should match `"abc"`. Why do the first two checks return `false`?

**Expected behavior**
I would expect the output to be

```
Thing:
can read Thing (class): true
can read Thing (instance): true
can read Thing (string): true
```

**Interactive example** (optional, but highly desirable)
https://codesandbox.io/s/casl-example-conditions-and-detectsubjecttype-xp102?file=/src/index.ts

**CASL Version**

`@casl/ability` - v5.2.2

**Environment**:
Node v14.15.4
TS 3.9.5

**Comment by stalniy** [comment]
Well, conditions should be an object and not an array

**Comment by stalniy** [comment]
Changing this gives the next results:

Thing:
can read Thing (class): false
can read Thing (instance): true
can read Thing (string): true

Matching on class doesn’t work due to reasons I said in your previous issue. 

detectSubjectType is responsible for mapping instance to its type. In other words it allows to associate an object with `subject` property in rules. 
 
 in v5 `detectSubjectType` is responsible for mapping objects to their corresponding types. When you pass  a class, function or string, they are automatically perceived as subject types and `detectSubjectType` is not called for them

**Comment by jfahrenkrug** [comment]
@stalniy Thank you for the clarification :) My fault for passing in an array of conditions. It's quite challenging to get all of this right. Maybe it would be helpful to point out in the docs that `detectSubjectType` is only called in certain situations. Thanks again for your help!

**Comment by stalniy** [comment]
Indeed, this is missed. I’ll extend docs for detectSubjectType with explanation I gave in this issue. 

Thanks :)

**Comment by stalniy** [comment]
By the way, there is an `Ability` class that has everything preconfigured for main cases

**Comment by deving1995** [comment]
> By the way, there is an `Ability` class that has everything preconfigured for main cases

This helped me with an issue where `PureAbility` was forcing me to add a conditionsMatcher, and would not work when I tried to ask about a rule that had a condition. I would get an error that said "ERROR [ExceptionsHandler] e is not a function":

![image](https://github.com/stalniy/casl/assets/87441052/f4218f8b-7ff6-459d-9ded-6f5d0386e2bd)

Using the following code:
```
const ability = new PureAbility(userFromDB.rules as any, {
  fieldMatcher: fieldPatternMatcher,
  conditionsMatcher: (matchConditions: MatchConditions) => matchConditions
});

....

ability.can(Action.Update, subject('Team', currentTeam)) <-- error here
```
---

So if I just replace `PureAbility` with `Ability`
```
const ability = new Ability(userFromDB.rules as any);
```
The problem goes away but `Ability` is deprecated. Please help.
