### ISSUE TITLE
Using an ability on the frontend that was generated on the backend

### ISSUE THREAD

**Issue by astralmedia** [stalniy/casl#469]
Hey, first off thanks for the great toolset :) We've been using it on the backend for months. I just tried to pass an ability from the backend to the frontend, and when I give it to the Can component, it throws this error:

```
TypeError: t.on is not a function
```

I read the other post about this error, but I am sure I am sending an instance of an ability to it. Here is an example of the object that its passing:

```
O: {}
g: {posts: {…}, users: {…}}
j: (2) [{…}, {…}]
p: {}
s: true
v: {}
```

Is there any way to use this ability from the backend? We built a rather complex ability building setup, and would rather not send all that data to the frontend to build a new ability there..

```
let caslAbility = new Ability(Builder.rules, {
			detectSubjectType: subject => (subject && subject.subject ? subject.subject : detectSubjectType(subject)),
			conditionsMatcher: conditions => {
				return createQueryTester(conditions, { operations: { $in, $eq } })
			},
			fieldMatcher: defaultFieldMatcher["O"].fieldMatcher, // Make sure this always works and "O" index does not change
			resolveAction: resolveActions
		})
```

Thanks for any insight

**Comment by stalniy** [comment]
How do you send this instance? Can you check whether that object has `.on` method?

**Comment by astralmedia** [comment]
So, I found a way to construct the ability on the frontend...basically had to:

```
const ability = new Ability()
ability.update(abilityData.ability)
```

when I got the abilityData from the server...

Now I have this in my ability:

```
get:
10:
action: (2) ["get", "find"]
conditions: {inId: "5fe0f6702033242be27187ef"}
inverted: false
subject: "transactions"
```

But when I try to hit `<Can do="get" this={transaction}>` on a transaction with `__caslSubjectType__: "transactions"` set on it, it doesnt render the children of the Can.

I feel so close to unlocking this here :X

Thanks for getting back to me

**Comment by astralmedia** [comment]
fyi, the `transaction` object also has an inId set that is equal to that required one

**Comment by stalniy** [comment]
@astralmedia the bug tracker is for issues only. As I understood this is a question. For questions, please use stackoverflow.
