### ISSUE TITLE
Store Ability in Express Session?

### ISSUE THREAD

**Issue by amrap030** [stalniy/casl#471]
Hello,

I have seen the express example, where an ability is stored via middleware in the req object. It then uses the following method to evaluate the permissions:

```javascript
ForbiddenError.from(req.ability).throwUnlessCan('read', article);
```

I want to achieve a similar thing. My idea is to save the ability inside an express session that is shared with socket io websockets. Through the sharing `req.session` = `socket.handshake.session`. My approach is the following, I make a request from the frontent application to get rules to update the ability on the frontend. The backend saves the ability inside the express session:

```javascript
// abilities.js file
import { Ability } from '@casl/ability';

export const defineAbilitiesFor = (rules) => {
  return new Ability(rules);
};

export default defineAbilitiesFor;
```

```javascript
// handler for express route to get permissions from the frontend
export const getPermissions = async (req, res) => {
...
  rules.push({
    action: ['view'],
    subject: views,
  });
  // manage all own processes
  rules.push({
    action: ['manage'],
    subject: 'Process',
    conditions: {
      userId: req.kauth.grant.access_token.content.sub,
    },
  });
// store ability in session
  req.session.rules = defineAbilitiesFor(rules);
  const token = jwt.sign({ token: packRules(rules) }, 'secret');
  if (token) {
    return res.status(200).json(token);
  } else {
    return res.status(400).json('Error');
  }
...
```

Then when a websocket request happens, I want to check in the backend if the user has the permissions to do that action:

```javascript
ForbiddenError.from(socket.handshake.session.rules).throwUnlessCan('view', 'Process');
```

However, this throws the following error:

```
TypeError: this.ability.relevantRuleFor is not a function
    at ForbiddenError.throwUnlessCan
```

The session object seems to have the correct ability object. When I console.log `socket.handshake.session.rules`, I get the following output:

```javascript
{
  h: false,
  l: {},
  p: {},
  '$': [
    { action: [Array], subject: 'Process', conditions: [Object] },
    { action: [Array], subject: [Array] },
    { action: [Array], subject: 'Process', conditions: [Object] }
  ],
  m: {}
}
```

Also the can function and everything else I tried wasn't working. I think storing the plain rules as an object inside the session and then updating the ability class before each request would work, but I don't want to do that. I want to store the ability right inside the session, so that I only have to execute the throwUnlessCan or can functions.

Is this even possible and if so, how would you do this?

Thanks so far.

**Comment by stalniy** [comment]
Hello, 

The bug tracker is for issues only. Please ask questions on [stackoverflow](https://stackoverflow.com/questions/tagged/casl).
