### ISSUE TITLE
Support for React 17.0.1

### ISSUE THREAD

**Issue by vizardkill** [stalniy/casl#475]
![image](https://user-images.githubusercontent.com/37307788/110161249-16cfb700-7dbb-11eb-936a-730418484084.png)

**Comment by stalniy** [comment]
@casl/react supports react v17:

https://github.com/stalniy/casl/blob/master/packages/casl-react/package.json#L70

tests pass. Please provide more details

**Comment by stalniy** [comment]
Close as this issue doesn’t follow suggested template for a bug
