### ISSUE TITLE
Mongoose Peer dependancy warning!

### ISSUE THREAD

**Issue by mdwekat** [stalniy/casl#481]
**Description**
The package shows peer dependency warning when using `mongoose@^5.12.2`

```bash
npm WARN Could not resolve dependency:
npm WARN peer mongoose@"^4.0.0 || <= 5.10.0" from @casl/mongoose@4.0.1
npm WARN node_modules/@casl/mongoose
npm WARN   @casl/mongoose@"^4.0.1" from the root project
```

**Suggested Solution**
To pump the peer dependency to include `mongoose@^5.12.2`

**Comment by stalniy** [comment]
Thanks for the issue. Mongoose version is restricted by reason. Please check #436 for details

**Comment by mdwekat** [comment]
I work around this by setting `skipLibCheck` to `true` in `tsconfig.json`

``` json
"compilerOptions": {
    "skipLibCheck": true
  }
}
```
