### ISSUE TITLE
Cannot detect the subject correctly with/without conditions 

### ISSUE THREAD

**Issue by jamesweb1** [stalniy/casl#489]
**Describe the bug**
Cannot detect the subject correctly with/without conditions, and I list the example as following:

**To Reproduce**
```typescript
export class Group {
  name: string;
}
```

Without conditions:
```typescript
const abilityUsingString = defineAbility((can) => {
      can(Action.Read, 'Group');
    });
const abilityUsingClass = defineAbility((can) => {
      can(Action.Read, Group);
});

console.log(abilityUsingString.can(Action.Read, Group)); // actual: false (expected: true)
console.log(abilityUsingClass.can(Action.Read, Group)); // actual: true
```

With conditions:
```typescript
const abilityUsingString = defineAbility((can) => {
      can(Action.Read, 'Group', { name: 'special' });
    });

const abilityUsingClass = defineAbility((can) => {
      can(Action.Read, Group, { name: 'special' });
});
const group = new Group();
group.name = 'special';
console.log(abilityUsingString.can(Action.Read, group)); // actual: true
console.log(abilityUsingClass.can(Action.Read, group)); // actual: false (expected: true)
```

**Expected behavior**
I list the expected behavior above. I don't know which pattern I should use (class name or string as subjects?). Anyone can point out it is a bug or something else? If I use Group as a subject, it is not correct when using  with conditions. If I use 'Group' as a subject, it is not correct when using without conditions.

**CASL Version**

`@casl/ability` - v5.2.2

**Environment**:

TypeScript v4.0.5

**Comment by stalniy** [comment]
This a breaking change in v5, to see full list please check CHANGELOG - https://github.com/stalniy/casl/blob/master/packages/casl-ability/CHANGELOG.md#breaking-changes

> Also it's important to note that it's no longer possible to use classes and strings as subject types interchangeably as it was before. Now, if you want to use classes, you should use them everywhere and define custom detectSubjecType

It's up to you whether you want to use classes or strings. Starting from v5 for classes you need to provide additional configuration. 

Also check this docs - https://casl.js.org/v5/en/guide/subject-type-detection#use-classes-as-subject-types
