### ISSUE TITLE
Clarification on how Ability API

### ISSUE THREAD

**Issue by sikula** [stalniy/casl#492]
Looking at the documentation [https://casl.js.org/v4/en/guide/define-rules#define-ability-example](url) it seems like you can pass in an array of actions and subjects.

But looking at the Ability API [https://casl.js.org/v4/en/api/casl-ability](url) it's not used at all.  The reason I bring this up is because I have an Ability config that looks like this:

```
import { AbilityBuilder, Ability } from '@casl/ability'

type Actions =
  'manage'
  | 'create'
  | 'read'
  | 'update'
  | 'delete'

type Subjects =
  'Article'
  | 'User'
  | 'ManageStuff'
  | 'Comment';

type AppAbility = Ability<[Actions, Subjects]>

const { can, rules } = new AbilityBuilder<AppAbility>()

const ability = new Ability(rules)


type Permissions = {
  action: string | string[],
  subject: string,
}

export function updateAbility(permissions: Permissions[]) {
  ability.update(permissions)
}


export default ability

```

and here are my results:

```
 const permissions = [
    { subject: 'User', action: ['create', 'update', 'delete'] },
    { subject: 'ManageStuff', action: ['create', 'update', 'delete'] }
 ]

ability.can("create", "User") # => True
ability.can(["create", "update"], "User") # => False
ability.can("create", ["User", "ManageStuff"]) # => False
ability.can(["create", "update"], ["User", "ManageStuff"]) # => False
```

Am I just missing something or doing something silly?

**Comment by stalniy** [comment]
You can pass array only when defining abilities but NOT when checking. 

The logic people expect `ability.can([“edit”, “create”], “Post”)` highly depends on their needs: somebody expect it to work as OR and others as AND. That’s why it’s not supported.

**Comment by stalniy** [comment]
Be explicit and use Boolean operators. Additionally, you can create  `can` function wrapper that behaves as you need
