### ISSUE TITLE
CASL/Vue - Vue 2 support with Composition Api

### ISSUE THREAD

**Issue by dombavetta** [stalniy/casl#495]
**Is your feature request related to a problem? Please describe.**
I would like to use the new version of CASL Vue with Vue 2 + [composition api plugin](https://github.com/vuejs/composition-api). I need to maintain my application in this way until I can migrate to Vue 3. 

**Describe the solution you'd like**
[Vue Demi](https://github.com/vueuse/vue-demi) allows packages to be cross compatible with Vue 2 and Vue 3 projects. By utilizing this package we can maintain the same api while opening up the package to be used with a far greater amount of apps still running on Vue 2.

**Describe alternatives you've considered** (optional)
None.

This would obviously require bringing on an additional package dependency but I (personally) believe that trade off is worth it.

**Comment by stalniy** [comment]
Thanks for the proposal! Looks interesting but I don't think CASL needs something like this. v1.x is for vue2, so if you want to have some functionality from casl/vue v2, I could backport it to the 1.x version.

Would be good if you could help me to do this. Right now I pretty busy at my current work and the next big task I plan to do is integration with Prisma.js. So, this is not a high priority for me but I can help you if you need something

**Comment by dombavetta** [comment]
Hey, thanks for the quick response. Fair point in regards to keeping v2.x coupled to Vue 3, I think your proposal makes more sense.

On that note, because the size was so small - I actually already started rewriting the Casl/Vue source within my project. Im using the composition api plugin directly. I will touch back here when completed and start a conversation about how we want to integrate the changes in to the current v1 package.

**Comment by stevebaros** [comment]
CASL v4 upwards is pretty easy to work with composition API , i have used both neither hacking nor workarounds .

**Comment by dombavetta** [comment]
@stevebaros yes it works just fine, Im using v5.2.x in a Vue 2 project with the composition api. The scope of this ticket was originally to bring Vue 2 support to future versions of the CASL/Vue v2 package but as Sergii mentioned, it makes more sense to backport the api the V1 package. With this approach, you can still use the most recent version of CASL, the Vue package would just come with the composable functions packaged inside. Although, the more I think about this.. I think it might make sense to wait until later this year to implement this when Vue backports the composition api to its 2.7 release. In this case, there would be no need to create a dependency between the composition api plugin.

I already reimplemented the composable functions in my Vue 2 project, I would just need to clean them up a bit before creating a PR to potentially merge in to the project. @stalniy what are your thoughts on waiting until Vue 2 receives the composition api vs including the composition api plugin as a (peer?/)dependency.

**Comment by stalniy** [comment]
let's add composition-api as optional peerDependency for now. As far as I can see it will take some time while Vue 2.7 is released

**Comment by stalniy** [comment]
As there is no other requests to support composition API in Vue2 for CASL, and @dombavetta doesn't provide a PR that adds this functionality to 1.x branch, I close this.

@dombavetta feel free to provide PR if with the functionality any time but I don't think it makes sense to keep this open

**Comment by mattzahel** [comment]
@stalniy Can we reopen this issue as the Vue 2.7 that brings in the built-in Composition API came out about a month ago and it is impossible to work with this API and the `@casl/vue` package?

**Comment by chantouchsek** [comment]
Is there any progress?

**Comment by stalniy** [comment]
is this still relevant to anybody?

**Comment by stalniy** [comment]
looks like not, so close it again :)
