### ISSUE TITLE
CASL Examples of integration in X framework

### ISSUE THREAD

**Issue by stalniy** [stalniy/casl#5]
- [x] [Angular 2+](https://medium.com/@sergiy.stotskiy/managing-user-permissions-in-angular-application-504c83752f83)
- [x] [Aurelia](https://medium.com/dailyjs/casl-based-authorization-in-aurelia-app-3e44c0fe1703)
- [x] [Vue.js](https://medium.com/@sergiy.stotskiy/vue-acl-with-casl-781a374b987a)
- [x] [React integration](https://medium.com/@sergiy.stotskiy/managing-user-permissions-in-your-react-app-a93a94ff9b40)
- [x] [Express.js](https://medium.com/dailyjs/authorization-with-casl-in-express-app-d94eb2e2b73b)
- [x] [Feathersjs](https://blog.feathersjs.com/authorization-with-casl-in-feathersjs-app-fd6e24eefbff)
- [x] [Rails + cancan](https://medium.com/@sergiy.stotskiy/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec)

**Comment by akaNightmare** [comment]
+ Vue

**Comment by elixiao** [comment]
- Angular2+ integration

**Comment by stalniy** [comment]
An article for Vue https://medium.com/@sergiy.stotskiy/vue-acl-with-casl-781a374b987a

**Comment by stalniy** [comment]
integration with React https://github.com/stalniy/casl-react-example, the article is coming soon

**Comment by stalniy** [comment]
the article about React will be published on 5th Feb

**Comment by stalniy** [comment]
https://medium.com/@sergiy.stotskiy/managing-user-permissions-in-your-react-app-a93a94ff9b40

**Comment by stalniy** [comment]
[Vue and CASL on Rails with Cancan](https://medium.com/@sergiy.stotskiy/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec)

**Comment by stalniy** [comment]
CASL with Vue and Vuex repo - https://github.com/stalniy/casl-vue-api-example

**Comment by mrV25** [comment]
Hi, thanks a lot for providing example for React,
but still is it possible to give an separate example for React + Redux?

To be honest I just have a problem updating rules on user login event,
and how to use Ability.update in general,
in understanding how Ability persists in our app.

Sorry if this is off-topic,
and if you have no time for this implementation,
just reply something like "have no time for this",
so I will move on to something custom.

**Comment by stalniy** [comment]
@mrV25 you can check how I did this for Vuex in this repo https://github.com/stalniy/casl-vue-api-example . Also you can find useful explanations in this article https://medium.com/@sergiy.stotskiy/casl-and-cancan-permissions-sharing-between-ui-and-api-5f1fa8b4bec

Currently I don't plan to write an article about React and Redux, probably a bit later I will publish a book about CASL with recipes for different integrations and requirements

**Comment by stalniy** [comment]
https://github.com/stalniy/casl-angular-example example for Angular. Plan to publish an article about it in a week

**Comment by stalniy** [comment]
article for Angular https://medium.com/@sergiy.stotskiy/managing-user-permissions-in-angular-application-504c83752f83
