### ISSUE TITLE
How to use CASL to limit the field value to be patched(updated)?

### ISSUE THREAD

**Issue by flight9** [stalniy/casl#501]
After reading the guides and searching google for some time, I couldn't find a way in CASL to solve my usecase.

### My goals
- A user can only patch his appointments.
- A user can only patch appointment.status from 'created' to 'cancelled'(not other values, like 'kept').
(`status` field may have one of these values: 'created', 'cancelled', 'kept', 'broken'... But some values like 'kept, broken' can be updated only by users with special role, eg 'teacher', not by a common user.)

### My Code
```
// define rules
async function defineAbilitiesFor(user) {
	if(user) {
		can('patch', 'appointments', { user_id: user.id, status: 'created' });
		// Nowhere to define rule for limit status to be patched
	}
}

// test rules
const appointment = {..., user_id:1, status:'created' };
const toPatch = { status: 'cancelled' };
ability.can('patch', appointment); // Nowhere to check `toPatch` data
```

**Comment by stalniy** [comment]
Sorry, I don’t understand the issue. You didn’t follow one of suggested templates at least specify expected/actual result. 

So, I close the issue. 

Ps: my guess is that you want to restrict status to be in specified range, if so then use `$in` operator

**Comment by stalniy** [comment]
Move this question to stackoverflow please. This repo is for issues and enhancements

**Comment by flight9** [comment]
> Sorry, I don’t understand the issue. You didn’t follow one of suggested templates at least specify expected/actual result.
> 
> So, I close the issue.
> 
> Ps: my guess is that you want to restrict status to be in specified range, if so then use `$in` operator

Sorry for not following your suggested templates.

But my question can't be solved by using `$in` operator. 
`can('patch', 'appointments', { user_id: user.id, status: {$in: ['created','cancelled'] });`
can not solve two issues:
- a user can still update appointment to other status, eg 'broken'; (for an appointment can only be set broken by a supervisor user)
- a user can update appointment from `cancelled` to `created`; (for an appointment can only be cancelled once.)

**Comment by stalniy** [comment]
here you need something like state machine with possible transitions. So you have 2 levels of restrictions:
- logical (transition of status cannot happen from canceled to created)
- permission based (additionally restrict what status user can set appointment)

So, now you have 2 options:
- implement  [custom operator for CASL](https://casl.js.org/v5/en/advanced/customize-ability) that will behave as you want but I don't know how you will get the previous value
- find a state machine library that does logical restrictions of transitions and use `$in` operator in CASL

**Comment by flight9** [comment]
thanks @stalniy , I'm considering option 2.
