### ISSUE TITLE
Question: are you aware of a CASL .NET library?

### ISSUE THREAD

**Issue by middiu** [stalniy/casl#503]
Hello, 

is anyone aware of a CASL (or similar) .net library?

I'm using casl for my React application and my CASL permissions/roles definition are stored in JSON format in a NoSQL database.
The idea was to re-use the same permissions/roles definition in my C#/.NET WebApi project.... this is why I'm looking for this.

Thanks

**Comment by stalniy** [comment]
hello

I’m not aware of such but you can google for “.net cancan” to find something similar
