### ISSUE TITLE
Advanced condition matching with arrays?

### ISSUE THREAD

**Issue by anthonyp** [stalniy/casl#519]
I have a scenario where I need to ensure that every item in an incoming array must be comprised only of items in a dynamically generated source array.

For example, given this dynamically generated source array:
[1, 2, 3, 4, 5, 6, 7]

This incoming array would pass:
[1, 3, 5]

And this one would fail:
[1, 7, 8]

Using Mongo directly, I might be able to use something like `$where` to accomplish this. Is there any way to do it w/ CASL or otherwise extend CASL w/ the capability?

**Comment by stalniy** [comment]
Mongo has `$all` operator which I think can fulfill your requirements - https://docs.mongodb.com/manual/reference/operator/query/all/

CASL supports it out of the box - https://casl.js.org/v5/en/guide/conditions-in-depth

anyway, if you need `$where` operator just include it into your custom condition matcher - https://casl.js.org/v5/en/advanced/customize-ability#extend-conditions-with-custom-operators

**Comment by stalniy** [comment]
Close as this is not an issue

**Comment by anthonyp** [comment]
That does the trick, thanks!

**Comment by Rutenioh** [comment]
I understand this thread is quite old, but I'm currently facing a similar issue regarding the where operator. I need to check if an array is greater than a number and I can not resolve it. I tried with the custom operator but I think I am having problems to implement it.
Do you have a little example with this operator, please?

**Comment by stalniy** [comment]
Can you show an example? Or maybe even start a new discussion in discussions
