### ISSUE TITLE
Ability refreshes are not honored when used inside `useMemo`, `useEffect`, etc.

### ISSUE THREAD

**Issue by anthonyp** [stalniy/casl#520]
**Describe the bug**
Ability refreshes are not honored when used inside `useMemo`, `useEffect`, etc.

**To Reproduce**
See sandbox: https://codesandbox.io/s/eager-chatelet-zv2ko?file=/src/App.js

**Expected behavior**
The app should state:

> I can read a {animal} from functional component logic.

... at the same time(s) as the other 2 messages.

**Interactive example** (optional, but highly desirable)
https://codesandbox.io/s/eager-chatelet-zv2ko?file=/src/App.js

**CASL Version**
    "@casl/ability": "^5.3.1",
    "@casl/react": "^2.3.0"

**Environment**:
See sandbox.

**Comment by stalniy** [comment]
Hi,

Thanks for the issue. Sorry for not looking into it for so long.  In my chrome, both components are updated synchronously. Maybe I miss something?



https://user-images.githubusercontent.com/1159966/124474969-d7859700-dda9-11eb-82d9-8c5ecf7788ef.mp4

**Comment by stalniy** [comment]
@anthonyp any clarifications? if not then I will close this

**Comment by stalniy** [comment]
@anthonyp could you please provide more details on what is wrong? if not I'm going to close this issue at the end of the week

**Comment by stalniy** [comment]
close as there is not enough details. Feel free to reopen and provide more info on what is expected. 

To me it seems that it works as expected
