### ISSUE TITLE
Ability to have condition as function

### ISSUE THREAD

**Issue by mmahalwy** [stalniy/casl#526]
**Is your feature request related to a problem? Please describe.**
There are cases where it'd be great to have the conditions of an ability be a function – this could be for fetching data related to the subject. An example is checking a subject that has a many-to-many relationship where the join table needs to be queried. In the traditional Twitter example, a user has many followers and many following. 

**Describe the solution you'd like**
Add ability to conditions for an async function

```ts
can('read', Follower, async (followerSubject) => /* use subject to query a db and return true/false or an object */)
```

**Describe alternatives you've considered** (optional)
Eager loading the data for the subject, then using nested conditions. Not ideal though. 

**Additional context** (optional)

**Comment by stalniy** [comment]
Please read comments in this issue https://github.com/stalniy/casl/issues/160

originally, I decided not to implement this because it changes all methods to be async.

There is no easy way to support both styles in single class, so you can try to implement it yourself (based on PureAbility class) and let me know how it goes

**Comment by stalniy** [comment]
Casl works best when you model BL according DDD and check permissions on Aggregate Roots. 

It also works good in NoSQL world. For SQL there is a pending issue but eventually you could use something like this to check permissions on relations:

```ts
const isAllowed = Post.exists({
  where: acessibleBy(ability).Post
})
```

this already works in @casl/prisma - https://casl.js.org/v5/en/package/casl-prisma

**Comment by stalniy** [comment]
Close, because in the foreseen future don’t plan to implement this

**Comment by mmahalwy** [comment]
hey @stalniy thanks for the quick reply! 

I am using Prisma and GraphQL. Problem is, I need to check if an object is related to another model. My current solution is to requery the object with the associated models and do a check that way


```ts
subject(
          'ApplicationFormConfig',
          await prisma.applicationFormConfig.findUnique({
            where: { id: parent.id },
            include: { organizations: true },
            rejectOnNotFound: true,
          })
```

Then in ability:
```
can(manage, 'ApplicationFormConfig', { organizations: { every: { id: organization.id } } });
```

This will get the job done, so I'm not too bothered, but I can would have much rather made that query in the `can` definition so that I don't have to repeat this query in other places. 

Do you have an example where I can create my own with `PureAbility`? Is there a way to extend the `can` method for `Ability` right now? I'd like to maintain the casl/prisma features.
