### ISSUE TITLE
`field` property is read from props inderectly (@casl/vue@1.2.2)

### ISSUE THREAD

**Issue by cpof-tea** [stalniy/casl#532]
`field` is read from split of either `I` or `do` properties,
i.e. current example of `Can` component usage is `<Can I="update title" a="Article">...</Can>`
https://github.com/stalniy/casl/blob/404fa444097d230f56819831228719a124043a0c/packages/casl-vue/src/component/can.ts#L36

**Comment by stalniy** [comment]
and where is the issue?

**Comment by cpof-tea** [comment]
`<Can I="update" a="Article" field="title">...</Can>` doesn't work, because `field` property is ignored by `Can` component, but [readme says it shouldn't](https://github.com/stalniy/casl/blob/404fa444097d230f56819831228719a124043a0c/packages/casl-vue/README.md#can-component)

**Comment by stalniy** [comment]
Ah I see, thanks!

**Comment by cpof-tea** [comment]
https://github.com/cpof-tea/casl/compare/@casl/vue@1.2.2...ad75c668fb9596fc5eccb899731a657602328d95

**Comment by stalniy** [comment]
thank you for the patch! there are some issues to backport fixes in the old releases that's why I did it by myself. fixed in @casl/vue@1.2.3
