### ISSUE TITLE
Guard against array?

### ISSUE THREAD

**Issue by mmahalwy** [stalniy/casl#558]
**Is your feature request related to a problem? Please describe.**
No. I am wondering if it's possible to guard against an array, not nested. 

**Describe the solution you'd like**
```ts
ForbiddenError.from(ability).throwUnlessCan(
          'read',
          quotes.map((q) => subject('Quote', q))
        );
```

**Describe alternatives you've considered** (optional)
I know I can do this:
```ts
quotes.forEach((q) => ForbiddenError.from(ability).throwUnlessCan(
          'read', subject('Quote', q)));
```

**Additional context** (optional)

**Comment by stalniy** [comment]
No support for array validation. Either use integration with mongoose or prisma where you can use `accessibleBy` helper or use forEach/some/every
