### ISSUE TITLE
(casl/mongoose or ucast/mongo?): merge mongo query

### ISSUE THREAD

**Issue by rubybb** [stalniy/casl#564]
**Is your feature request related to a problem? Please describe.**
```ts
const { toMongoQuery } = require('@casl/mongoose');
const ability = require('./ability'); /* some predefined ability */

const query = toMongoQuery(ability, 'Post', 'update');
/* this returns a mongodb filter, but if I wanted to add custom properties to it, 
there's a pretty likely chance there'd be conflict or it'd be an invalid query. */
```

**Describe the solution you'd like**
```ts
const { Ability, AbilityBuilder } = require("@casl/ability");
require("mongoose") /* peer dependency */

const { toMongoQuery } = require("@casl/mongoose")

const builder = new AbilityBuilder(Ability);
builder.can("read", "Post", { id: "bar" });

const ability = builder.build();
toMongoQuery(ability, "Post", "read") /* { $or: [{ id: "bar" }] } */
toMongoQuery(ability, "Post", "read", { baz: "foo" }) /* { $or: [{ id: "bar", baz: "foo" }] } */
/* the above function signature is my suggestion */
```

**Describe alternatives you've considered** (optional)

**Additional context** (optional)

This could probably be implemented in rulesToQuery or directly in one of the projects in the ucast ecosystem.

**Comment by stalniy** [comment]
Can you write your query in this way?

```ts
const query = {
  $and: [
     toMongoQuery(...),
     /* custom additions */ 
  ]
}
```

**Comment by rubybb** [comment]
That's quite possible but I feel like it could internally minify, simplify
the query ect.

**Comment by stalniy** [comment]
Sure, it can Munich but may also cause issues. I don’t want developers  to depend on the shape of query casl returns. Eventually, it may change due to some internal optimizations, so the best way to go is to use methods which MongoDB provides to combine queries together

**Comment by stalniy** [comment]
Close the issue because I don’t see good reasons to make public api more flexible at this moment. 

Feel free to comment and provide additional arguments. I’m ok to reopen the issue if we find consensus on this
