### ISSUE TITLE
using casl/mongoose with typescript

### ISSUE THREAD

**Issue by Tasades** [stalniy/casl#57]
Hello, I tried to integrate casl in my node js project, but I failed. 

I user typescript and get the following erros during building:

node_modules/@casl/mongoose/index.d.ts(2,8): error TS1192: Module '"mongoose"' has no default export.
node_modules/@casl/mongoose/index.d.ts(7,3): error TS7010: 'permittedFieldsBy', which lacks return-type annotation, implicitly has an 'any' return type.

Thank you for helping.

**Comment by stalniy** [comment]
Hello,

This is a bug. I'm going to fix this soon. Thanks for the report!

**Comment by stalniy** [comment]
Fixed in `@casl/mongoose@2.1.1`
