### ISSUE TITLE
Angular pipe type issue

### ISSUE THREAD

**Issue by TheSlimvReal** [stalniy/casl#574]
**Describe the bug**
When using the `AbilityPipe` or the `AbilityPurePipe` Webstorm is showing type errors.
See the screenshot for the exact error message but the error message _type update is not assignable to paramter type any_ does not really make sense to me.
![image](https://user-images.githubusercontent.com/33730997/142849916-de03ed08-3fce-44ed-8248-6b9fedc40dc8.png)
![image](https://user-images.githubusercontent.com/33730997/142849952-5cb7d0df-006d-4463-a24d-0da5304947ba.png)
The types are correctly set up and using `update` and the `Entity` class with the `Ability` injectable does not create errors.
I followed the [TypeScript](https://casl.js.org/v5/en/advanced/typescript) and the [Angular](https://casl.js.org/v5/en/package/casl-angular) guide for a correct setup. 

**To Reproduce**
1. Use Webstorm
2. Import the `AbilityModule`
3. Use the `AbilityPipe` or the `AbilityPurePipe` in a template

**Expected behavior**
The template files should not show error messages about wrong types.

**CASL Version**

```
"@casl/ability": "^5.4.3",
"@casl/angular": "^5.1.1",
```

**Environment**:
node@16.8.0

**Comment by stalniy** [comment]
I don’t know what’s wrong with webstorm. Maybe types pipe uses are too complicated (lots of conditionals). 

So, can’t say for sure. The app should compile without any issues.

**Comment by TheSlimvReal** [comment]
Yes compiling works fine. 
I am also no expert on this topic so let's see if something might be fixed in the future.

**Comment by stalniy** [comment]
Close as there is not enough information. Anyway, I plan to change API and officially will propose to use observables instead of pipes
