### ISSUE TITLE
Support to Next.js

### ISSUE THREAD

**Issue by paoru5444** [stalniy/casl#576]
Hi folks, I'm thinking in implement CASL in my company stack and I need to know if there is support to Next.js projects.

**Comment by stalniy** [comment]
Do you have anything particular in mind or it’s a general question?

**Comment by paoru5444** [comment]
@stalniy I think its a general question, I want to use this within a next project

**Comment by stalniy** [comment]
You can use it within nestjs already:
1. “Integrating CASL” section - https://docs.nestjs.com/security/authorization
2. https://mfi.engineering/extensible-and-secure-authorization-with-nestjs-and-casl-c6f6d1ceefd5
3. google for casl and nestjs you will find repos and tutorials written by other people

**Comment by stalniy** [comment]
I close this because we don’t have any particular requirements for this issue. When somebody have, I’m ok to reopen this

**Comment by stalniy** [comment]
next this is similar to Vue's nuxt but on React? If so, then I do not plan to do anything particular about it as well. Can be done in user-land because there are integration for both Vue and React
