### ISSUE TITLE
Type error when updating rules in vue 3

### ISSUE THREAD

**Issue by raphaelschwinger** [stalniy/casl#577]
**Describe the bug**
When calling `update(rules)` a type error: `Cannot read properties of undefined (reading 'j')` is raised.
I tried to follow the [docs](https://casl.js.org/v5/en/package/casl-vue#update-ability-instance).

**To Reproduce**
1. define rules with AbilityBuilder:
```
    const { can: can, rules } = new AbilityBuilder(Ability);
    can("read", "Thing");
```
2. update ability:
```
const { update } = useAbility();
update(rules);
```

**Expected behavior**
Rules get updated

**Interactive example** (optional, but highly desirable)
https://codesandbox.io/s/trusting-northcutt-g60jh?file=/src/App.vue:585-599

**CASL Version**

`@casl/ability` - v 5.4.3
`@casl/vue` - v 2.1.2

**Environment**:

Codesandbox: core-js 3.19.2 vue 3.2.23

**Comment by stalniy** [comment]
In documentation there is no such example. `update` of Ability is not bound (only `can` and `cannot` are bound), that’s why  you get an error. 

To make it work either change your code to this:

```js
const  ability = useAbility();
ability.update(rules);
```

or bind `ability` to `update` method.

**Comment by stalniy** [comment]
Close because this is not a bug and works as expected. 

I don’t see reasons to bind `update` in library because this method is so rarely used in comparison to `can` and `cannot`

**Comment by raphaelschwinger** [comment]
Thanks for clarifying this!
I updated the CodeSandbox and it is working as expected now.
