### ISSUE TITLE
Allow adding multiple abilities with single `can` function call of AbilityBuilder

### ISSUE THREAD

**Issue by jd-0001** [stalniy/casl#578]
**Is your feature request related to a problem? Please describe.**
I am getting array of abilities that I can individually provide to `AbilityBuilder`

Current Implementation:
```ts
export interface UserAbility {
  action: string
  subject: string
}

export interface LoginResponse {
  // other
  userAbilities: UserAbility[]
}

// ---

const ability = useAbility()

const { can, rules } = new AbilityBuilder(Ability)
userAbilities.forEach(userAbility => {
  can(...Object.values(userAbility))
})

ability.update(rules)
```

**Describe the solution you'd like**
Allow providing multiple abilities to `can`.

```js
can(userAbilities)
```

**Describe alternatives you've considered** (optional)
```js
userAbilities.forEach(userAbility => {
  can(...Object.values(userAbility))
})
```

**Additional context** (optional)

**Comment by stalniy** [comment]
AbilityBuilder is an utility, DSL which should be easy to read and write for people manually. That means I won’t add support for multiple values. 

Can you please tell me why you don’t pass your objects directly into `ability.update()`?

**Comment by jd-0001** [comment]
Oh, sorry I didn't know I can do that.

Actually, I didn't find any example on this in docs. However, I found this section but I thought this is not my case and I referred to [this](https://casl.js.org/v5/en/package/casl-vue#update-ability-instance) issue and wrote related code.

With your suggestion, this issue is not relevant so closing this.
