### ISSUE TITLE
[docs] Vue Typescript snippet from docs gives `AppAbility` is already defined

### ISSUE THREAD

**Issue by jd-0001** [stalniy/casl#579]
**Describe the bug**
I am creating typescript app with vue and following [this](https://casl.js.org/v5/en/package/casl-vue#type-script-support) docs. `AppAbility.ts` file show below code snippet:
```ts
import { Ability, AbilityClass } from '@casl/ability';

type Actions = 'create' | 'read' | 'update' | 'delete';
type Subjects = 'Article' | 'User'

export type AppAbility = Ability<[Actions, Subjects]>;
export const AppAbility = Ability as AbilityClass<AppAbility>;
```

Above code shows the below error:
![Screenshot 2021-12-16 at 11 31 17 AM](https://user-images.githubusercontent.com/47495003/146316831-61d6e3cd-268f-416d-beb6-00b724316eec.png)

**To Reproduce**
1. Create new typescript file (i.e. AppAbility.ts)
2. Paste the code for docs or above snippet

**Expected behavior**
Nothing. Just docs needs some update.

**Interactive example** (optional, but highly desirable)
N/A

**CASL Version**
N/A

**Environment**:
N/A

**Comment by stalniy** [comment]
Not a bug actually. It’s so called Companion object pattern. Please refer to https://dev.to/hcapucho/typescript-patterns-2d8n

Probably your IDE settings or eslint needs to be adjusted properly for this pattern to work correctly
