### ISSUE TITLE
Vue $ability is not defined when using Vue Composition API

### ISSUE THREAD

**Issue by adrianwix** [stalniy/casl#585]
**Describe the bug**
I am getting a $ability is undefined when trying to access it using the Vue Composition API (I use Vue 2 in Nuxt with the @nuxtjs/composition-api plugin.

**To Reproduce**

1. Install the nuxt plugin
```ts
import { defineNuxtPlugin } from '@nuxtjs/composition-api'
import Vue from 'vue'
import { abilitiesPlugin } from '@casl/vue'
import { Ability } from '@casl/ability'

export default defineNuxtPlugin((_ctx) => {
    const ability = new Ability([])
    Vue.use(abilitiesPlugin, ability, {
        useGlobalProperties: true
    })
})
```

2. Try to access $ability inside setup. It is not inside the ctx when using the useContext() composable
```vue
<script>
import { defineComponent, ref, useAsync, useContext } from '@nuxtjs/composition-api'
import { Ability } from '@casl/ability'

export default defineComponent({
    auth: false,
    setup() {
        const ctx = useContext()

        const roles = ref({})

        useAsync(async () => {
            roles.value = await ctx.$axios.$get('/access-control/rules')
        })

        console.log(ctx)
        // This throws can't read "update" of undefined
        // $ability.update(new Ability(roles.value.groupMember))

        return {
            roles
        }
    }
})
</script>
```

**Expected behavior**

**Interactive example** (optional, but highly desirable)
provide a link to the example from http://repl.it/, https://codesandbox.io/ or similar, so we can quickly test and provide feedback. Otherwise

**CASL Version**

"@casl/ability": "^5.4.3",
"@casl/vue": "1.x",

**Environment**:

"@nuxtjs/composition-api": "^0.29.2"
"nuxt": "^2.15.7"
node -v => v14.18.2
npm -v => 6.14.15

**Comment by stalniy** [comment]
@casl/vue@1.x doesn't work with composition API use the latest version

**Comment by adrianwix** [comment]
Can I use @casl/vue@2.x with Vue 2 and the composition-api plugin?

**Comment by stalniy** [comment]
No, it requires Vue 3. There was some discussion about adding support for it by the community but nobody provided PR -https://github.com/stalniy/casl/issues/495
