### ISSUE TITLE
Vue: $ability.can is not reactive

### ISSUE THREAD

**Issue by adrianwix** [stalniy/casl#586]
**Describe the bug**
Updating the abilities of a user is not reactive. I need to change pages to see the effect. 

**To Reproduce**

1. Create some component or text that should be shown if the user has permission
2.  It should be unallowed by default
3.  Call $ability.update with new permissions that allow the user to see the text
4.  It still won't show unless you travel to a new page and return

**Expected behavior**

**Interactive example** (optional, but highly desirable)
provide a link to the example from http://repl.it/, https://codesandbox.io/ or similar, so we can quickly test and provide feedback. Otherwise

**CASL Version**

"@casl/ability": "^5.4.3",
"@casl/vue": "1.x",

**Environment**:

"@nuxtjs/composition-api": "^0.29.2"
"nuxt": "^2.15.7"
node -v => v14.18.2
npm -v => 6.14.15

**Comment by stalniy** [comment]
Thank you for the issue. In 1.x `$ability.can` is not reactive that's why you need to use `this.$can()` to check permissions in components
