### ISSUE TITLE
Infer subject types from classes dosnt work

### ISSUE THREAD

**Issue by Wenish** [stalniy/casl#595]
Fr, 04.02.2022 20:21
**Describe the bug**
If you cast ability.can(Action, object) with a mongoose model it returns false but it should return true.
the error is that it dosnt infer the subject correctly.

I referring to this part of the docs: https://casl.js.org/v5/en/guide/subject-type-detection#how-does-casl-detect-subject-type

Its says it takes it from `object.constructor.modelName` if its defined

with the defineSubjectType function it should work with classes like described here:
https://casl.js.org/v5/en/guide/subject-type-detection#use-classes-as-subject-types

and with typescript you have to pass second argument as true on InferSubjects
https://casl.js.org/v5/en/advanced/typescript#infer-subject-types-from-interfaces-and-classes

**To Reproduce**
I made a github repo:
https://github.com/Wenish/nestjs-mongoose-casl

1. clone the repo
2. run command `npm ci`
3.  run command `npm test`

you will see the test 'user should be able to read specific offer' fails:
https://github.com/Wenish/nestjs-mongoose-casl/blob/main/src/casl/casl-ability.factory.spec.ts#L51

**Expected behavior**
I would expect that this return true:
https://github.com/Wenish/nestjs-mongoose-casl/blob/main/src/casl/casl-ability.factory.spec.ts#L62

**Interactive example** (optional, but highly desirable)
https://github.com/Wenish/nestjs-mongoose-casl

**CASL Version**

`@casl/ability` - v5.4.3

**Environment**:
`node` - v16.13.0
`TypeScript` - 4.3.5

**Comment by Justinio99** [comment]
I have exactly the same problem using nestjs...

**Comment by stalniy** [comment]
Hi guys,

Not a bug. CASL works as expected, the issue is that you are using classes to describe your mongodb models. This is a hacky way to define mongoose models. Eventually, these classes are nothing more than just metadata stuff which is then thrown away in runtime.

You can check it yourself that the instance of created mongoose model has nothing to do with the schemas you defined. There is a special test that ensures this specific scenario works in normal conditions - https://github.com/stalniy/casl/blob/master/packages/casl-ability/spec/ability.spec.js#L113

And yes, I know your pain and hate mongoose. Mongoose works very badly with TypeScript, very inconvenient.

**Comment by stalniy** [comment]
Use your models in casl definitions instead of schema classes and it will work. 

Close as there is nothing to do from CASL side

**Comment by Wenish** [comment]
@stalniy did you even took the time to run the example?

**Comment by Wenish** [comment]
@stalniy what you mean with use the models in casl definitions?

can you elaborate a little bit more

**Comment by stalniy** [comment]
I don’t need to run the code when I see a clear issue. So

https://github.com/Wenish/nestjs-mongoose-casl/blob/main/src/casl/casl-ability.factory.spec.ts#L61 <- here you check permissions on instance of OfferModel

BUT here -> https://github.com/Wenish/nestjs-mongoose-casl/blob/main/src/casl/casl-ability.factory.ts#L22 you define permissions on `Offer` class. 

Offer class is not a class that creates an instance of OfferModel. These are 2 different classes

1st - serves the purpose of metadata to make mongoose schema from it nothing more. The 2nd one is a compiled constructor function from the schema. 

Hopefully it makes sense.

**Comment by Wenish** [comment]
@stalniy maybe i need to point it out more clearly

the modelName of the OfferModel is in fact "Offer"

this test is true
https://github.com/Wenish/nestjs-mongoose-casl/blob/5e0ed4b0262dff30ea303fe8bd9b230628c65111/src/casl/casl-ability.factory.spec.ts#L48

And if i read the docs:
https://casl.js.org/v5/en/guide/subject-type-detection#how-does-casl-detect-subject-type
it says `CASL gets object.constructor.modelName`
so my test clearly shows. it dosnt take modelName into account to infer the subject

**Comment by Wenish** [comment]
and maybe its a big ask. but would it be possible to make a running example with nestjs and mongoose? 
it has 44k stars on github. im not the first one running into the issue.

**Comment by stalniy** [comment]
Guys, you changed default behavior by providing custom `detectSubjecType` and still want the default behavior to take place :) 

In this place: 
https://github.com/Wenish/nestjs-mongoose-casl/blob/5e0ed4b0262dff30ea303fe8bd9b230628c65111/src/casl/casl-ability.factory.ts#L47

If you want to rely on stringified subject names, you must use strings in rule definitions. You use classes. This classes are used as keys in cache map internally in casl. 

So, if you want to rely on modelName, remove that detectSubjectType option completely. And use strings in AbilityBuilder definitions (I.e., `”Offer”` instead of `Offer`), and it should work. 

Sorry, don’t have free time right now to run/update this example

**Comment by stalniy** [comment]
I’ll add a notice in the docs to make it super clear that when classes are used in definitions stringified subject types don’t work.

**Comment by xahanix** [comment]
same issue here

**Comment by mathibla** [comment]
Have the same problem. The test from @Wenish shows exactly the problem I run into.

**Comment by Wenish** [comment]
@mathibla @Justinio99 
hey guys
this is the solution i came up with.

the key with nestjs is to inject the model in the factory and use the injected model

no idea if there is away to simplify the definitions since atm wrote them 3 times.


```
import { InferSubjects, Ability, AbilityBuilder, AbilityClass, ExtractSubjectType } from "@casl/ability";
import { Injectable } from "@nestjs/common";
import { InjectModel } from "@nestjs/mongoose";
import { Model } from "mongoose";
import { Offer, OfferDocument, OfferStatus } from "../database/schemas/offer.schema";

export enum Action {
    Manage = 'manage',
    Create = 'create',
    Read = 'read',
    Update = 'update',
    Delete = 'delete',
}

@Injectable()
export class CaslAbilityFactory {
    constructor(
        @InjectModel(Offer.name)
        private offerModel: Model<OfferDocument>,
    ) { }
    
    createForUser(user: any) {
        const { can, cannot, build } = new AbilityBuilder<Ability<[Action, InferSubjects<typeof this.offerModel> | 'all']>>(Ability as AbilityClass<Ability<[Action, InferSubjects<typeof this.offerModel> | 'all']>>);

        can(Action.Read, this.offerModel, {
            publishDate: { $lte: new Date() },
            status: { $in: [OfferStatus.Approved] },
        });

        can(Action.Create, this.offerModel);

        if (user) {
            if (user?.uid) {
                can(Action.Manage, this.offerModel, { creator: user.uid });
            }

            const userRoles: Role[] = user?.roles || [];

            if (userRoles.includes(Role.CONTENT_MANAGER)) {
                can(Action.Manage, this.offerModel);
            }

            if (userRoles.includes(Role.SYSTEM_ADMIN)) {
                can(Action.Manage, 'all');
            }
        }

        return build({
            // Read https://casl.js.org/v5/en/guide/subject-type-detection#use-classes-as-subject-types for details
            detectSubjectType: object => {
                return object.constructor as ExtractSubjectType<InferSubjects<typeof this.offerModel> | 'all'>
            }
        });
    }
}

export enum Role {
    CONTENT_MANAGER = 'ContentManager',
    SYSTEM_ADMIN = 'SystemAdmin',
}
```

also that how the controller looks where i use the factory

```
import { Controller, Delete, Get, NotFoundException, Param, Patch, Post, UnauthorizedException } from '@nestjs/common';
import { ApiResponse } from '@nestjs/swagger';
import { Action, CaslAbilityFactory } from '../casl/casl-ability.factory';
import { OffersService } from './offers.service';
import { Offer, OfferDocument } from '../database/schemas/offer.schema';
import { Model } from 'mongoose';
import { InjectModel } from '@nestjs/mongoose';

@Controller('offers')
export class OffersController {
    constructor(
        @InjectModel(Offer.name)
        private offerModel: Model<OfferDocument>,
        private readonly offersService: OffersService,
        private readonly caslAbilityFactory: CaslAbilityFactory
    ) { }

    @Post()
    @ApiResponse({ type: Offer })
    create() {
        const user = {}
        const ability = this.caslAbilityFactory.createForUser(user);
        const canCreateOffers = ability.can(Action.Create, this.offerModel);
        console.log(this.timeString(),'can create offer', canCreateOffers)

        if (!canCreateOffers) throw new UnauthorizedException();

        return this.offersService.create();
    }

    @Get()
    @ApiResponse({ type: Offer, isArray: true })
    async readAll() {
        const user = {
            // roles: ['SystemAdmin']
        }
        const ability = this.caslAbilityFactory.createForUser(user);
        const canReadOffers = ability.can(Action.Read, this.offerModel);
        console.log(this.timeString(), 'can read offers', canReadOffers)

        if (!canReadOffers) throw new UnauthorizedException();

        return (await this.offersService.findAll()).filter((offer) => {
            const canReadOffer = ability.can(Action.Read, offer)
            console.log(offer.id)
            console.log(this.timeString(),'can read offer', canReadOffer)
            return canReadOffer
        });
    }

    @Get(':id')
    @ApiResponse({ type: Offer })
    async read(@Param('id') id: string) {
        const user = {}
        const ability = this.caslAbilityFactory.createForUser(user);
        const offer = await this.offersService.findOne(id)
        const canReadOffer = ability.can(Action.Read, offer)
        console.log(this.timeString(),'can read offer', canReadOffer)

        if (!canReadOffer) throw new UnauthorizedException();
        if (!offer) throw new NotFoundException();

        return offer;
    }

    @Patch(':id')
    @ApiResponse({ type: Offer })
    async update(@Param('id') id: string) {
        const user = {}
        const ability = this.caslAbilityFactory.createForUser(user);
        const offer = await this.offersService.findOne(id)
        const canUpdateOffer = ability.can(Action.Update, offer)
        console.log(this.timeString(),'can update offer', canUpdateOffer)

        if (!canUpdateOffer) throw new UnauthorizedException();
        if (!offer) throw new NotFoundException();
        
        return this.offersService.update(id)
    }

    @Delete(':id')
    @ApiResponse({ type: Offer })
    async delete(@Param('id') id: string) {
        const user = {}
        const ability = this.caslAbilityFactory.createForUser(user);
        const offer = await this.offersService.findOne(id)
        const canDeleteOffer = ability.can(Action.Delete, offer)
        console.log(this.timeString(),'can delete offer', canDeleteOffer)

        if (!canDeleteOffer) throw new UnauthorizedException();
        if (!offer) throw new NotFoundException();

        return this.offersService.delete(id);
    }

    private timeString() {
        const date = new Date()
        return `[${date.getHours()}:${date.getMinutes()}:${date.getSeconds()}]`
    }
}
```
the schema is in a seperate database module else offers module and the casl module would have circular dependencies

**Comment by Krzypis** [comment]
Hi @Wenish , could you let me know if the following:

>         const { can, cannot, build } = new AbilityBuilder(Ability as AbilityClass<Ability<[Action, InferSubjects<typeof this.offerModel> | 'all']>>);

still works for you?

Some of us gets:
> Expression expected
in typeof this.offerModel
