### ISSUE TITLE
Write access on a mongo collection

### ISSUE THREAD

**Issue by kalyandk1** [stalniy/casl#599]
**Describe the bug**
When I tried this --> mongoModelName.accessibleBy(ability, 'create').create(data); to check if the current_user is allowed to add a record to mongo collection and add record if allowed, it gives me this error -> this.issueCategoriesModel.accessibleBy(...).create is not a function

**Expected behavior**
It should create a record in specified mongo collection if the user has 'write' access to that collection

**CASL Version**

`@casl/ability` 5.4.3
`@casl/mongoose` 5.0.0

**Environment**:
 TypeScript version in nodejs

**Comment by stalniy** [comment]
Does mongoose support `Model.find({ status: “ready” }).create(..)` syntax?

If not, then not a casl issue

**Comment by stalniy** [comment]
Checked and mongoose doesn't support this syntax. Close as there is nothing to do from CASL side
