### ISSUE TITLE
Raw Rule conditions

### ISSUE THREAD

**Issue by cavator** [stalniy/casl#600]
I'm trying to create a Raw rules to send it to React, but the conditions don't autocomplete the fields from subjects, like it did when you use AbilityBuilder and Record, that i pass User as type to it, and how can i pass a user to RawRule as a type, to it accept thinks like "user.id" in conditions, i know i can create the rules inside a function that receive user as parameter to use in conditions, but if have a type way like i did in the Record to do a RBAC with CASL
i know it's not a issue, but you guys don't have a local to people make their questions, it would be great if you guys did a discord to people help themselves
![2022-02-23_10-09](https://user-images.githubusercontent.com/14593967/155325662-90aa5d4d-3c8d-49d5-a670-ba825d610ca0.png)

**Comment by stalniy** [comment]
Hi @cavator 

You can post your question either on stackoverflow or in https://gitter.im/stalniy-casl/casl

**Comment by cavator** [comment]
my man, please create a discord, no one stay looking this gitter to answer, discord is faster, poeple is always active, on gitter people not even asnwer, they just ask, so every 5days people send more questions but 0 responses :/
