### ISSUE TITLE
Angular 13 and rxjs update

### ISSUE THREAD

**Issue by blindsz** [stalniy/casl#601]
Hi, when can we expect a update to angular 13 and rxjs 7

**Comment by stalniy** [comment]
Please read more information about the current situation in Ukraine. I've already posted a message in gitter - https://gitter.im/stalniy-casl/casl#:~:text=I%27m%20Sergii%2C%20author%20of%20CASL

**Comment by stalniy** [comment]
will release a new version tomorrow

**Comment by mariod84** [comment]
news?

**Comment by stalniy** [comment]
just released a new version, please check and let me know whether everything works fine
