### ISSUE TITLE
object.hasOwnProperty and objects without prototype error

### ISSUE THREAD

**Issue by adrianwix** [stalniy/casl#604]
Please fix the calls to object.hasOwnProperty it causes the following error when the object does not has a Prototype.
the subject utility does not work because of that nor ability.can()
![image](https://user-images.githubusercontent.com/37629556/158629862-34a337d4-9c85-4e11-9928-085e64c2590d.png)

"@casl/ability": "^5.4.3",

PS: I don't think there is the need for more information regarding this bug. changing object.hasOwnProperty for Object.prototype.hasOwnProperty.bind(object)('Property') everywhere will solve the problem

**Comment by stalniy** [comment]
PR with such utility function is very welcome

**Comment by stalniy** [comment]
fixed in @casl/ability@6.0.0
