### ISSUE TITLE
Share 

### ISSUE THREAD

**Issue by atlanteh** [stalniy/casl#606]
First thanks so much for all the hard work on this awesome library!  

**Is your feature request related to a problem? Please describe.**
In every project we use `permittedFieldsOf` it's always also required to use external method to extract the fields as well (either lodash.pick or custom pick you guys created). Since this library supports `*` and `**` it would be great if it also supports stripping objects based on these attributes, and not rely on external implementation, which in any case doesn't support `**`.

**Describe the solution you'd like**
Integrate `https://gist.github.com/stalniy/855f3de3115c8a89824370cb4d8bb5a7` into the package, make sure it supports `**` and expose a `filter` method on the ability or in the extra package that will accept an action, subject and object, and will return an object only with allowed fields.

**Describe alternatives you've considered** (optional)
Keep using the external implementation

**Additional context** (optional)
None

**Comment by stalniy** [comment]
Can you make a PR with tests?

**Comment by stalniy** [comment]
close as this is the 1st request like this and there is no PR
