### ISSUE TITLE
MongoQuery type causes error in Vue3 composable return type

### ISSUE THREAD

**Issue by NicoAiko** [stalniy/casl#608]
**Describe the bug**
I have an interface that uses the `MongoQuery` type in one of its properties.
It seems that adding this type causes TS-4058 errors.
`Return type of exported function has or is using name '$value' from external module "node_modules/@casl/ability/dist/types/hkt" but cannot be named.`

**To Reproduce**
1. Set up a regular vue3 app boilerplate
2. Add casl
3. Copy in the following code:

```ts
// A.ts
import type { MongoQuery } from '@casl/ability';

export interface A {
  foobar: MongoQuery;
}
```

```ts
// aTest.ts
import { ref } from 'vue';
import type { A } from './A';

export function useAtest() {
  const aBunchOfAs = ref<A[]>([]);
  return {
    aBunchOfAs,
  };
}
```

**Expected behavior**
Using the type should not cause an error.

**CASL Version**

`@casl/ability` - v5.4.3
`@casl/vue` - v2.1.2

**Environment**:
Node.JS v16.14.0
TypeScript v4.6.3

**Comment by stalniy** [comment]
cannot reproduce this

**Comment by stalniy** [comment]
but exported that symbol just in case it's needed by TS to generate other d.ts files. Exported in `@casl/ability@6.1.1`
