### ISSUE TITLE
Support for Deno

### ISSUE THREAD

**Issue by sunw31** [stalniy/casl#614]
**Is your feature request related to a problem? Please describe.**
Deno hasn't casl module

**Describe the solution you'd like**
public casl module

**Describe alternatives you've considered** (optional)
compatible to deno

**Additional context** (optional)
also recommend
https://deno.land/manual/node/dnt

**Comment by stalniy** [comment]
Contributions are very welcome. Very unlikely that I’ll be able to do this in the nearest future

**Comment by Blanen** [comment]
I'd like this too but casl doesn't use ES modules so would have to be an annoying porting job.

**Comment by Blanen** [comment]
Actually core uses ES modules and TS.

I'll try out the core only and see if it works.

**Comment by stalniy** [comment]
Casl provide esm version as well but without absolute urls. Is there a tutorial that helps to understand what needs to be done?

**Comment by stalniy** [comment]
Looks like Deno is going to [support NPM](https://deno.com/blog/changes#compatibility-with-node-and-npm) out of the box, so no need to do anything.

Close this as wontfix.
