### ISSUE TITLE
casl-vue: What should my /services/ability.js file look like?

### ISSUE THREAD

**Issue by ocratravis** [stalniy/casl#617]
Hi there –

I'm trying to follow the instructions in [the README file for casl-vue](https://github.com/stalniy/casl/tree/master/packages/casl-vue) to integrate with Vue 3.

I've followed the first instruction, to add the following to my main.js:

```
import { abilitiesPlugin } from '@casl/vue';
import ability from './services/ability'

app.use(abilitiesPlugin, ability, {
    useGlobalProperties: true
})
```

However, I get this error in the console:

```
plugin.ts:12 Uncaught Error: Please provide an Ability instance to abilitiesPlugin plugin
    at l (plugin.ts:12:11)
    at Object.use (runtime-core.esm-bundler.js:3812:21)
    at main.js?t=1651515259176:29:5
```

My /services/ability.js file looks like the following (based on [these instructions](https://casl.js.org/v5/en/guide/intro#conditions)):

```
import { defineAbility } from '@casl/ability';

export default (user) => defineAbility((can) => {

  can('read', 'Article');

  if (user.isLoggedIn) {
    can('update', 'Article', { authorId: user.id });
    can('create', 'Comment');
    can('update', 'Comment', { authorId: user.id });
  }

});
```

What am I doing wrong?

It's very unclear to me what ability.js should actually contain. Any guidance would be appreciated. Thanks!

**Comment by stalniy** [comment]
Please try to find an answer on SO, gutter or in casl examples/docs. I do not provide answers to support questions. 

Close as this is not an issue with casl and current issue doesn’t follow provided template
