### ISSUE TITLE
Better documention and examples  on store ability templates

### ISSUE THREAD

**Issue by Spartano** [stalniy/casl#62]
Hi,

I am trying to create a CRUD manager that allows me to create custom template rule but

i am having problems understanding how to write conditions inside the schema. Using you're example i want to add a condition that says "id" === '123'

`{
    "actions": ["read", "update"],
    "subject": "User",
    "conditions": {
      "id": "123"
    }
  }`

when i try to do `ability.can("read", "User", {user.id: "125"})` it returns `true`.

Can you explain  more  what conditions inside the schema does.

**Comment by stalniy** [comment]
You don't correctly use `Ability.can`. 

In your case you need to write `ability.can('read', new User({ user_id: 126 }))`. Also check typescript definitions to understand method signatures - https://github.com/stalniy/casl/blob/master/packages/casl-ability/index.d.ts.
Please see this comment for details https://github.com/stalniy/casl/issues/59#issuecomment-387288324

**P.S.**: looks like that for some reason people are mixing `AbilityBuilder.can` and `Ability.can` :) Probably I need to add runtime warning

**Comment by stalniy** [comment]
feel free to ask questions in gitter chat

**Comment by stalniy** [comment]
Also check this link to documentation https://stalniy.github.io/casl/abilities/2017/07/21/check-abilities.html

**Comment by stalniy** [comment]
duplicates #59

**Comment by sonphnt** [comment]
I still dont get how it works. Without conditions, you can do this.
ability.can("read", "User")

With conditions, you do this 
ability.can('read', new User({ user_id: 126 }))

Where is "User" string parameter?

What if we have 2 User classes called User1, User2, How can you distinguish between User1, and User2 class in this call
ability.can('read', new User1({ user_id: 126 })) =>>> new User1 or new User2

Thanks

**Comment by stalniy** [comment]
Check this docs https://stalniy.github.io/casl/v4/en/guide/subject-type-detection

Casl detects subject type from subject instances. That’s why you don’t need to pass the User by yourself. 

This prevents errors like passing type `User` and object which actually represents something else (e.g., article)

**Comment by sonphnt** [comment]
Thanks @stalniy . I love the way with subject-type then I can apply a dynamic model from JSON without creating a class for it..
this.$ability.can("manage", subject("Article", { author_id: 1 }))

**Comment by dhcmega** [comment]
Hi
I'm running into the same problem (I guess)
Is this possible?

$can(['update', 'delete'], 'Post')

to check if a user can update or delete a post?
The use case is a situation in which a menu option holds more options nested.
So in order to show the parent button "Handle Posts" that has 2 options "Update" and "Delete" I need to check for any of those abilities first in order to show the "Handle Posts" button, and then, check for each of the nested options: "Update" and "Delete".

Thanks!
