### ISSUE TITLE
Can't use Prisma package if built into custom directory

### ISSUE THREAD

**Issue by Faithfinder** [stalniy/casl#621]
Here's a repro of type errors with Prisma 3.14 (same with 3.0.2)
https://codesandbox.io/s/cranky-frog-dy6nfq?file=/src/index.ts

No typesafety for conditions with `AbilityBuilder` and type error with raw rules.

I believe the reason is that typings depend on types from `@prisma/client`, but that doesn't exist in all the prisma usage scenarios

**Comment by stalniy** [comment]
How can you use prisma without @prisma/client? 

When you define prisma schema you need to generate corresponding stuff out of it (i.e., client)

**Comment by Faithfinder** [comment]
Like this: https://www.prisma.io/docs/concepts/components/prisma-client/working-with-prismaclient/generating-prisma-client#using-a-custom-output-path

And then in a monorepo you can pack it up in a package to use the same client with multiple backend servers and import it like `@yourcompany/yourpackage` like my company does

**Comment by stalniy** [comment]
Any thoughts on how to support this?

I see 2 options:
1. Additional cli script to run which will replace `@prisma/client` with specified dependency
2. Fake dependency which can be provided on package manager level `”@casl/prisma-client”: “npm:@prisma/client@^3.0.0”`

The 2nd option adds less magic but I don’t know how to provide default value. Very likely it’s impossible and will force everybody to do it.

**Comment by Faithfinder** [comment]
Personally I'd be happy if CASL had no dependency on my types at all, making Prisma just an alternative query language with an added perk of being able to get a `Where` condition from an ability instance. We already need to pass model names to create the ability, according to the docs:

```ts
type AppAbility = PrismaAbility<[string, Subjects<{
  User: User,
  Post: Post
}>]>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
```

I don't mind doing it to `accessibleBy` as well, like:

```ts
export const appAccessibleBy = (ability: AppAbility) => accessibleBy<PrismaModels>(ability)
```

I imagine with some TS wizardry it might even be possible to make `accessibleBy` typed strongly just by inferring stuff from `ability` instance

**Comment by d-tw** [comment]
I'm also encountering this issue. I agree that there shouldn't be a direct dependency on the locally generated Prisma client - this limits the use of CASL in monorepo contexts where there may be multiple generated prisma clients (using the previously mentioned custom output paths).

As a workaround, I'm currently using/abusing the Typescript `paths` compiler option to remap `@prisma/client` to the custom output path.

```json
{
    "compilerOptions": {
        "paths": {
            "@prisma/client": ["my/path/to/prisma.ts"]
        }
    }
}
```

There may be reasons to not do this, but I haven't encountered them yet. YMMV.

**Comment by stalniy** [comment]
I need this direct dependency in order to provide proper typesafety for conditions you specify during Ability definition. There is no other way to get all that except of reimplementing the whole prisma model generation logic which I will need to keep in sync :) 

However, there might be solution - prisma generator. I could write custom generator for casl like this:

```prisma
generator casl {
  provider = "@casl/prisma/generator"
  clientPath = "path/to/your/custom/prisma/folder" # defaults to @prisma/client
}
```

**Comment by Faithfinder** [comment]
Sounds worth exploring to me.

**Comment by stalniy** [comment]
Please check @casl/prisma@2.0.0-alpha.3 and let me know whether it works for you.

**Comment by Faithfinder** [comment]
In a week :) On vacation now, no access to anything where I can code.

**Comment by stalniy** [comment]
any updates in this regard?

**Comment by Faithfinder** [comment]
Yup! Sorry for not trying it out earlier. The adapter generation needs a bit more in our scenario, where prisma client is treated as a separate package.

* It needs an `output` setting, similarly to the normal `client` generator. In our setup (a [`rushjs`](https://rushjs.io/) monorepo) `node_modules` are treated as sacred, and nothing should change their contents but the package manager, so creating a `.prisma` folder is a no-no.
* `clientLib` would better be `clientLocation` rather, and instead of a library package name, should expect a path to the generated client, relative to the schema (e.g same thing you put into `output` of the normal `client`.
* The generated file should probably be a `.d.ts`. After the client is generated the package is considered "built", so we need the result of TS compilation - `.js` and `.d.ts` files.

**Comment by stalniy** [comment]
after playing around with generator, everything becomes very complicated. That's why I decided to push this complexity back to user-land, at least for now :) 

But I also implemented a way to use custom generated prisma client (some manual work is required on your side) -> https://casl.js.org/v6/en/package/casl-prisma#custom-prisma-client-output-path

Fixed in casl/prisma@1.2.0

**Comment by stalniy** [comment]
let me know if there are any issues you faced with that solution

**Comment by ravi0lii** [comment]
Hey,
I noticed one issue here. I see that you deprecated `PrismaAbility` in favor of `createPrismaAbility` in the same commit as you added the support custom generated prisma clients. You also added additional documentation for the custom generation of the client, but the old documentation regarding the usage of `@casl/prisma` is now out of date, since the `PrismaAbility` is still used there. I think that the documentation should be updated as well since this is quite confusing now

**Comment by ZenSoftware** [comment]
For anyone who was curious as to how to utilize the new `createPrismaAbility` function while waiting on the docs to to be updated, this is how we are creating our user's Casl ability in our [NestJS app](https://github.com/ZenSoftware/zen).  So far it is working very well.  Thanks @stalniy!

```ts
import { AbilityBuilder, createMongoAbility } from '@casl/ability';
import { createPrismaAbility } from '@casl/prisma';
import { Injectable } from '@nestjs/common';
import { Action } from '@zen/api-interfaces';

import { RequestUser } from '../models/request-user';
import { PrismaSubjects } from './generated';

/** @description A union of subjects to extend the ability beyond just Prisma models */
export type ExtendedSubjects = 'all' | 'Sample';

@Injectable()
export class CaslAbilityFactory {
  async createAbility(user: RequestUser) {
    const prismaRules = this.#prismaRules(user);
    const extendedRules = this.#extendedRules(user);
    return createMongoAbility(prismaRules.concat(extendedRules as any));
  }

  #prismaRules(user: RequestUser) {
    const { can, cannot, rules } = new AbilityBuilder(createPrismaAbility);

    // Customize user permissions over Prisma models here

    return rules;
  }

  #extendedRules(user: RequestUser) {
    const { can, cannot, rules } = new AbilityBuilder(
      createMongoAbility<[Action, ExtendedSubjects | PrismaSubjects]>
    );

    if (user.roles.includes('Super')) {
      can('manage', 'all');
    }

    // Customize extended user permissions here
    can('read', 'Sample');

    return rules;
  }
}
```

**Comment by stalniy** [comment]
In short, I plan to replace specific classes of abilities with corresponding factory functions. So eventually there is only 1 Ability class and several factory functions. 

Type specific classes were not needed from the beginning but at that time I’ve just couldn’t come with a better solution. 

 I’ll keep `PrismaAbility` as an interface but class itself will gone. The only thing it did was passing predefined conditionsMatcher to PureAbility class. Currently it feels like there is a lack of helper interfaces/types to work with ability factory functions. I’ll improve that  
 
Sorry guys for the docs. Writing docs is much longer then writing implementation :)

**Comment by stalniy** [comment]
updated docs
