### ISSUE TITLE
Destructuring of `ability` not working

### ISSUE THREAD

**Issue by antoineviscardi** [stalniy/casl#622]
**Describe the bug**

When destructuring `ability`, the `can` function throws an error.

**To Reproduce**

```javascript
import { defineAbility } from "@casl/ability";

const ability = defineAbility((can) => {
  can("read", "article");
});

function checkAbilityA(ability) {
  return ability.can("read", "article");
}

function checkAbilityB({ can }) {  // <- destructuring here
  return can("read", "article");
}

console.log("checkAbilityA: ", checkAbilityA(ability)); // Good
console.log("checkAbilityB: ", checkAbilityB(ability)); // Error!!
```

**Expected behavior**

Destructuring should work. That is, there should be no difference in behavior between a call to `checkAbilityA` and `checkAbilityB`. 

**Interactive example** (optional, but highly desirable)

https://codesandbox.io/embed/casl-ability-debug-forked-9z657k

**CASL Version**

`@casl/ability` - v5.4.3

**Environment**:

```
❯ node -v
v16.13.1
```

**Comment by stalniy** [comment]
It has never been supposed to work this way. You can always bind any method in userland. 

Close as it’s not a bug
