### ISSUE TITLE
React 18 support

### ISSUE THREAD

**Issue by Fallup** [stalniy/casl#623]
Would it be possible to get React 18 into peer dependencies in `@casl/react` ? Currently only 15, 16 and 17 are supported.
```
"react": "^15.0.0 || ^16.0.0 || ^17.0.0"
```
Or are there any breaking changes in v18 which would prevent this quick change?

**Comment by jitbasemartin** [comment]
A PR exists but it seems failing: https://github.com/stalniy/casl/pull/620

**Comment by daviddyess** [comment]
It's failing for code coverage unrelated to the actual PR.

**Comment by stalniy** [comment]
Hi guys,

don’t have laptop yet to publish new versions. I’ll try to automate this through gha later. Currently, we have some issues with gasoline in Ukraine, so I can’t get home. 

But hopefully I’ll do this  on the next week

**Comment by stalniy** [comment]
published `@casl/react@3.0.0`
