### ISSUE TITLE
TypeScript errors upgrading CASL Prisma from 1.0.1 to 1.0.2

### ISSUE THREAD

**Issue by maxh** [stalniy/casl#627]
**Describe the bug**
We're having troubling upgrading CASL Prisma from 1.0.1 to 1.0.2. Our approach follows the example in the documentation here: 

https://www.npmjs.com/package/@casl/prisma

So I'm not sure what we are doing wrong or if this is a bug.

**To Reproduce**

Prisma file.
```prisma
model DbMessage {
  tenantQid String @map(name: "tenant_qid")
  qid       String @id

  topic       String
  authorQid   String @map(name: "author_qid")

  @@map(name: "message")
}

```

Ability file:

```typescript
type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      Message: DbMessage;
    }>,
  ]
>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
const { can, cannot, build } = new AbilityBuilder(AppAbility);
can('read', 'Message', { tenantQid: 'example-qid' });
```

TypeScript error:
```
TS2769: No overload matches this call.   Overload 1 of 2, '(action: string | string[], subject: "Message" | "Message"[], conditions?: undefined): RuleBuilder<AppAbility>', gave the following error.     Argument of type '{ tenantQid: string; }' is not assignable to parameter of type 'undefined'.   Overload 2 of 2, '(action: string | string[], subject: "Message" | "Message"[], fields?: string | string[] | undefined, conditions?: undefined): RuleBuilder<AppAbility>', gave the following error.     Argument of type '{ tenantQid: string; }' is not assignable to parameter of type 'string | string[] | undefined'.       Object literal may only specify known properties, and 'tenantQid' does not exist in type 'string[]'.
```
<img width="875" alt="image" src="https://user-images.githubusercontent.com/1289501/171244482-dbd950f9-56c7-42a6-b1d7-85781bec1df1.png">

**Expected behavior**
Expected no TypeScript error.

**Versions**

`@casl/ability` - 5.4.4
`@casl/prisma` - 1.0.2
`typescript` - 4.6.4

**Environment**:
Node, TypeScript

**Comment by stalniy** [comment]
Thank you for the report. I’ll take a look at it today

**Comment by stalniy** [comment]
Not related. You cannot name your models differently, it should be this:

```ts
type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      DbMessage: DbMessage; // <-- here we map model name to its actual TS representation, prisma doesn't provide this info
    }>,
  ]
>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
const { can, cannot, build } = new AbilityBuilder(AppAbility);
can('read', 'Message', { tenantQid: 'example-qid' });

```

**Comment by maxh** [comment]
Thanks. For what it's worth, renaming the subject doesn't seem to have fixed it for us:

```
import { DbMessage, Prisma } from 'generated/prisma/client';

type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      DbMessage: DbMessage;
    }>,
  ]
>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
const { can, cannot, build } = new AbilityBuilder(AppAbility);
can('read', 'DbMessage', { tenantQid: 'example-qid' });
```

<img width="1180" alt="image" src="https://user-images.githubusercontent.com/1289501/185463955-00cd801e-3303-43f7-9d0d-43103a425453.png">

**Comment by stalniy** [comment]
Strange because I’m my test app it works. I’ll pot a link tomorrow

**Comment by maxh** [comment]
Cool. One thing I was wondering is whether the `@@map(name: "message")` could have any impact? Maybe not.

I was able to it to work like this:

![image](https://user-images.githubusercontent.com/1289501/185500064-0cc5284f-baf0-4fec-8320-acb160c282d5.png)

```ts
type PrismaWhereInput = Prisma.DbMessageWhereInput;
type CaslWhereInput = PrismaQuery<Model<DbMessage, 'DbMessage'>>;

const assertWhere = (where: PrismaWhereInput): CaslWhereInput => {
  return where as CaslWhereInput;
};

type AppAbility = PrismaAbility<
  [
    string,
    Subjects<{
      DbMessage: DbMessage;
    }>,
  ]
>;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
const { can, cannot, build } = new AbilityBuilder(AppAbility);
can('read', 'DbMessage', assertWhere({ tenantQid: 'abc' }));
```

**Comment by maxh** [comment]
More generally though (and I can file a separate feature request for this if you prefer), I think in our case it would be best if we could have the subject name decoupled from the Prisma model name. We have two levels of abstraction:

- Prisma models (conforms 1:1 with relational table schema)
- DTO entities (conforms to coherent conceptual domain entity, a mental model we share with business stakeholders)

Sometimes a single DTO entity is persisted in several tables.

To me, the authorization rules are a domain concept and should live at the DTO entity layer rather than the persistence layer. Of course, we need to resolve rule conditions to db where clauses. And I believe that Prisma is trying to blur the lines between these to obviate the need for a separate DTO layer. The separation helps with modularity, etc.

So I think we may end up pursuing an approach like this in any case, though curious your thoughts:

```ts
type PrismaWhereInput = Prisma.DbMessageWhereInput;
type CaslWhereInput = PrismaQuery<Model<DbMessage, 'DbMessage'>>;

const assertWhere = (where: PrismaWhereInput): CaslWhereInput => {
  return where as CaslWhereInput;
};

type AppAbility = PrismaAbility<
    [
      string,
      Subjects<{
        [EntityType.MESSAGE]: AbilitySubject<MessageDto>;
      }>,
    ]
    >;
const AppAbility = PrismaAbility as AbilityClass<AppAbility>;
const { can, cannot, build } = new AbilityBuilder(AppAbility);
can(OperationType.READ, EntityType.MESSAGE, assertWhere({ tenantQid: 'example-qid' }));
```
