### ISSUE TITLE
TS invalid declaration of arguments for function can

### ISSUE THREAD

**Issue by websitevirtuoso** [stalniy/casl#629]
**Describe the bug**
TS invalid declaration of arguments for function can

**To Reproduce**
1. 
File ability to set up all abilities
https://gist.github.com/websitevirtuoso/1f3dad8446642fa0462a1589aed54a1c
2. Usage abilities inside components 'Composition API'
```
<script setup lang="ts">
import { useAbility } from '@casl/vue';
const { can } = useAbility();
console.log(can('country.view'))
</script>
```

My console log return correct behavior and everything works but TS blames that function "can" expect 2 or 3 arguments
![image](https://user-images.githubusercontent.com/5112918/172085808-2f627991-90b7-4eac-91a3-2fd117fd990b.png)

**Expected behavior**
Expect to not have TS error when use function "can" with 1 argument

**CASL Version**

`@casl/ability` - 5.4.4
`@casl/vue` - 2.1.2

**Environment**:

TS version

Solution
Change type in file
node_modules/@casl/ability/dist/types/types.d.ts

Line 20: 
**current version**
export declare type CanParameters<T extends Abilities, IncludeField extends boolean = true> = AbilityParameters<T, T extends AbilityTuple ? IncludeField extends true ? (action: T[0], subject: T[1], field?: string) => 0 : (action: T[0], subject: T[1]) => 0 : never, (action: Extract<T, string>) => 0>;

**expected version**
export declare type CanParameters<T extends Abilities, IncludeField extends boolean = true> = AbilityParameters<T, T extends AbilityTuple ? IncludeField extends true ? (action: T[0], subject**?**: T[1], field?: string) => 0 : (action: T[0], subject**?**: T[1]) => 0 : never, (action: Extract<T, string>) => 0>;

**Comment by stalniy** [comment]
By design, read https://casl.js.org/v5/en/cookbook/claim-authorization on how to configure Ability to use single action parameter

and “TypeScript support” section in https://casl.js.org/v5/en/package/casl-vue to see how to provide correspondence ding generic to useAbility
