### ISSUE TITLE
Restricting fields access not working?

### ISSUE THREAD

**Issue by farzindev** [stalniy/casl#633]
**Describe the bug**
Admin should be able to update only ROLE and ACTIVE fields.

**To Reproduce**
```
function defineAdminRules({ can, cannot }, user) {
	can('read', 'User');
	can('update', 'User', ['role', 'active']);
}
```
and I'm checking it with this in my controller:

```
ForbiddenError.from(req.ability).throwUnlessCan('update', doc);
```

**Expected behavior**
Not be able to update fields that are not specified!

**Environment**:
`@casl/ability` 
`@casl/mongoose`
Nodejs, Mongoose, Express

**Comment by stalniy** [comment]
By design. Please read the docs about checking field access
