### ISSUE TITLE
Mongoose with Typescript without “extends Document”

### ISSUE THREAD

**Issue by qqilihq** [stalniy/casl#634]
**Is your feature request related to a problem? Please describe.**

Mongoose recommends not to use `extends Document`. [According to them](https://mongoosejs.com/docs/typescript.html#using-extends-document), support for this will be dropped in the next major release and they claim that there are “major performance issues” (unfortunately without going into any details at all -- I would only guess they mean for running `tsc`?). 

> We strongly recommend against using this approach, its support will be dropped in the next major version as it causes major performance issues. Many Mongoose TypeScript codebases use the below approach.

However …

I have tried picking up their new recommendations and going without the `extends Document`. I've hit already several walls there, finally getting it work, but I'm now kind of stuck properly combining this with `@casl/mongoose`, which seems to assume the “deprecated” `extends Document` principle.

**Describe the solution you'd like**

Has anybody successfully managed to use `@casl/mongoose` with the new Mongoose-recommended structure? I would highly appreciate some sample code for that. Is it possible at all, or would the `@casl/mongoose` plugin need to be updated?

**Comment by qqilihq** [comment]
I think I figured it out using some workarounds. Would you be interested in a MR which addresses this on the plugin side?

**Comment by stalniy** [comment]
Hey,

thank you for the issue. Yes, please send a PR with required changes. I’ll check and release new version

**Comment by qqilihq** [comment]
Hi @stalniy -- the details turned out more fiddly than I actually expected, but I think I have a working version now. Any feedback welcome!
