### ISSUE TITLE
RawRuleOf and ForcedSubject are not working

### ISSUE THREAD

**Issue by hmarcelodn** [stalniy/casl#635]
**Describe the bug**
I am trying to read permissions from the database using the provided example but it has problems with RawRuleOF
`node_modules/@casl/ability"' has no exported member 'RawRuleOf'. Did you mean 'RawRule'? (2724)`
`node_modules/@casl/ability"' has no exported member 'ForcedSubject'. (2305)`

**To Reproduce**
Import the following line in your appAbility.ts service

`import { Ability, RawRuleOf, ForcedSubject } from '@casl/ability';`

**Expected behavior**
Be able to use RawRuleOf and ForcedSubject

**Interactive example** (optional, but highly desirable)
NA

**CASL Version**

`@casl/ability` ^5.4.4

**Environment**:
v16.10.0

**Comment by stalniy** [comment]
It works https://codesandbox.io/s/vibrant-volhard-z3ygmw?file=/src/index.ts

Not a casl issue
