### ISSUE TITLE
Need help to allow user read only their own datas

### ISSUE THREAD

**Issue by mi-mazouz** [stalniy/casl#640]
Hello!

I just want to build a simple authorization logic, I want my user able to only access to their own data to inject correct content in my database query for example:

```
// Defined Availability
can('read', 'user', { id: 1 })
```

will inject into my database query something like:
```
const query = {}

if (can('read', 'user')) {
 query.where = {}
} else if (can('read', 'user', { id: userId })) {
 query.where = { id: userId }
}

return findAll(query);
```

In that case my query will look like ```{ where: {} }```

After reading the documentation from https://casl.js.org/v5/en/guide/intro#checking-logic I can understand that it is not possible but I want to make sure there is no other way to handle this case.

Thanks for your help

**Comment by stalniy** [comment]
Sorry but issue tracker for issues only. There are multiple examples for different frameworks. You can find answer on the Internet or ask for help on stackoverflow. 


close as there is no issue

**Comment by mi-mazouz** [comment]
I understand your point and I will ask it on stackoverflow but please don't say I didn't search the answer on the internet before asking here...

**Comment by stalniy** [comment]
I don’t say you haven’t searched but I say that there are examples and you can find answer on your question. When I have time I’ll make a FAQ and clearly explain this case

thanks you for the question
