### ISSUE TITLE
Add documentation for NestJs

### ISSUE THREAD

**Issue by gyanendrasng** [stalniy/casl#646]
Hi,
Recently frameworks like NestJs have become quite popular, The NestJs documentation provides example for integration with CASL but it doesn't uses any db(Specifically ORM's) , which is not going to be the case in any real world scenario.

NestJS CASL implementation documentation here-
https://docs.nestjs.com/security/authorization#integrating-casl

I was thinking to add the documentation for NestJS with different ORM, I can help with Nest and Prisma, but I don't have much knowledge of TypeORM and wont be able to contribute to that. 

I have some doubts regarding Prisma implementation as well, if someone can help me I can make a PR for the documentation. 

Here is the incomplete implementation for the integration, I have taken reference from both NestJs documentation and @casl/prisma documentation.

Links for the both  (NestJs link is same as the one mentioned above) -
https://docs.nestjs.com/security/authorization#integrating-casl
https://casl.js.org/v6/en/package/casl-prisma

<img width="1440" alt="Screenshot 2022-07-30 at 6 38 52 PM" src="https://user-images.githubusercontent.com/63923409/181915756-0935eb7a-70af-4dd6-afa1-58212d8bb2c8.png">

How does the idea sound to you guys??

**Comment by gyanendrasng** [comment]
I have a question that in PrismaAbility the first array value is string, why is it there(how does that help) , maybe a silly question, but thanks for anyone helping me.

**Comment by stalniy** [comment]
Hi there. 

Thank you for the proposal. Looks like docs for cookbook section. Example with prisma is ok. You can then add it to https://github.com/stalniy/casl-examples

I’d suggest to implement blog post API. There is one for expresses. You can use it as a reference. It’s good to follow the same url structure so they can be replaceable between each other and it will be possible to reuse it with existing UI example

**Comment by stalniy** [comment]
The 1st parameter is string in order make restrictions on action parameter using literal at types

**Comment by stalniy** [comment]
Also check this cookbook guide https://casl.js.org/v6/en/cookbook/intro

**Comment by gyanendrasng** [comment]
Sure, also wanted to point that in website if we do cant open a url in new tab when we do cmd(or ctrl for windows)+left click

**Comment by gyanendrasng** [comment]
I will make a PR in 2 weeks maybe, quite busy right now

**Comment by stalniy** [comment]
There are also integration tests for API -> https://github.com/stalniy/casl-examples/tree/master/packages/express-blog/spec

which can be used to validate new implementation

**Comment by stalniy** [comment]
hey @gyanendrasng 

do you still plan to contribute?

**Comment by stalniy** [comment]
As there is no any progress in this regard I close the issue. Feel free to contribute if you still want
