### ISSUE TITLE
[casl-react] Missing aliases on TypeScript

### ISSUE THREAD

**Issue by melkir** [stalniy/casl#65]
Hello,
I was trying to follow the readme but it seems that there's not type aliases for

> I (do is an alias) - name of the action and field
> a (on, of, this are aliases) - checked subject

https://github.com/stalniy/casl/blob/c411e2ca1a9b49a0b6bf312a125545e1f7bb457f/packages/casl-react/index.d.ts#L5

Type checking is ok with "do" and "on"

**Comment by stalniy** [comment]
Yes, my bad. Forgot to update types. I’ll fix this in a week. Currently on vacation :)

**Comment by melkir** [comment]
Thank you stalniy :) 
Enjoy your vacation!
