### ISSUE TITLE
v4 Debugging/Testing docs are incorrect

### ISSUE THREAD

**Issue by marr** [stalniy/casl#659]
The v4 docs contain some example tests at the bottom that do not pass: https://casl.js.org/v4/en/advanced/debugging-testing
```
it('can read non private article', () => {
  expect(ability.can('read', 'Article')).to.be.true;
  expect(ability.can('read', article({ title: 'test' }))).to.be.true;
  expect(ability.can('read', article({ title: 'test', private: false }))).to.be.true;
  expect(ability.can('read', article({ private: true }))).to.be.false;
});
```
The `expect(ability.can('read', article({ title: 'test' }))).to.be.true;` line actually does not pass. I expected that to pass along with the author I'm guessing, but maybe there is more effort needed to make that a passing test?

I'm just learning how to use this library, and thought this may be a good thing to figure out.

**Comment by stalniy** [comment]
Ok makes sense. Thanks for catching. It looks like I wrote tests for prev rules ) need to adjust docs

**Comment by marr** [comment]
Thanks @stalniy,

I wonder if there is some way to use the alternative rule and have the test pass. Is there a way to declare: "private is optional, and only a `true` value would prevent reading"?

**Comment by stalniy** [comment]
yes, you can do this either by using inverted rule (by forbidding `private = true` explicitly) or you can use `$in` operator:

```
can('read', 'Article', { private: { $in: [false, undefined] } })
```
