### ISSUE TITLE
Is there a plan to update angular to v14 ?

### ISSUE THREAD

**Issue by floross** [stalniy/casl#661]
Hi, when you try to use @casl/angular with angular@v14 you get a npm error during the package installation cause of the casl peerDependencies

**To Reproduce**
1. `npm i @casl/angular @angular/core@14`

**Expected behavior**
It should not fail the installation

**CASL Version**

`@casl/angular` - 7.0.1

**Comment by stalniy** [comment]
PRs are welcome

**Comment by stalniy** [comment]
published in @casl/angular@8.0.0
