### ISSUE TITLE
Repair for correct ESM with TS

### ISSUE THREAD

**Issue by adostal** [stalniy/casl#668]
Hello, I try switch from CommonJS to ESM Modules.
I have a problem with your library. For proper functioning, it would be necessary to add the **types** attribute to **exports** in **package.json**

Example **@casl/ability**

From:
```json
"exports": {
    ".": {
      "import": "./dist/es6m/index.mjs",
      "require": "./dist/es6c/index.js"
    }
```

To:
```json
  "exports": {
    ".": {
      "types": "./dist/types/index.d.ts",
      "import": "./dist/es6m/index.mjs",
      "require": "./dist/es6c/index.js"
    },
```

**Comment by stalniy** [comment]
Can you do PR for all packages?
