### ISSUE TITLE
Probleme with can/cannot condition

### ISSUE THREAD

**Issue by kfachas** [stalniy/casl#669]
Hello, i dont understand how works condition on can/cannot method,
`
can(Action.Update, SlotEntity, {
        'company.permissions.client.user.id': user.id,
      });
`
So result : "Cannot execute "update" on "SlotEntity"" :(
SlotEntity has a relation with a company, company has a relation with permissions etc.. and i need to check if user is able to update slot by his permissions from his client relation. 
How can I make this condition work?
Thanks in advance

**Comment by stalniy** [comment]
This is a question not a bug or feature request. Use stackoverflow
