### ISSUE TITLE
[Prisma][Typescript] Action - Subject type dependency does not work with PrismaAbility

### ISSUE THREAD

**Issue by adri1wald** [stalniy/casl#675]
**Describe the bug**

As described in https://casl.js.org/v5/en/advanced/typescript#safer-permissions-inference, one can define dependencies between actions and subjects. Typescript is then able to infer the allowed actions given a subject.

I verified this works with the normal `Ability` generic. But trying it with the `PrismaAbility` generic, the action type for any specific subject is inferred as the union over the action type of *all* subjects.

**To Reproduce**
1. Setup a project with prisma and casl
2. Add at least two models
3. Assign different actions to each model
4. See that action type is not correctly inferred in the `can` method

```ts
import { User, Resource } from '@prisma/client'
import { AbilityClass, AbilityBuilder } from '@casl/ability'
import { PrismaAbility, Subjects } from '@casl/prisma'

type CRUD = 'create' | 'read' | 'update' | 'delete'

type Abilities =
  | ['read', Subjects<{ User: User }>]
  | [CRUD, Subjects<{ Resource: Resource }>]

export type AppAbility = PrismaAbility<Abilities>
export const AppAbility = PrismaAbility as AbilityClass<AppAbility>

const { can, build } = new AbilityBuilder(AppAbility)

can('create', 'User')
```

<img width="579" alt="Screenshot 2022-09-04 at 03 01 01" src="https://user-images.githubusercontent.com/34961840/188293981-0691f3b5-33dd-45cd-99ae-f8622b06b7a2.png">

**Expected behavior**

It seems the issue can be fixed by changing the way `ExtendedAbilityTuple` is defined in `/packages/casl-prisma/src/PrismaAbility.ts`. I got inspiration from https://stackoverflow.com/questions/68323706/transform-all-elements-of-union-type.
```ts
type ExtendedAbilityTuple<T extends AbilityTuple> = T extends any ? [T[0], 'all' | T[1]] : never;
```

<img width="617" alt="Screenshot 2022-09-04 at 03 01 25" src="https://user-images.githubusercontent.com/34961840/188293983-1250aae0-dd42-47b5-9edb-2b39a6488f0c.png">
 
If you are happy with this solution, I'd gladly open a PR with this change :)

**CASL Version**

`@casl/ability` - v 6.0.0
`@casl/prisma` - v 1.0.4

**Environment**:

`typescript` - v 4.7.4

**Comment by stalniy** [comment]
fixed in @casl/prisma@1.3.1
