### ISSUE TITLE
ts error "An argument for 'defaultValue' was not provided" when defining AbilityContext for contextual Can with @casl/react 

### ISSUE THREAD

**Issue by miller-productions** [stalniy/casl#682]
**Describe the bug**
ts error when trying to use casl/react for the first time and following instructions in doc.

Unable to make it past the first steps when following this example in the doc.

Setting up `createContextualCan`

```
import { createContext } from "react";
import { createContextualCan } from "@casl/react";

export const AbilityContext = createContext();  <---- ERROR HERE
export const Can = createContextualCan(AbilityContext.Consumer);
```

TS ERROR: `Expected 1 arguments, but got 0.` `An argument for 'defaultValue' was not provided" when defining export const AbilityContext = createContext();`

**To Reproduce**

Visit this section in the doc and attempt to follow it: https://casl.js.org/v5/en/package/casl-react#bind-can-to-a-particular-ability-instance

**Expected behavior**
Unsure - should probably not experience errors when following the instructions in the doc.

**CASL Version**

`@casl/ability: "^6.1.1"`
`@casl/react: "^3.1.0"`

**Environment**:

`typescript: "^4.7.3"`
`react": "^18.2.0"`

**Comment by okomarov** [comment]
@miller-productions This has nothing to do with CASL although for completeness of the example here's a quick search that might fix your needs: https://stackoverflow.com/questions/63193891/createcontext-doesnt-accept-defaultvalue

**Comment by stalniy** [comment]
Most examples are written in JS not TS -> 
<img width="796" alt="Screenshot 2022-09-18 at 17 20 36" src="https://user-images.githubusercontent.com/1159966/190911815-c950012b-8ad6-4171-8a67-00d08b2659f5.png">


You can take a look at https://github.com/stalniy/casl-examples for some TS examples and working apps

**Comment by miller-productions** [comment]
Understood.

Thanks for the links @stalniy and @okomarov. Very helpful and got me up and running. 🙂

Just thought I'd let you know about this one in case others experience it also in the future.

CASL is excellent BTW - was my first time using it yesterday and once it is all configured and up and running, it's so much more intuitive and well-organised when it comes to implementing access control.

Love your work guys 💙

**Comment by ldgmaia** [comment]
I know this issue is closed, but since I couldn't find in the documentation how to fix this using TypeScript, I will post the solution I am using. I hope it's OK.

```js
import { AnyAbility } from '@casl/ability'
import { createContextualCan } from '@casl/react'
import { createContext } from 'react'

export const AbilityContext = createContext<AnyAbility | undefined>(undefined)
export const Can = createContextualCan(
    AbilityContext.Consumer as React.Consumer<AnyAbility>
)
```

**Comment by Sujit0807** [comment]
> I know this issue is closed, but since I couldn't find in the documentation how to fix this using TypeScript, I will post the solution I am using. I hope it's OK.
> 
> This solution is based on CASL V6.
> 
> ```js
> import { AnyAbility, PureAbility } from '@casl/ability'
> import { createContextualCan } from '@casl/react'
> import { createContext } from 'react'
> 
> export const AbilityContext = createContext<AnyAbility>(new PureAbility())
> export const Can = createContextualCan(
>     AbilityContext.Consumer as React.Consumer<AnyAbility>
> )
> ```

Instead of using `undefined`, we can use an instance of `PureAbility`
