### ISSUE TITLE
Handle accessibleBy in `update` queries (supported in latest prisma)

### ISSUE THREAD

**Issue by ambiguous48** [stalniy/casl#693]
**Is your feature request related to a problem? Please describe.**
In the [latest prisma version 4.5](https://github.com/prisma/prisma/releases/tag/4.5.0), a new [feature](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#filter-on-non-unique-fields-with-userwhereuniqueinput) was added that synergizes well with `@casl/prisma`. We can now use `accessibleBy` for `update` operations, like so:

```ts
const updateablePost = await prisma.post.update({
  where: {
    id: 5,
    AND: accessibleBy(ability).Post,
  },
  data: {
    content: "Incredible new story",
    version: { increment: 1 },
  },
});
```

Currently, if no record is found, this will return error code [P2025](https://www.prisma.io/docs/reference/api-reference/error-reference#p2025):

>  "An operation failed because it depends on one or more records that were required but not found. {cause}"

This behavior is a bit different than using accessibleBy in a `findMany`, which throws a `ForbiddenError` when a user doesn't have ability to access any posts.

**Describe the solution you'd like**
Consider making both behaviors identical.

**Additional context** (optional)
[One](https://www.prisma.io/docs/reference/api-reference/prisma-client-reference#permission-checks) more example

**Comment by stalniy** [comment]
Hi,

Can you please describe actual/expected results to understand the issue? Because currently I don't understand what is wrong.

casl throws ForbiddenError only in case it 100% sure that there is no permissions for that particular action/subjectType

**Comment by ambiguous48** [comment]
When I first read [this](https://github.com/stalniy/casl/blob/25b1b8ef60db8856f3bdf4512abe814e8e6899dc/packages/casl-prisma/README.md?plain=1#L78), I was under the impression `accessibleBy` would also throw a ForbiddenError any time the findMany call returned 0 results.

> casl throws ForbiddenError only in case it 100% sure that there is no permissions **for that particular action/subjectType**

This makes much more sense.
