### ISSUE TITLE
Hosting expired dearrussian.wtf

### ISSUE THREAD

**Issue by Tusko** [stalniy/casl#703]
please check the hosting of the website
https://dearrussian.wtf

<img width="361" alt="CleanShot 2022-11-21 at 13 35 51@2x" src="https://user-images.githubusercontent.com/2039259/203041519-03533c5c-c259-4378-b894-67087972a5fe.png">

**Comment by stalniy** [comment]
updated, thank you!

**Comment by ztefn** [comment]
@stalniy domain itself appears to be completely expired currently.
