### ISSUE TITLE
@casl/angular does not support Angular 15

### ISSUE THREAD

**Issue by xbisa** [stalniy/casl#710]
npm ERR! Found: @angular/core@15.0.3
npm ERR! node_modules/@angular/core
npm ERR!   @angular/core@"^15.0.1" from the root project
npm ERR!
npm ERR! Could not resolve dependency:
npm ERR! peer @angular/core@"^14.0.0" from @casl/angular@8.1.0
npm ERR! node_modules/@casl/angular
npm ERR!   @casl/angular@"*" from the root project

Are there plans to support it?

**Comment by xbisa** [comment]
PR against `master`?

**Comment by stalniy** [comment]
Yes

**Comment by xbisa** [comment]
I couldn't run npm install. What version of node and NPM are you using?

**Comment by vmikhav** [comment]
@stalniy here is the existing PR https://github.com/stalniy/casl/pull/704

**Comment by stalniy** [comment]
It doesn't pass ci

**Comment by xbisa** [comment]
This is duplicate.
