### ISSUE TITLE
Allowing access to any field except one

### ISSUE THREAD

**Issue by SwenVogel** [stalniy/casl#722]
Hi,

i would like to know whether it is possible to permit access to any field except one.

For example:
**A user can update all fields of an article except the id.** 

It would be really nice to use some kind of negation operator like in the following library: [onury/accesscontrol](https://github.com/onury/accesscontrol#checking-permissions-and-filtering-attributes)

Translated to CASL: 
`can('update', 'Article', ['**', '!id']);
`

**Comment by stalniy** [comment]
This should help

```ts
can('update', 'Article')
cannot('update', 'Article', ['id'])
```
