### ISSUE TITLE
'Ability' is deprecated (Angular 15 (@casl/angular: 8.2.0) - CASL ability (@casl/ability: 6.3.3))

### ISSUE THREAD

**Issue by camilathomasi** [stalniy/casl#726]
Hello!

My application uses angular 15, and I am using the following versions of CASL:

   "@casl/ability": "^6.3.3",
   "@casl/angular": "^8.2.0"

I am following this doc https://casl.js.org/v6/en/package/casl-angular, but I have this situation:

1. Ability configuration 

![image](https://user-images.githubusercontent.com/63751286/212348602-6abc3a59-3807-4b67-847d-73f017de33b4.png)

![image](https://user-images.githubusercontent.com/63751286/212348729-6ddc6f74-a8d9-4dd8-b2a8-f196c64d8de0.png)

![image](https://user-images.githubusercontent.com/63751286/212348922-c4a3148d-fbdc-48aa-9c87-1f2429df376a.png)

What version of @casl/ability"  should I use in this case? Should I need to change the setup on providers?

**CASL Version**

"@casl/ability": "6.3.3",
"@casl/angular": "8.2.0",

**Environment**:
 "@angular/core": "15.1.0",
  "typescript": "4.9.4",  
  node: v18.12.1

Thanks in advance!

**Comment by stalniy** [comment]
JsDoc tells you what to do. https://github.com/stalniy/casl/blob/master/packages/casl-ability/src/Ability.ts#L9
