### ISSUE TITLE
Question: 

### ISSUE THREAD

**Issue by jbblt** [stalniy/casl#727]
Hello, I would like to add this new Can : `can(AuthAction.UPDATE, AuthSubject.SCOPE, (scope: Scope) => scope.audit.createdBy === user.name);`

and now i have this issue : 
![Capture d’écran, le 2023-01-20 à 16 55 43](https://user-images.githubusercontent.com/65205828/213812360-611cdc69-ea24-43fc-959e-83d75657c3f3.png)

Any ideas ? 

```
const { can, rules } = new AbilityBuilder<PossibleAbilities>(PureAbility);
 can(AuthAction.UPDATE, AuthSubject.SCOPE, (scope: Scope) => scope.audit.createdBy === user.name)
return rules;

 ability.update(defineAbilityFor(currentUser));
```

**Comment by stalniy** [comment]
Read docs more carefully. Works as expected. Here for example - https://casl.js.org/v6/en/advanced/customize-ability

**Comment by jbblt** [comment]
in your exemple you propose,( the doc) it use $nor , we don't use custom opérator, we just need to check if an Object with field: user is the same as our User logged.

we did exacly that => 
![Capture d’écran, le 2023-01-24 à 13 16 50](https://user-images.githubusercontent.com/65205828/214375336-bb23386b-8e77-471e-a8fa-085ef82c34df.png)
