### ISSUE TITLE
Forbidden Error: Cannot execute "read" on "Project"

### ISSUE THREAD

**Issue by rajkanase** [stalniy/casl#730]
**Describe the bug**
I have updated my all mongoose related packages. More specifically @casl/ability (from 5.2.2 to 6.3.2), @casl/mongoose (5.0.0 to 7.1.2), @nestjs/mongoose(8.0.0 to 9.2.1), mongoose (5.12.15 to 6.7.2) from then onwards I have started facing **_Forbidden Error: Cannot execute "read" on "Project"_** for regular user role and it is working fine for admin role (may be bcz the subject for admin role is 'all')

**To Reproduce**

```
if (user.roles.includes('NASP_ADMIN')) { 
      can(Action.Read, 'all'); //if I am changing 'all' with 'Project' then same error here also
      can(Action.Update, 'Project', ['isReviewed']);
      can(Action.Delete, 'all');
    } else {
      can(Action.Read, 'Project', { createdBy: user.sub }); // read-only access to own projects
      can(Action.Update, 'Project', ['name', 'projectDescription'], {
        createdBy: user.sub,
      });
}
```

```
return build({
  detectSubjectType: (item) => {
    return item.constructor as ExtractSubjectType<AppSubjects>
  },
  fieldMatcher: fieldMatcher
});
```

**Expected behavior**
This is still working fine if I switch back to previous commit.

**CASL Version**

`@casl/ability` - v6.3.2
`@casl/mongoose` - v7.1.2
`@nestjs/mongoose` - v9.1.2
`@mongoose` - v6.7.2

**Environment**:
node js - v16.13.2

@stalniy

**Comment by rajkanase** [comment]
@stalniy

**Comment by stalniy** [comment]
You say that subject type is a constructor but in definition you pass strings. That’s why you get errors. Either pass models in rules definition or use `constructor.modelName` in detectSuvjectType. 

Let me know if it helped

**Comment by rajkanase** [comment]
> You say that subject type is a constructor but in definition you pass strings. That’s why you get errors. Either pass models in rules definition or use `constructor.modelName` in detectSuvjectType.
> 
> Let me know if it helped

Yeah, when I changed the strings to model name at least I am getting the records now, but the issue remains is 
either `accessibleBy(ability)`  OR `can(Action.Read, Project, { createdBy: user.sub })` seems not working because I am getting all the records.

**Comment by rajkanase** [comment]
Hi @stalniy 
I am facing weird scenario
Everything works perfect till @casl/mongoose@7.0.0 but when I upgrade to 7.1.0 and above, it doesn't throw any error but the abilities doesn't work it seems. For USER role also it returns all the records. 
```
// casl/mongoose@7.0.0
    if (user.roles.includes('NASP_ADMIN')) {
      can(Action.Read, 'all');
      can(Action.Update, 'Project', ['isReviewed']);
      can(Action.Delete, 'all');
    } else {
      can(Action.Read, 'Project', { createdBy: user.sub }); // read-only access to own projects
      can(Action.Update, 'Project', ['name', 'projectDescription'], {
        createdBy: user.sub,
      });
    }
```

```
//casl/mongoose@7.1.0
    let Project: AccessibleRecordModel<Project>;
    if (user.roles.includes('NASP_ADMIN')) {
      can(Action.Read, 'all');
      can(Action.Update, Project, ['isReviewed']);
      can(Action.Delete, 'all');
    } else {
      can(Action.Read, Project, { createdBy: user.sub }); // read-only access to own projects
      can(Action.Update, Project, ['name', 'projectDescription'], {
        createdBy: user.sub,
      });
    }

    return build({
      // Read https://casl.js.org/v5/en/guide/subject-type-detection#use-classes-as-subject-types for details
      detectSubjectType: (item) => item.constructor as ExtractSubjectType<AppSubjects>,
    });

```

Expected Behavior - 
For USER role - it should show only the records created by himself.
For ADMIN role - it should show all the records.

**Comment by stalniy** [comment]
checked the latest casl with your setup and it works as expected. Query results are different per different roles. So, if you receive the same records the issue is somewhere else:

https://gist.github.com/stalniy/19afe0a73c62e6c64d13ca9ae45cee89

**Comment by rajkanase** [comment]
> checked the latest casl with your setup and it works as expected. Query results are different per different roles. So, if you receive the same records the issue is somewhere else:
> 
> https://gist.github.com/stalniy/19afe0a73c62e6c64d13ca9ae45cee89

@stalniy
Your example works absolutely fine and I know we have already closed the discussion but 

what if I don't want to go with classname? can we still use string as subject type instead of constructor??
