### ISSUE TITLE
ESM build with `node16` module resolver fails to build

### ISSUE THREAD

**Issue by egmacke** [stalniy/casl#734]
**Describe the bug**

Original post on stackoverflow: https://stackoverflow.com/questions/75372705/casljs-with-esm-node16

Using @casl/ability in a (typescript) project which is built using ESM causes errors regarding missing types.

`node_modules/@casl/ability/dist/types/types.d.ts(1,32): error TS7016: Could not find a declaration file for module '@ucast/mongo2js'.`

**To Reproduce**

1. Create a new ESM typescript project, with `@casl/ability` as a dependency.
2. Set tsconfig.json `moduleResolution` to `node16`

Attempt to build project.

**Expected behavior**

Project should build and run successfully, without the type error.

**Interactive example** (optional, but highly desirable)

Git repo: https://github.com/egmacke/casljs-esm-node16
Repl: https://replit.com/@egmacke/casljs-esm-node16

**Comment by stalniy** [comment]
probably this is due to missing 

```ts

      "types": "./dist/types/index.d.ts",
```

**Comment by stalniy** [comment]
npm update @ucast/mong2js and it should update your package-lock.json. Updated corresponding dependencies

**Comment by egmacke** [comment]
@stalniy that seems to have sorted it - thank you!
