### ISSUE TITLE
Ability' is deprecated.

### ISSUE THREAD

**Issue by memory660** [stalniy/casl#737]
**Describe the bug**

Ability' is deprecated.

**To Reproduce**

npm install @casl/angular @casl/ability
and use it

**Expected behavior**

**Interactive example** (optional, but highly desirable)

the solution for it not to be depreciated

**CASL Version**

    "@casl/ability": "^6.3.3",
    "@casl/angular": "^8.2.0",
    "@angular/common": "^15.0.0",

**Environment**:

npm 8.11.0

**Comment by TheDelta** [comment]
See https://github.com/stalniy/casl/discussions/724
Documentation is most likely outdated.

**Comment by stalniy** [comment]
Please read this thread - https://github.com/stalniy/casl/discussions/724
