### ISSUE TITLE
MongoAbility and custom conditions

### ISSUE THREAD

**Issue by kratker** [stalniy/casl#738]
Hi, thanks for the great library!

I have a problem with MongoAbility and mongo ids vs string ids.

I need to compare `{_id: userId}` where _id is a mongoose ObjectId and userId is a string.

 I cannot do `toString()` on a left hand side of a condition. If I use `new ObjectId(userId)` it won't work, because these will be two different objects with different references.

Is there any way for me to implement a function condition in mongo ability? Or is there any other way?

Thanks!

**Comment by kratker** [comment]
Hi, I have managed to use the $where condition after customizing the ability as per doc  [here](https://casl.js.org/v5/en/advanced/customize-ability)

Thanks!

**Comment by stalniy** [comment]
casl uses @ucast/mongo2js and it can compare objects that implement `toJSON` function. So, if `ObjectId().toJSON()` returns primitive value (e.g., string), it can compare ObjectId to string and also can compare ObjectIds: https://github.com/stalniy/ucast/blob/master/packages/mongo2js/src/factory.ts#L38

**Comment by kratker** [comment]
I see, all works now without the need for $where. Thanks a lot for a prompt response!
