### ISSUE TITLE
casl/mongoose - getFields() should also get the virtual properties

### ISSUE THREAD

**Issue by jsanchezba** [stalniy/casl#739]
**Is your feature request related to a problem? Please describe.**
When using mongoose with the accessibleFieldsPlugin(), the virtual properties are not available. Currently i'm registering the plugin on the models instead of globally, but i have to repeat this on every model.

**Describe the solution you'd like**
Can something like this be implemented as default on the getFields() function?
```javascript
const accessibleFields = accessibleFieldsPlugin(schema, {
    getFields(schema) {
        const paths = Object.keys(schema.paths)
        const virtuals = Object.keys(schema.virtuals)
        return [...paths, ...virtuals]
    },
})
```

**Comment by stalniy** [comment]
Looks like ALL_FIELDS are cached per plug-in call but instead should be cached per schema - https://github.com/stalniy/casl/blob/master/packages/casl-mongoose/src/accessible_fields.ts#L50

**Comment by stalniy** [comment]
PR is welcome

**Comment by jsanchezba** [comment]
It's working globally after a second attempt, guess i was missing something:

```javascript
mongoose.plugin(accessibleFieldsPlugin, {
    getFields: (schema: Record<string, unknown>) =>
        Object.keys({
            ...(schema as { paths: object }).paths,
            ...(schema as { virtuals: object }).virtuals,
        }),
})
```
