### ISSUE TITLE
[Question] How do I get the prisma query object without using accessibleBy?

### ISSUE THREAD

**Issue by joshualcdev** [stalniy/casl#758]
I'm using a third-party library and Nest.js and therefore cannot use accessibleBy() as I do not have access to the ability builder.

I noticed the @casl/prisma package exports a `prismaQuery` function. I'm able to get the conditions AST using the third-party library like this:

```
async findAll(
    @CaslConditions() conditions: ConditionsProxy,
  ) {

  const condition = conditions.toAst();
```

Am I supposed to pass this to `prismaQuery`? The following code seems to work, however, I'm not sure how to get the prisma query object from it. 

```
prismaQuery(condition)
```

Any help would be appreciated!

**Comment by stalniy** [comment]
Hi 

Have no idea what libraries you are using :) So, please ask this question on stackoverflow

**Comment by stalniy** [comment]
just exposed `WhereInput<T>` this is what `accessibleBy(ability).Post` returns (i.e., `WhereInput<Post>`)
