### ISSUE TITLE
ability.can requires third parameters to be string and subject() doesn't work

### ISSUE THREAD

**Issue by hathinhks** [stalniy/casl#759]
**Describe the bug**
I try to setup my casl factory with @casl/prisma as close to the documentation at https://casl.js.org/v6/en/package/casl-prisma as possible, like this:

![image](https://user-images.githubusercontent.com/52519166/235348543-c2e3ac13-d238-448a-b2dd-8726515f51f2.png)

Then when I try to use it in another module, typescript errors are thrown. In this image you can see it requires the third parameter to be a string:
![image](https://user-images.githubusercontent.com/52519166/235348600-5050151f-32e4-43ee-a7d2-d0adc380c356.png)
![image](https://user-images.githubusercontent.com/52519166/235348619-e69c7f2f-4d90-4ac0-a548-7882849fd0e4.png)

And when I use the subject() method from @casl/ability:
![image](https://user-images.githubusercontent.com/52519166/235348439-8cba7b23-3ec8-404d-9ccf-bf8541be7f31.png)
![image](https://user-images.githubusercontent.com/52519166/235348578-8a375a4f-e1c6-4e6c-a5b1-ca3207050dbf.png)

Same for when I try to setup using createMongoAbility instead of prisma:
![image](https://user-images.githubusercontent.com/52519166/235348415-a8912de8-c994-4118-b451-e80e6c16dea5.png)
![image](https://user-images.githubusercontent.com/52519166/235348456-a72b392e-4955-4ba1-bfa3-db9916f0757e.png)

**To Reproduce**
1. Configure casl ability factory as images shown above
2. Try using ability.can in another file

**Expected behavior**
I can pass a PrismaQuery object in the third parameter normally, or pass subject() function result in the second parameter.

**Interactive example** (optional, but highly desirable)
provide a link to the example from http://repl.it/, https://codesandbox.io/ or similar, so we can quickly test and provide feedback. Otherwise

**CASL Version**
 "@casl/ability": "^6.5.0"
    "@casl/prisma": "^1.4.0"

**Environment**:

**Comment by stalniy** [comment]
It seems it's not a CASL issue. I've just finished example of CASL + Fastify + Prisma and all was good. Please check it here -> https://github.com/stalniy/casl-examples/tree/master/packages/fastify-prisma-blog

**Comment by hathinhks** [comment]
But the error is from calling method on the casl ability object, so how is that not a CASL issue? My application is a nestjs project by the way.

**Comment by stalniy** [comment]
```ts
const aNumber: string = 1; // ts error
```

Who's that error above? :) 

You are asking me to look in your code, understand details and help to solve the issue. I'm pretty sure this is not casl issue because:
1. There are tests that validate all different cases
2. I've just finished example which works and has no unexpected behavior. You can check it and understand how your code is different from the example and fix it yourelf

**Comment by hathinhks** [comment]
@stalniy it'd be easier if the error comes from my code, but it's from the ability.can() method from casl package. As I understand the parameters that ability.can() accepts are defined in within these lines of code, am I correct?
```javascript
type AppAbility = PureAbility<
  [
    string,
    (
      | Subjects<{
        User: User
      }>
      | 'all' 
    ),
  ],
  PrismaQuery
>

const { can, cannot, build } = new AbilityBuilder<AppAbility>(createPrismaAbility)
```
The first parameters to PureAbility is the type of the action (in this case string) and the accepted subject, and the second is the condition object, which in this case is PrismaQuery. There's not a place that defining a third 'string' type parameter.
My code looks almost identical to the documentation, so that's why I don't understand the reason behind the error.

**Comment by coolbho3k** [comment]
@hathinhks I just figured this out, the error message is rather opaque. The Prisma example is not TypeScript in the docs so it doesn't work as-is.

The object passed into `subject` needs to be of type `User`. You need the `as User` as follows:

`ability.can(Action.Read, subject('User', { role: UserRole.admin } as User));`

**Comment by coolbho3k** [comment]
Actually scratch what I just said You may be running into this: https://github.com/stalniy/casl/issues/778
