### ISSUE TITLE
Accessing nested fields does not work as described in the docs

### ISSUE THREAD

**Issue by IfyNdu** [stalniy/casl#769]
Hello!

I have the following `TypeORM` entity types

```ts
type User = {
    id: string;
    name: string;
};

type Organisation = {
    id: string;
};

type OrganisationMember = {
    id: string;
    organisation: Organisation;
    user: User;
};

type Scan = {
    id: string;
    organisationMember: OrganisationMember;
};

```
According to the docs i have tried accessing organisation id with dot notation like so `organisationMember.organisation.id`  and `organisationMember.organisation` but all to no avail.

```ts
const organisationMember = {
    organisation: { id: 'awesome-organisation-id' }
};

can('read', Scan, {
    isActive: true,
    'organisationMember.organisation.id': organisationMember.organisation.id, // TS: Error ''organisationMember.organisation.id'' does not exist in type 'MongoQuery<Scan>'
});

can('read', Scan, {
    isActive: true,
    'organisationMember.organisation': { // TS:Error ''organisationMember.organisation'' does not exist in type 'MongoQuery<Scan>'
        id: organisationMember.organisation.id,
    },
});
```
Here is a sample `Scan` subject I am testing against
```ts
const scan = {
    id: 'awesome-scan-id',
    organisationMember: {
        id: 'awesome-organisation-member-id',
        organisation: { id: 'awesome-organisation-id' },
        user: { id: 'awesome-user-id' }
    }
}; // This is an actual Scan subject instead of some object type.
```
Is there something I am missing?

**Comment by stalniy** [comment]
flattening doesn’t work out of the Box. You need to provide custom generic type in `can`

check it here for TS usage: https://casl.js.org/v6/en/advanced/typescript#nested-fields-with-dot-notation

**Comment by stalniy** [comment]
This can be automated with template literal types but some day in the future :)

**Comment by IfyNdu** [comment]
Thanks for your reply. it still doesn't work quite as expected for me. Might I add that my types `Organisation. OrganisationMember, User and Scan` are classes (`typeorm` entities). I am also using `InferSubjects` on those classes.
