### ISSUE TITLE
Subject from @casl/ability need a full object with prisma

### ISSUE THREAD

**Issue by shankiflang** [stalniy/casl#778]
**Describe the bug**
I created my prisma subjects in my factory
![image](https://github.com/stalniy/casl/assets/32774804/089e8989-740d-4281-b119-b19957f18397)

Here is how a Community is defined :
![image](https://github.com/stalniy/casl/assets/32774804/6c7daa10-200f-4a09-8444-c261725dcb6a)

When I call my guard, I only have the id of my Community. I'd like to do 
```ability.can(requiredRole.action, subject('Community', { id: '1' })```.

But I get the following error:
```The type '{ id: string; } & ForcedSubject<"Community">' doesn't have the following properties of the 'Community' type: projectId, type, permalink, name and 6 others.```

Is there a way to check just one attribute?

**CASL Version**

"@casl/ability": "^6.5.0",
"@casl/prisma": "^1.4.0",

**Environment**:
Nodejs 18

**Comment by the-me-0** [comment]
Hello shankiflang !
Sadly, not that I know about. When I searched for checking the ability of a user to create an entity I found this example :
https://github.com/stalniy/casl-examples/blob/5bacb73dff14546dd88de8acccbe493068943ad6/packages/fastify-prisma-blog/src/modules/articles/routes.ts#L81
For testing if a user can create something before such thing being created, I had to create a "copy" of what the object would look like after creation, test it using ability.can method, and only then create the real thing.

I did not find any solution to test a single attribute, so each time it happened in my code I created a minimal object to test the ability on. Maybe someone will come with a better solution, but I would advice you doing that for now !

PS : I tried using the third parameter (field) on the can method while giving only an id to the subject helper, but typescript blocks you from going further as it asks for the type to be fullfilled, and an id isn't enough. I guess you can test your ability on a single attribute of the objects, but still all object properties must be defined.

**Comment by shankiflang** [comment]
> Hello shankiflang ! Sadly, not that I know about. When I searched for checking the ability of a user to create an entity I found this example : https://github.com/stalniy/casl-examples/blob/5bacb73dff14546dd88de8acccbe493068943ad6/packages/fastify-prisma-blog/src/modules/articles/routes.ts#L81 For testing if a user can create something before such thing being created, I had to create a "copy" of what the object would look like after creation, test it using ability.can method, and only then create the real thing.
> 
> I did not find any solution to test a single attribute, so each time it happened in my code I created a minimal object to test the ability on. Maybe someone will come with a better solution, but I would advice you doing that for now !
> 
> PS : I tried using the third parameter (field) on the can method while giving only an id to the subject helper, but typescript blocks you from going further as it asks for the type to be fullfilled, and an id isn't enough. I guess you can test your ability on a single attribute of the objects, but still all object properties must be defined.

as I haven't found a solution yet, I've just recovered my Community from the database in my guard. I now have the whole object. The only problem is that I need to have a switch() for each resource that my API owns.

**Comment by stalniy** [comment]
https://github.com/stalniy/casl-examples/tree/master/packages/fastify-prisma-blog

Did you check this example?

**Comment by stalniy** [comment]
Close because it works as expected. 

If you pass partial object, which doesn’t exist in db, there is no way to ensure that conditions in rules will match 

feel free to comment if you have more questions or suggestions
