### ISSUE TITLE
question: using accessibleBy(ability) in prisma create query

### ISSUE THREAD

**Issue by x3malmusic** [stalniy/casl#786]
hello everyone, so i installed casl/prisma package and it seems to work well when you need to get data from database, but what about other operations? for example create, i want casl ability to be able to prevent users from creating entities if user not allowed to do so, but there's no documentation on how to do this or if it even possible to do

so the question is pretty straight forward, is casl/prisma able to prevent users from creating entities?

**Comment by stalniy** [comment]
https://github.com/stalniy/casl-examples

There are many examples. Please pick one you like and check it
