### ISSUE TITLE
$ability in component template is not updated after I update it in a mixin

### ISSUE THREAD

**Issue by meidikawardana** [stalniy/casl#796]
**Describe the bug**
I'm using `$ability` in a component template:
```
<!-- src/modules/Sep/pages/SepsGrid.vue -->
<template>
  <!-- ... -->
  <my-create-button v-show='$ability.can("create", "Sep")' id='btn-sep-create' tooltip='Create SEP' @click='onCreate' />
  <!-- ... -->
</template>
```

The `$ability` is from a mixin:
```
<!-- src/modules/Sep/pages/SepsGrid.vue -->
<!-- ... -->
<script lang="ts">
import { defineComponent } from 'vue'
import AbilityState from 'src/modules/Application/mixins/AbilityState'

export default defineComponent({
  name: 'ServicesExecutionPlan',
  mixins: [AbilityState],
  // ...
})
</script>
```

And the mixin injects `$ability` from `ABILITY_TOKEN`, and updates it later when it is mounted:
```
// src/modules/Application/mixins/AbilityState.ts
import defineAbilityFor from 'src/app/abilities/abilities'
import { ABILITY_TOKEN } from '@casl/vue'
import GuestUser from 'src/app/configs/GuestUser.json'

export default {
  inject: {
    $ability: { from: ABILITY_TOKEN }
  },
  // ...
  mounted() {
    // ...
    this.setUpdatePermissions()
  },
  methods: {
    async setUpdatePermissions() {
      // ...
      this.$ability = (defineAbilityFor(GuestUser))
      // ...
    },
    // ...
  }
}
```

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
The ability is defined in `abilities.ts`:
```
// src/app/abilities/abilities.ts
import { AbilityBuilder, AnyMongoAbility, createMongoAbility } from '@casl/ability'
import { hasRole } from 'src/modules/Application/actions/HasRole'
import { IUser } from 'src/modules/Application/models/User/UserInterface'

export default function defineAbilityFor(user: IUser): AnyMongoAbility {
  const roles = user.roles
  const { can, build } = new AbilityBuilder(createMongoAbility)

  if (hasRole(roles, 'admin')) {
    console.log('Admin User')
    can('manage', 'all')
    return build()
  }

  if (hasRole(roles, 'guest')) {
    console.log('Guest User')
    can(['create', 'read', 'update'], 'Hazob', { created_by: 'Meidika', status_id: 1 })
  }

  can('read', 'all')
  return build()
}
```

2. How do you check abilities
The ability is initialized in one of quasar boot files, `permissions.js`:
```
// src/boot/permissions.js
import { abilitiesPlugin } from '@casl/vue'
import { boot } from 'quasar/wrappers'
import defineAbilityFor from 'src/app/abilities/abilities'
import AdminUser from 'src/app/configs/AdminUser.json'

export default boot(async ({ app }) => {
  app.use(abilitiesPlugin, defineAbilityFor(AdminUser))
})
```

**Expected behavior**
When the mixin updates the `$ability`, the `$ability` in the component template should be updated automatically.

**Interactive example** (optional, but highly desirable)
_provide a link to the example from http://repl.it/, https://codesandbox.io/ or similar, so we can quickly test and provide feedback._
I have prepared a github repo and import it to codesandbox, but I need your github email so you can open the codesandbox project. Please let me know your email by emailing it to jdeep555.mw@gmail.com.
The github repo: https://github.com/meidikawardana/casl-sample
The codesandbox: https://codesandbox.io/p/github/meidikawardana/casl-sample/main
* Instruction for codesandbox: after you send me your github email, I will add it to the sandbox ASAP so you can open it. Then when you open it, open a new terminal in it & run: `yarn start`. The app should then start immediately

Otherwise

**CASL Version**

`@casl/ability` - v6.5.0
`@casl/vue` - v2.2.1

**Environment**:

node v16.15.0

**Comment by stalniy** [comment]
I don’t think this should be expected to work. you update reference to ability but instead your mixin should call `.update()` method on $ability

**Comment by meidikawardana** [comment]
Thanks, @stalniy for the reply. I have updated [the sample](https://github.com/meidikawardana/casl-sample). I call `.update()` method, then I realize when I assigned the ability initially with GuestUser which doesn't have `can('manage', 'all')`, then update the ability to AdminUser which have `can('manage', 'all')`, it won't work. In the sample, the create button doesn't show up. I think this is a bug, so please add `bug` label to this issue. Or do you want me to create another issue for this?

**Comment by stalniy** [comment]
This is very unlikely a bug. 

 You passed Ability instance inside `update` method but that method expects to receive an array of rules.

**Comment by meidikawardana** [comment]
Thank you @stalniy . I know now, that I made a mistake. This is not a bug, but a mistake on my end
