### ISSUE TITLE
Overriding via provide in a plugin causes strange behavior in templates

### ISSUE THREAD

**Issue by illegalnumbers** [stalniy/casl#804]
**Describe the bug**
If you `provide` an ability through a plugin defined after the vue plugin is setup you will get undetermined behavior including the following error every time you try to use `can` on it's own in a template:
```
index.mjs:1 Uncaught (in promise) TypeError: "this.relevantRuleFor" is not a function
```

**To Reproduce**
1. Define any ability function
2. create a plugin to inject abilities based on application changes after the vue plugin is installed such as 
```
install(app, config){
 watch(thing, () => {
   app.provide(ABILITY_TOKEN, defineAbility(thing.value)
 })
}
```
4. How do you check abilities

const { can } = useAbility()

When you use `can` in the template you'll get the above error for any check. But, if you do the same check by doing
```
const ability = useAbility()
```
in the script setup for the component it will be valid e.g `ability.can('do', 'Thing')`

but you can't pass or proxy `can` into the template without explicitly taking all the parameters from the template.

if you do do this, it seems the ability is fine. e.g.
```
<template>
<div v-if="can('view', 'Thing')> hi </div>
</template>
<script setup>
const ability = useAbility()
const can = (perm, thing) => { return ability.can(perm, thing) }
</script>
```

**Expected behavior**
The page doesnt error 

**CASL Version**

`@casl/ability` - 6.5.0
`@casl/vue` - 2.2.1

**Environment**:

Chrome, latest
Typescript, 4.9.5

**Comment by stalniy** [comment]
Hello,

are you sure you can change providers inside watch? I don't think it's a valid syntax. Instead of providing a new ability on every `thing` change, you need to update existing ability

**Comment by stalniy** [comment]
`inject` inside child components happens at setup time. and setup is called (very likely) once per component, until it's destroyed.

**Comment by illegalnumbers** [comment]
Yes it is valid syntax to change providers in a watch inside a plugin.

**Comment by illegalnumbers** [comment]
> Hello,
> 
> are you sure you can change providers inside watch? I don't think it's a valid syntax. Instead of providing a new ability on every `thing` change, you need to update existing ability

Yes it is valid syntax to change providers in a watch inside a plugin.

**Comment by stalniy** [comment]
Can you prepare some live/github example for me to look into this issue?

**Comment by stalniy** [comment]
By the way, I can’t find in official docs that multiple calls of provide will provide a new value. That say if you want reactivity - use refs.

**Comment by illegalnumbers** [comment]
> Can you prepare some live/github example for me to look into this issue?

Yea I'll see if I can find some time next week to try to reproduce it in a gist or something.

> By the way, I can’t find in official docs that multiple calls of provide will provide a new value. That say if you want reactivity - use refs.

It does though. You can test this by using any app level or component level provide with the same injection token twice.

I was actually thinking about using the ability in a ref just in our own plugin and providing reactivity through that. I was curious why this wasn't the route taken with the current plugin?

**Comment by illegalnumbers** [comment]
In fact, since we check in `usAbility` for the ability to be null before injecting it in the component I don't know how the error I'm running into actually happens https://github.com/stalniy/casl/blob/master/packages/casl-vue/src/useAbility.ts#L10

**Comment by illegalnumbers** [comment]
[Here](https://replit.com/join/sycxudqbhb-ben-nelson) is a REPL that demonstrates some of the behavior that I'm talking about. Here it is nondeterministic to get the `relevantRuleFor` error but it does show some of what I'm talking about. In this particular instance it is caused because the ability defined by the library isn't a `ref` so the page isn't reactive to the changes made for the abiility. But for instances like this, where a reactive change needs to happen to define the `can` provided by the composable how are we supposed to update this so that we can use `can` and the `Can` component with the library? I have to update the ability defined for the current user on the fly for a couple of reasons (permissions change arbitrarily, not defined by login on a login component specifically) so I need to be able to update this ability at will using the watch.

Should I just use a `ref` and essentially write my own plugin and not use the casl defined one? How would I be able to use the `Can` component in that instance?

**Comment by stalniy** [comment]
Have you seen this example https://github.com/stalniy/casl-examples/tree/master/packages/vue-blog ?

**Comment by illegalnumbers** [comment]
Yea, we don't use Vuex so the state modifications don't apply and won't fix the issue for us unfortunately :/ we were thinking about plugging in Pinia at some point but it's far off.

**Comment by illegalnumbers** [comment]
Typically in vue plugins you provide a ref, I'm confused as to why you built in something different for this plugin? The reactivity problems would be eliminated by using one and I think it'd still be compatible with vuex, etc.

**Comment by stalniy** [comment]
It has nothing to do to vuex. Plug-in is built in the same way it was built for Vue2. You don’t need ref to track ability changes. Reactivity is built in inside Ability

**Comment by illegalnumbers** [comment]
Can you show me an example of that? [This](https://github.com/stalniy/casl-examples/blob/master/packages/vue-blog/src/store/ability.js#L6) in your vuex code is providing the reactivity and updates for your abilities.

**Comment by illegalnumbers** [comment]
The stored ability is a singleton in that example which gets pulled from and updated by vuex. If you just pull the ability elsewhere as I've done in the example I've shown the updates don't properly propagate.

**Comment by illegalnumbers** [comment]
Unless you use the composable for the `provide` function which updates the ability within the plugin. Which should be the same behavior I have in the plugin I've written above, I don't understand how it's not updating.

**Comment by stalniy** [comment]
I looked into the code and now I understand the reason. You did manually provide ability instance via your custom plugin or whatever but instead you should use `abilitiesPlugin` from `@casl/vue` which makes ability to be reactive under the hood -> https://github.com/stalniy/casl/blob/master/packages/casl-vue/src/plugin.ts#L15

If you do this, you will no longer see the error. The error happens because `can` and `cannot` are not bound to `this` by default and only plugin binds them.

**Comment by stalniy** [comment]
<img width="745" alt="Screenshot 2023-09-18 at 15 19 34" src="https://github.com/stalniy/casl/assets/1159966/626a2ed1-449d-4153-8a77-707275f5c4a0">

When I try to setup example similar to yours, I see 2 issues:
1. Vue warns that ABILITY_TOKEN has been provided and will be overwritten.
2. Child template is not re-rendered when `app.provide` provides a new instance of Ability. That means, `provide` is not reactive and when you provide new value, new also need to force re-render the whole app.

What you should do instead is this:

 
<img width="619" alt="Screenshot 2023-09-18 at 15 27 20" src="https://github.com/stalniy/casl/assets/1159966/2719e04e-3697-4468-98c2-ff3ce0f88556">
<img width="629" alt="Screenshot 2023-09-18 at 15 27 30" src="https://github.com/stalniy/casl/assets/1159966/d0afceef-f081-47e2-bea5-af3768f4310e">

Then reactivity works as expected and you can do this in components:

<img width="638" alt="Screenshot 2023-09-18 at 15 29 03" src="https://github.com/stalniy/casl/assets/1159966/dffedfaa-726d-4223-a75d-79fdaba8033f">

**Comment by stalniy** [comment]
You can use any ability instance. It can also be PureAbility. This is just what my fingers now to type ))

let me know if you will have further questions
