### ISSUE TITLE
CASL 

### ISSUE THREAD

**Issue by akhilmhdh** [stalniy/casl#810]
**Describe the bug**
I was using CASL and noticied this particular behavoir. 

Is this expected? Can someone please explain why this is returning true? I do feel this is should not be the expected  behavoir. 

```
var ability = require("@casl/ability")
const { can, cannot, build } = new ability.AbilityBuilder(ability.createMongoAbility);
can('delete', 'Post', { published: true });

const a = build();
  
 a.can('delete', "Post"); // return true
```

**Expected behavior**
Feels it should return false

**CASL Version**

`@casl/ability` - latest

**Environment**:
Run Kit: https://npm.runkit.com/%40casl%2Fability

**Comment by stalniy** [comment]
Hello, 

I’m just curious)) when will people start to read documentation? 

The answer is here - https://casl.js.org/v6/en/guide/intro#checking-logic

**Comment by akhilmhdh** [comment]
Hey @stalniy 

Haha😅i do refer the doc. But damn, i forgot about that section completely. My bad.

Thank you again for your time and for this library.
