### ISSUE TITLE
@casl/angular AblePipe and AblePurePipe typing not working in Angular template

### ISSUE THREAD

**Issue by odermattaccso** [stalniy/casl#829]
**Describe the bug**
I'm using @casl/angular in a project and ran into an issue where the `able` and `ablePure` pipes don't seem to correctly get picked up by the Angular compiler. Hovering over the pipe won't show any information about the pipe nor can you navigate to its definition by CTRL/CMD+Click'ing on the `able` pipe.

This might also be the cause why I can't seem to override the typings for `AblePipe` and `AblePurePipe` using declaration merging (but I also don't really understand declaration merging so that issue might just be me 😔).

**To Reproduce**
I created a reproduction repository using the latest Angular version here:
https://github.com/odermattaccso/casl-angular-able-pipe-untyped/tree/main

Please have a look at [app.component.html](https://github.com/odermattaccso/casl-angular-able-pipe-untyped/blob/main/src/app/app.component.html) and the usage of `able` pipe. Code completion seems to offer "able" as well as "ablePure" but hovering over them doesn't show any typing information and trying to navigate to their definition doesn't work.

Looking at the definition of [casl-angular/src/pipes.ts](https://github.com/stalniy/casl/blob/master/packages/casl-angular/src/pipes.ts) remembers me of a similar issue I had when I put my type generics inside the class definition like so: `export class OrderPipe<T, U extends OrderBy> implements PipeTransform {....}`

Have a look at [order.pipe.ts](https://github.com/odermattaccso/casl-angular-able-pipe-untyped/blob/main/src/app/pipes/order.pipe.ts) for a possible alternative, moving the type generics into the `transform` method of the pipe.

**Expected behavior**
Hovering over `able` and `ablePure` will result in typing information to be shown and allows navigating to its definition.

**CASL Version**
`@casl/ability@6.5.0`
`@casl/angular@8.2.1`

**Environment**:
Issue comes up inside VS Code using `typescript@5.1.6` (but probably any TypeScript version will do)

**Comment by odermattaccso** [comment]
I just realised that my alternative like in [order.pipe.ts](https://github.com/odermattaccso/casl-angular-able-pipe-untyped/blob/main/src/app/pipes/order.pipe.ts) doesn't really work for a definition of `T` like in `AblePipe<T extends AnyAbility>` because it is also used in class property definitions as well as inside the constructor injection.

Not sure how this can be solved then...

**Comment by stalniy** [comment]
I think it's much easier/better to use `AbilityService` and pass `can` method to template through `can`, Then there is no need to have magic with this pipes. Eventually, I think I will remove them
