### ISSUE TITLE
How to use accessibleFieldsBy without Mongoose (with basic Mondodb driver)

### ISSUE THREAD

**Issue by thomasdvd** [stalniy/casl#837]
**Is your feature request related to a problem? Please describe.**
I would like to use accessible by plugins with native MongoDB Adapter

**Describe the solution you'd like**
Import accessibleFieldsBy and other helper utility functions directly like accessibleBy

**Comment by stalniy** [comment]
For now there is no way to do this. Just use permittedFieldsBy helper from @casl/ability/extra

**Comment by stalniy** [comment]
Fixed in #880

**Comment by stalniy** [comment]
released in @casl/mongoose@8.0.0
