### ISSUE TITLE
Automatic filter selection through `accessibleBy` ?

### ISSUE THREAD

**Issue by wassgha** [stalniy/casl#85]
First of all, amazing job on this middleware! I am currently using it in my project, however, I find myself always doing something like

```javascript
Posts.find(..).select(_.join( _.filter(fields, field =>
        req.ability.can('read', 'Post', field)
      ),  ' '))
.accessibleBy(req.ability, 'read')
.then(post => {});
```

Initially, I thought the `accessibleRecordsPlugin` would handle filtering fields that the user doesn't have access to but I guess that's not the case. Is there a way to add this feature?

Thank you!

**Comment by wassgha** [comment]
Took some digging but I just found `permittedFieldsPlugin`, closing this for now. Maybe make it a bit more visible in the documentation?

**Comment by stalniy** [comment]
Hello, 

Thanks for the issue! However I’m not sure whether this is a right way to do this.

First of all, you may need fields which user can’t access in your business logic calculations. 

Secondly, field access may be restricted per record (by using rules with conditions), so it won’t be possible to request records with specified fields from database without additional filtering on Nodejs side. 

So, these are my suggestions:
- if you don’t have restriction on fields with conditions you can do this:

```js
Post.select(Post.permittedFieldsBy(ability).join(‘ ‘)).accessibleBy(ability)
```
But as I said it doesn’t guaranty the right output if you have rules which restricts fields for specific records:

```js
can(“read”, “Post”, [“title”, “description”], { id: 2 })
```

- to guaranty that output will have exactly those fields which you specified in abilities, you need to do this:

```js
const records = await Post.accessibleBy(ability)

// do business logic
const response = records.map(record => _.pick(record, record.permittedFieldsBy(ability))
```

So, what you need is `permittedFieldsBy` method :)

Hm... after weighting all this stuff now I think that I could overwrite records `toJSON` method. 

Read [here](https://github.com/stalniy/casl/blob/master/packages/casl-mongoose/README.md) about `permittedFieldsPlugin`

**Comment by stalniy** [comment]
Actually I can't change `toJSON` method of records because I don't have an instance of `Ability` there. The only possible way is something like this:

```js
record.toJSON({ ability })
```

Which I think is error prune because people may forget to pass `ability` inside. So, I think what I showed above is a better and pretty simple way. Especially because you use `lodash` or `underscorejs` library.

What do you think on this?

**Comment by stalniy** [comment]
Please check this repository for an example https://github.com/stalniy/casl-mongoose-example/blob/master/index.js

**Comment by stalniy** [comment]
I close this as wontfix because of:
- sometimes it may be useful to have access to forbidden fields on  business logic level
- it’s not possible to select accessible fields without fetching query results as shown in https://github.com/stalniy/casl-mongoose-example/blob/master/index.js
