### ISSUE TITLE
@casl/angular@8.2.2 npm package is missing content

### ISSUE THREAD

**Issue by daiscog** [stalniy/casl#852]
The `@casl/angular@8.2.2` is missing the dist dir contain the sources:

![Screenshot 2023-11-21 at 15 52 32](https://github.com/stalniy/casl/assets/5968668/f27148c4-92e4-4a24-ac95-2ba2f5e0c532)

The package is therefore unusable.

**Comment by stalniy** [comment]
Hmm, I’ll check it a bit later today. It was released trough automated release GH action and probably pre-hooks in npm scripts were skipped. That’s why there is no dist

**Comment by stalniy** [comment]
should be fixed in 8.2.3, please double check

**Comment by daiscog** [comment]
@stalniy yes, thanks, fixed in 8.2.3
