### ISSUE TITLE
[not urgent] CLI Yarn warning: @casl/vue 1.x requests version lower than current 6.5.0

### ISSUE THREAD

**Issue by scheinercc** [stalniy/casl#869]
**Describe the bug**
Yarn warning
```
@casl/ability is listed by your project with version 6.5.0, which doesn't satisfy what @casl/vue (pa3960) requests (^2.0.0 || ^3.0.0 || ^4.0.0 || ^5.1.0)
```

**To Reproduce**
1. Follow steps for Vue 2.x from https://casl.js.org/v6/en/package/casl-vue
2. `yarn add @casl/vue@1.x @casl/ability`
3. CLI yarn warning as above

**Expected behavior**
No CLI warning about a version mismatch

**CASL Version**

`@casl/ability` - v6.5.0
`@casl/vue` - v1.2.3

**Environment**:

node v21.2.0
yarn v4.0.2

**Comment by stalniy** [comment]
casl/vue@1.x won't be supported anymore, I don't plan to keep it up to date with latest casl/ability

**Comment by scheinercc** [comment]
That's fair enough. Would you say it's safest then to downgrade to latest @casl/ability 5.x or just upgrade until @casl/ability with casl/vue@1.x breaks and then revert to previous version and lock it?

**Comment by stalniy** [comment]
Look through changelog between 5.x and 6.x and decide whether you are affected. 

Obviously it would be good to upgrade Vue to latest BUT I know life is hard)
