### ISSUE TITLE
`findById(..).accessibleBy(..)` returns an array instead of a document

### ISSUE THREAD

**Issue by wassgha** [stalniy/casl#87]
When `accessibleBy` is appended to a `findById` query, the resulting query is a single-object array instead of returning the object itself

**Comment by stalniy** [comment]
This is a bug. Just reverse the order of calls. 

I will fix this tomorrow. Thanks for the issue!

**Comment by Alex0007** [comment]
@stalniy 
findById is `undefined` after using `accessibleBy`.. Is this operator still supported?

```typescript
console.log('find', ArticleModel.accessibleBy(ability).find);
console.log('findOne', ArticleModel.accessibleBy(ability).findOne);
console.log('findById', ArticleModel.accessibleBy(ability).findById);
```

TypeError: ArticleModel.accessibleBy(...).findById is not a function

**Comment by stalniy** [comment]
`accessibleBy` returns mongoose.Query. So if method undefined then it was removed by mongoose author

**Comment by Alex0007** [comment]
@stalniy 
<img width="863" alt="Screenshot 2022-10-17 at 03 42 21" src="https://user-images.githubusercontent.com/1143226/196064419-b41fcf3c-e8d9-4e53-b788-fac6773ca635.png">

Method is still there

```typescript
console.log('1', ArticleModel.findById('test').accessibleBy(ability).getQuery());
console.log('2', ArticleModel.accessibleBy(ability).findById('test').getQuery());
```
Output:
```
1 { _id: 'test', '$and': [ {} ] }
TypeError: ArticleModel.accessibleBy(...).findById is not a function
```

**Comment by stalniy** [comment]
There are 2 types of methods:
- static “class”/model methods
- query methods 


What you need to check is `ArticleModel.find().findById()`
