### ISSUE TITLE
cannot check ability if rules are loaded from database then we create ability using mongoCreateAbility

### ISSUE THREAD

**Issue by saeidalidadi** [stalniy/casl#870]
**Describe the bug**
If we load the rules from a database as JSON and create the ability using createMongoAbility 
then we cannot check ability against classes of subject types.

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
  🔹Create some rules as JSON objects.
  🔹Create the ability using the rules with `createMongoAbility`.
  🔹Aslo pass `detectSubjectType` function as the options of `createMongoAbility` that logs something.
  🔹Check the ability against one action like 'create' or 'update' with a `SubjectClass`.
```typescript
class User {}

const rules = [{ action: "create", subject: "User" }];

const ability = createMongoAbility(rules, {
  detectSubjectType: (objectClass) => {
    console.log('Subject type detection');
    return objectClass.constructor;
  },
});
ability.can('create',  User)
// OR
ability.can('create', new User)
```

**Expected behavior**
the result should be true if the rules allow that action and subject.

**Interactive example** (optional, but highly desirable)
[Example](https://codesandbox.io/p/sandbox/casl-bug-createmongoability-cxkl39)

**CASL Version**

`@casl/ability` - v6.5

**Environment**:

Node.js v21.2
Typescript v5.3.3

**Comment by stalniy** [comment]
Please provide an example of JSON you try to provide and how you check conditions.

At first sight, it looks like you expect magic to happen :) casl cannot automatically map strings (subject are represented as strings in db, right?) to application classes, you need to do it manually in app logic

**Comment by saeidalidadi** [comment]
thanks @stalniy . I have provided your requirements.

**Comment by stalniy** [comment]
As I said, you need to map subjects from db (ie, strings) to classes by yourself in app code

casl doesn’t do this for you. Subjects in rules and what detectSubjectType return and what you pass to can method must be the same

**Comment by saeidalidadi** [comment]
So I need to have a loop through the rule items and create each ability manually.

```javascript
for (rule in rules) {
   switch(rule.subject) {
     case "User": 
       ability.can(rule.action, User);
   }
}
```

**Comment by saeidalidadi** [comment]
I think I missed something last time so I want to open this issue again
Please look at this example and guess why the `detectSubjectType`  is not called.
[Example](https://codesandbox.io/p/sandbox/casl-bug-createmongoability-forked-c2k23s?file=%2Fsrc%2Findex.ts%3A9%2C62)

**Comment by stalniy** [comment]
You need to map through your rules after db fetch and replace subject string with corresponding class ref

```ts
const rulesFromDb = …
const mapping = { User: User }
const rules = rulesFromDb.map(r => {
  return { …r, subject: mapping[r.subject] }
}) 

const ability = createMongoAbility(rules)
```

**Comment by stalniy** [comment]
Then use the code as previously, no need to use switch stmt

as to about why detectSubjectType is not called, it’s called only for instances. If you pass class or string, it’s perceived as subjectType without additional checks

**Comment by stalniy** [comment]
By the way, I can’t open your sandbox examples

**Comment by saeidalidadi** [comment]
Thanks, @stalniy, I was wrong about passing subject type to the `can`  method, as you are saying it MUST be an instance of the subject's class.
Sorry, I changed the example sandbox to be public you are allowed to open it now.
