### ISSUE TITLE
`rulesToQuery` should be generic over the return type of `RuleToQueryConverter`

### ISSUE THREAD

**Issue by jarpoole** [stalniy/casl#875]
Currently the signature of `rulesToQuery` is roughly (omitting irrelevant details) 

```ts
(ability: T, action, subjectType, convert: RuleToQueryConverter<T>): AbilityQuery | null
```

The issue is that rule to query function takes in a rule and returns `object` and therefore `rulesToQuery` has no choice but to return `AbilityQuery<object>`. 

Ideally the return type of `convert` should drive the generic parameter of `AbilityQuery`. For example:

```ts
type RuleToQueryConverter<T extends AnyAbility, R> = (rule: RuleOf<T>) => R;
function<T, R>(ability: T, action, subjectType, convert: RuleToQueryConverter<T, R>): AbilityQuery<R> | null
```

**Comment by stalniy** [comment]
Agree

**Comment by jarpoole** [comment]
@stalniy Shall I raise a PR? Scope seems really manageable to me but maybe I'm missing something.

**Comment by stalniy** [comment]
Would be awesome  👍. If you can make it work with backward compatibility in mind, then I will accept and publish new version
