### ISSUE TITLE
Update ability JSON

### ISSUE THREAD

**Issue by roylans** [stalniy/casl#885]
I am implementing casl using JSON this is my ability:

```
import { createMongoAbility } from '@casl/ability'

export default createMongoAbility([
  {
    action: 'read',
    subject: 'all'
  },
])
```

but I want to update the ability after logging in:

```const updateAbility = (roles: string[]) => {
     
     const rules = .....

      ability.update(rules)
    }
```

but I don't know how to configure the rules using typescript
If anyone can give me a hand I would appreciate it.

**Comment by stalniy** [comment]
not an issue with casl, please look into https://github.com/stalniy/casl-examples
