### ISSUE TITLE
Unable to import `reactiveAbility` from casl/vue

### ISSUE THREAD

**Issue by Waqar-SE** [stalniy/casl#890]
**Describe the bug**
Unable to import `reactiveAbility`

**To Reproduce**
Try to import `reactiveAbility` and it will fail as index.js doesn't provide it.

**Expected behavior**
Successful import of `reactiveAbility`

**CASL Version**
`@casl/vue` - v

**Environment**:

Node 20, Vue 3

**Comment by stalniy** [comment]
I has never been a part of public interface. Could you please explain why do you need it?

**Comment by Waqar-SE** [comment]
For me the usecase is providing abilities to render function when testing the components.

**Comment by stalniy** [comment]
in this case it's an improvement not a bug. Why cannot you use plugin or provide/inject in tests?

**Comment by Waqar-SE** [comment]
To be able to provide the ability I need to build it, that's where the reactive ability is needed.

**Comment by stalniy** [comment]
You don’t need it because it’s hidden inside `provideAbility` and `abilitiesPlugin`

build ability in any way you like, casl/vue will make it reactive when you provide it. See the code:

https://github.com/stalniy/casl/blob/master/packages/casl-vue/src/useAbility.ts#L17

**Comment by stalniy** [comment]
Close as stale. Feel free to provide more details

**Comment by Waqar-SE** [comment]
Sorry, couldn't reply back. 

The hook doesn't work when testing as the `options` in [render(component,options)](https://testing-library.com/docs/vue-testing-library/api/#rendercomponent-options) are supposed to be object not a hook.
