### ISSUE TITLE
@casl/ability/extra/package.json contains a typo preventing Jest from resolving the package correctly

### ISSUE THREAD

**Issue by neketka** [stalniy/casl#891]
**Describe the bug**
When importing from @casl/ability/extra, Jest will complain about the module not being found.

**To Reproduce**
1. Import from @casl/ability/extra
2. Run a Jest test

**Expected behavior**
The imports should be correctly resolved while running under Jest. This can be fixed if any instances of "extra.js" in the package.json are replaced with "extra/index.js".

**CASL Version**

`@casl/ability` - v6.7.0
`@casl/prisma` - v1.4.1

**Environment**:
Node 18

**Comment by stalniy** [comment]
Thank you for the issue! Will fix today/tomorrow
