### ISSUE TITLE
Typescript issue with the new ofType of accessibleBy

### ISSUE THREAD

**Issue by kemalcany** [stalniy/casl#899]
Hello! 

Typescript doesn't allow the mongoose 8.0.1 package usage as described in the latest docs (link and the TS error screenshot below)

https://casl.js.org/v6/en/package/casl-mongoose#accessible-by-helper

![image](https://github.com/stalniy/casl/assets/2018725/ad4434f7-e435-4cc0-9c34-12045d2c6c25)

**Comment by stalniy** [comment]
I think you use the old version of @casl/mongoose very likely 7.x. This is expected because in that version `accessibleBy` returns proxy which is then on property access returns AbilityQuery. this is not the case for 8.x

I double checked and it works as expected -> https://playcode.io/1816910

**Comment by stalniy** [comment]
Close as it’s not casl issue but feel free to comment

**Comment by kemalcany** [comment]
Apologies it was my mistake with the editor. Thank you for looking into it!
