### ISSUE TITLE
Use function name "can" and "cannot" in both define and check mode can be confusing.

### ISSUE THREAD

**Issue by jludev1** [stalniy/casl#90]
Suggest using function names like "addRule" to make the intention more clear in define mode.

**Comment by stalniy** [comment]
You can use different names in your code 

```js
const ability = AbilityBuilder.define((allow, forbid) => {
  allow(“read”, “Post”, {....})
  forbid(“delete”, “Post”)
})

// in extract mode 
const {.can: allow, cannot: forbid } = AbilityBuilder.extract()

allow(...)
forbid(...)

const ability = new Ability(rules)
```

I will add thi to the docs. 

Just to note that `addRule` is to expressive because the counterpart for `cannot` will need to be something like `addInvertedRule` what seems even more confusing for me :)

**Comment by jludev1** [comment]
I like the names you pick and the solution you proposed. :)
