### ISSUE TITLE
Unable to understand the implementation of CASL in nextjs App

### ISSUE THREAD

**Issue by deepakshrma30** [stalniy/casl#909]
**Describe the bug**
Unable to understand how can i define my route path which will be restricted for the subadmin

**To Reproduce**
1. Ability configuration (rules, detectSubjectType, etc)
2. How do you check abilities

**Expected behavior**
```
const defineRulesFor = (role, subject) => {
  const data = window.localStorage.getItem('userData')
  const userData = JSON.parse(data)
 

  const { can, rules } = new AbilityBuilder(AppAbility)
  if (role === 'ADMIN') {
    can('manage', 'all')

  } else if (role === 'client') {
    can(['read'], 'acl-page')
  } else if (role === 'SUBADMIN') {
 
    can('read','amenities') // this thind does not work
  } else {
    can(['read', 'create', 'update', 'delete'], subject)
  }

  return rules

```
![Screenshot 2024-05-06 160003](https://github.com/stalniy/casl/assets/109404940/10882f4c-5b12-48e3-961f-a7d50fcc8672)
}

**Interactive example** (optional, but highly desirable)
provide a link to the example from http://repl.it/, https://codesandbox.io/ or similar, so we can quickly test and provide feedback. Otherwise

**CASL Version**

`@casl/ability` - v

`@casl/react` - v

**Environment**:

**Comment by stalniy** [comment]
Did you look into examples? https://github.com/stalniy/casl-examples

**Comment by stalniy** [comment]
Close as this is not an issue with casl. Ask question on stackoverflow

I’ll create nests example at some point later

**Comment by deepakshrma30** [comment]
thanks for the help
