### ISSUE TITLE
bug: subject helper error

### ISSUE THREAD

**Issue by Nishchit14** [stalniy/casl#912]
**Describe the bug**
When I use `subject` helper multiple time in the same function to check multiple permission then it's showing error

```ts
ability.can('create', subject('folder', {}));
ability.can('read', subject('chat',{}));
```

**Error**
```
Error: Trying to cast object to subject type chat but previously it was casted to folder
```

**CASL Version**

`@casl/ability` - v6.7.1

**Environment**:
Nodejs version v21

**Comment by stalniy** [comment]
Cannot reproduce, If you look into code this error is thrown only if you try to change the type of previously used object - https://github.com/stalniy/casl/blob/master/packages/casl-ability/src/utils.ts#L25

**Comment by stalniy** [comment]
close as I stale. Feel free to comment and provide additional deteils
