### ISSUE TITLE
How to perform conditions on nested objects?

### ISSUE THREAD

**Issue by hugomendonca98** [stalniy/casl#914]
Hello, I'm trying to access properties in nested objects and perform conditions, but I can't do this.

`  builder.can("VIEW_POST_TAGS", "PUBLICATION", {
      creator: { role: { $ne: "CONTENT_CREATOR" } },
    });`

**Comment by stalniy** [comment]
https://casl.js.org/v6/en/guide/conditions-in-depth#match-nested-property-value

**Comment by hmd-ai** [comment]
@stalniy , Is there any way to support querying nested objects without using the dot notation. It becomes tedious when there are a lot of nested fields?

**Comment by stalniy** [comment]
If it’s mongo, you can try to use $elemMatch operator. There are also utility helpers for typescript which allow to generate flat type with dots from type with nested fields
