### ISSUE TITLE
Angular 18 support

### ISSUE THREAD

**Issue by NrujalSharma** [stalniy/casl#935]
**Is your feature request related to a problem? Please describe.**
For us relying on @angular/casl and want to upgrade our Angular apps to Angular 18 it's not possible at the moment.

**Describe the solution you'd like**
@angular/casl support for Angular 18

**Comment by vkarchevskyi** [comment]
It seems like dependency rules in repository support Angular 18, but NPM release is still outdated.

https://github.com/stalniy/casl/commit/4972cb26ed450a4e45e93e5c72d9a6a49fbe0201

**Comment by Nabelops** [comment]
+1

**Comment by stalniy** [comment]
I finally fixed automatic releasing, so the next time renovate PR pass all checks, changes will be released without my intervention.

Available in the latest @casl/angular
