### ISSUE TITLE
Not attribute shouldn't be mandatory in casl-react when using Typescript

### ISSUE THREAD

**Issue by zareth** [stalniy/casl#95]
The not attribute for the types CanProps and CanPropsStrict in @casl/react is defined as mandatory. From looking at the examples it seems this attribute should be optional.

The following should be possible (taken from project readme)
```javascript
<Can I="create" a="Post" ability={ability}>
  () => <button onClick={this.createPost.bind(this)}>Create Post</button>
</Can>
```
The above will result in a type error as the not attribute is missing.

With the current type definitions you have to write it as follows
```javascript
<Can not={false} I="create" a="Post" ability={ability}>
  () => <button onClick={this.createPost.bind(this)}>Create Post</button>
</Can>
```

**Comment by stalniy** [comment]
Fixed in `@casl/react@0.7.2`
