### ISSUE TITLE
A rulesToAst case that ignores conditions

### ISSUE THREAD

**Issue by dennemark** [stalniy/casl#957]
Hi,

I am trying to generate a AST for my CASL/prisma rules. The following case ignores the rules with conditions, if there is one rule without condition. Most probably this is on purpose.
```ts
can('read', 'User', ['email'])

can('read', 'User', ['email', 'id'], {
    posts: {
            creatorId: userId
    }
})
```
What it says is 
- A user can be read by everyone. But only the email.
- If the User is the creator of a post, the id can be read, too.

Looking at `rulesToQuery` it does not deal with field access, and if there is a rule without can condition all other can rules with conditions are ignored. 
https://github.com/stalniy/casl/blob/c114197697ea446d2f3469152dfee34d741e4f03/packages/casl-ability/src/extra/rulesToQuery.ts#L25
I am wondering if this is a bug - probably fixing it is a breaking change for some applications. And I am wondering, if it would be possible to somehow get rulesToAst with consideration of conditions.

My only other way to get around it, would be to recreate the functions in my package and add ucast dependency.
It is for this one: https://github.com/dennemark/prisma-extension-casl

**Comment by dennemark** [comment]
Might have found a workaround. In the case of casl/prisma
```ts
  const ability = createPrismaAbility(abilities.rules.filter((rule) => rule.conditions))
  const ast = rulesToAST(ability, action, model)
```

**Comment by stalniy** [comment]
It’s actually expected result. 

Field access has no influence on db. Basically you allow reading all Users but only restrict what information can be extracted from particular records. 

To do this there is no easier way than fetch everything and then iterate and retrieve only accessible fields. 

need to double check Prisma version but in mongoose there is a special method that can retrieve accessible fields for “this” particular record

**Comment by stalniy** [comment]
So, you need to think about it this way:
- I can read all users
- I can read only email field on all users 
- If this is me then I can also read “id”

**Comment by stalniy** [comment]
But the actual set of what records you can fetch is not restricted because you can read all emails. If you expect restriction on returned users, how then you can read all emails?

hopefully it makes sense

**Comment by dennemark** [comment]
Ah nice! Thanks for the clarifying reply! Yes I am trying to do all of this logic within the prisma query. It queries all related conditional fields, afterwards it filters them out again with a mask that I created.
So far it seems to work. The workaround above was helpful!

So for the case above I can do  db.user.findMany()  and the result will be
[ { email: 'a', id: 0' } , { email: 'b' } ]

**Comment by stalniy** [comment]
It’s not usually the case that you need to restrict what fields are returned by db. Very often you need all of them in order to do some business logic but then in response you need to return only accessible ones. Those which user can access

imagine you have `enabled` field on user. Obviously, you do not let users toggle this field or even read it because it’s a private thing in your system BUT you need to check whether user is enabled before doing any actions on his behalf (eg, disabled users cannot create blog posts). This is simple example which can be solved on db conditions level but then on app level you will not be able to distinguish whether this user actually exists in db or it’s disabled. Sometimes it’s also important

**Comment by dennemark** [comment]
Thanks, yes! Great thoughts! I am using the normal prisma client to bypass my casl prisma client and do these queries. 
It leads to more queries. But it gives me a better feeling knowing that all relation queries in a graphql request obey the casl rules. For REST endpoints i think i wouldnt need to do this, but for graphql it is easy to do nested queries and get around the authorization logic. :/

If it does not scale well, i will consider returning the full request as well as the mask. So the part that is currently done within the extension to filter the results. Lets see :)
