### ISSUE TITLE
DOC: SQLite vs MongoDB

### ISSUE THREAD

**Issue by sschneider-ihre-pvs** [stalniy/casl#979]
https://github.com/stalniy/casl/blob/f8e594a99c72eccd1aa1e566ba25ffe21a46ad17/docs-src/src/content/pages/cookbook/roles-with-persisted-permissions/en.md?plain=1#L57
SQLite
https://github.com/stalniy/casl/blob/f8e594a99c72eccd1aa1e566ba25ffe21a46ad17/docs-src/src/content/pages/cookbook/roles-with-persisted-permissions/en.md?plain=1#L153
Mongo
I think that doesn't work together

**Comment by stalniy** [comment]
Casl uses mongo conditions to check whether items fit special criteria on JS side, in runtime. It can also convert this to other db queries to run check db level 

this is real example https://github.com/stalniy/casl-persisted-permissions-example
