### ISSUE TITLE
Extends "manage" with another rule

### ISSUE THREAD

**Issue by victorsilent** [stalniy/casl#98]
How can I extend manage ability to include another rule?
Anything like this:
`Ability.addAlias("manage", ["list"]);`
or
`Ability.addAlias("manage", ["list", "manage"]);`

**Comment by stalniy** [comment]
You can create custom alias with name `access`:

```js
Ability.addAlias("access", ["list", "manage"])
```

**Comment by stalniy** [comment]
Another approach is to extend what is inside `manage` (read, create, update, delete)

```js
Ability.addAlias('read', ['list'])

// later when you define rules
const abiltiy = AbilityBuilder.define(can => {
  can('read', 'Product')
})

ability.can('list', 'Product') // true
ability.can('read', 'Product') // true
```

**Comment by victorsilent** [comment]
Thank you sir! I'm implementing the first option right now

**Comment by stalniy** [comment]
Thanks for using CASL! I'm closing this as there are no action items anymore
